### ISSUE TITLE
Invoking constructors changes global this instead of newTarget

### ISSUE THREAD

**Issue by tofpie** [boa-dev/boa#1009]
**Describe the bug**
`String` used as a function call messes up with the global object.

**To Reproduce**

This JavaScript code reproduces the issue:
```javascript
String(10)
this.length
String.prototype.toString.call(this)
```

Running this code, `2` is printed as `this.length` and `"10"` is printed as `String.prototype.toString.call(this)`.

**Expected behavior**
Running this code, `this.length` should stay `undefined` and `String.prototype.toString.call(this)` should throw a `TypeError`.

**Build environment (please complete the following information):**

- OS: Windows 10
- Version: 0.10
- Target triple: x86_64-pc-windows-msvc
- Rustc version: rustc 1.48.0 (7eac88abb 2020-11-16)

**Additional context**
None

**Comment by tofpie** [comment]
This is this part that messes up with the global object when `String` is called directly:

https://github.com/boa-dev/boa/blob/67ee6faa5819ba5e97ae826244a88ce370e32070/boa/src/builtins/string/mod.rs#L132-L153

But I really do not know how to fix that. If anyone has some guidance, I can give it a try though.

**Comment by RageKnify** [comment]
I think this can happen with most builtin constructors, we can generate a similar effect with:
```js
>>  Boolean()
>> this
Boolean { false }
```

I assume we need to change most of the constructors, the spec mentions `newTarget`, which I think can be found in `boa` in https://github.com/boa-dev/boa/blob/7b103a5c0bf29150a9bace87b17b39c9e0e7750d/boa/src/environment/function_environment_record.rs#L57

`rust-analyzer` only spots it only as being declared and initialized so it seems it currently isn't used.
