### ISSUE TITLE
Seemingly wrong comment for Rational in instruction enum

### ISSUE THREAD

**Issue by stephanemagnenat** [boa-dev/boa#1038]
This comment talks about [loading an `f32` immediate](https://github.com/boa-dev/boa/blob/master/boa/src/vm/instructions.rs#L15), but the [parameter is an `f64`](https://github.com/boa-dev/boa/blob/master/boa/src/vm/instructions.rs#L16).

**Comment by jasonwilliams** [comment]
Thanks for spotting that @stephanemagnenat

**Comment by NathanRoyer** [comment]
I'm including a fix in my next PR.
