### ISSUE TITLE
Panic: "invalid or out-of-range date"

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1054]
When running [this](https://github.com/tc39/test262/blob/main/test/annexB/built-ins/Date/prototype/setYear/time-clip.js) ECMAScript test, we get the following panic:

```
thread 'main' panicked at 'invalid or out-of-range date', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/naive/date.rs:173:51
```

This in itself is not very clear, but this comes from the [`setYear()`](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/date/mod.rs#L927-L948) function. This calls to the [`set_components()`](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/date/mod.rs#L210-L314) function which calls `NaiveDate::from_ymd()` instead of `NaiveDate::from_ymd_opt()`, so it can panic if it gets out of range.

A solution would be to change those calls and try to return `NaN` in those cases, but for it to be fully spec compliant we should implement the [`TimeClip()`](https://tc39.es/ecma262/#sec-timeclip) function, which is called from the [`setYear()`](https://tc39.es/ecma262/#sec-date.prototype.setyear) function among others.

**Comment by jevancc** [comment]
Hi, I want to work on this issue. Can you assign it to me?

**Comment by tofpie** [comment]
Sure. Go ahead.
