### ISSUE TITLE
Add dark mode to benchmarks page

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#1055]
Our benchmarks page lives here:
https://boa-dev.github.io/boa/dev/bench/

Its quite useful for reporting how Boa is doing over time, however I can put snippets into release notes because of the white background. It would be nice to have a dark mode toggle on this page which matches the colour of https://boa-dev.github.io/

Benchmark page code lives here:
https://github.com/boa-dev/boa/blob/gh-pages/dev/bench/index.html

Best option is to checkout the gh-pages branch, then run locally.

Same for conformance page https://boa-dev.github.io/boa/test262/

**Comment by SuneelFreimuth** [comment]
I'm a Rust programmer/web developer looking for a good first issue-is this still something worth pursuing? I could implement a toggle-able dark mode this week.

**Comment by Razican** [comment]
> I'm a Rust programmer/web developer looking for a good first issue-is this still something worth pursuing? I could implement a toggle-able dark mode this week.

Sure! That would be very nice indeed. And it would be best if it followed the behaviour of the main / blog page.

**Comment by SuneelFreimuth** [comment]
Got it, I'll make a PR this week using the homepage as an example.

**Comment by SuneelFreimuth** [comment]
I've been having some trouble adjusting the colors of the charts on the benchmarks page, which I think might be due to an old version of Chart.js, namely v.2.9, being loaded from a CDN. Is it alright if I upgrade the page to Chart.js v3.4 (the latest) instead? It adds a variety of useful features.

**Comment by Razican** [comment]
> I've been having some trouble adjusting the colors of the charts on the benchmarks page, which I think might be due to an old version of Chart.js, namely v.2.9, being loaded from a CDN. Is it alright if I upgrade the page to Chart.js v3.4 (the latest) instead? It adds a variety of useful features.
> 
> I'd of course update the existing Chart.js to accomodate v3's API.

Of course, feel free to update dependencies! ChartJS v3 should also perform better :)

**Comment by HalidOdat** [comment]
Closed by #1388
