### ISSUE TITLE
[Optimisation] - Zero cost arguments, create argument objects lazily

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#111]
Benchmarks were added in: https://github.com/jasonwilliams/boa/pull/109
They will introduce a slow down to all function invocations.
It might be an idea to only add an argument object to the function scope when its needed.

## Before and after benchmarks of `arguments`
| Test | PR Benchmark | Master Benchmark | % |
|------|--------------|------------------|---|
| Hello World (Execution) | **168.2±7.00µs** | 173.4±9.18µs | 97% |
| Hello World (Lexer) | **1096.3±28.06ns** | 1136.3±37.10ns | 96% |
| Hello World (Parser) | 1294.0±35.94ns | **1220.6±41.01ns** | 106% |
| fibonacci (Execution) | 5.4±0.16ms | **2.2±0.08ms** | 239% |

**Comment by Razican** [comment]
Hi @jasonwilliams could you please give a bit more insight on what should be done here?

**Comment by jasonwilliams** [comment]
So i think this needs discussion, as i don't have a solution right now.
Basically every time a function is called an arguments object is created, so this degraded performance quite a bit.

There was an idea to only create the arguments object if its used.

**Comment by jasonwilliams** [comment]
Im going to close this as i think we've refactored quite a bit since this was made
