### ISSUE TITLE
setup test262 harness

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#12]
It would be good to start running these https://github.com/tc39/test262/tree/master/test/language

#### Project
https://github.com/jasonwilliams/boa/projects/2

#### Tracking of blocking issues:
 - [x] Exception handling (#377)
 - [x] Function expressions (#266)
 - [x] `this` keyword (#264)
 - [x] Hoisting variables (#376)
 - [x] Goal symbols when lexing (#294)

**Comment by jasonwilliams** [comment]
@vitkarpov if this is too much we could start of by doing what rapidus does for now and start with a few js files to test from https://github.com/maekawatoshiki/rapidus/tree/new-gen/test

**Comment by jasonwilliams** [comment]
A good start could be to have a test file, which pulls in some of the pre-defined bindings before loading a file.  Assert would be a start
https://github.com/tc39/test262/blob/master/INTERPRETING.md#test262-defined-bindings

**Comment by Razican** [comment]
I would like to re-open this. I don't think we are so far away from it, I would say we have to implement the following:
 - [ ] Exception handling (#377)
 - [ ] Function expressions (#266)
 - [ ] `this` keyword (#264)
 - [ ] Hoisting variables (#376)

After that, we can implement an automated process to give stats on what we support, and we can start tackling syntax step by step.

**Comment by Lan2u** [comment]
Now that we have goal symbol support (in the form of #486) is it worth giving this a go - do we have any progress already in terms of running test262 on boa?

**Comment by HalidOdat** [comment]
> Now that we have goal symbol support (in the form of #486) is it worth giving this a go - do we have any progress already in terms of running test262 on boa (like a rust test runner)?

No progress yet in terms of setting up the harness of the tests

**Comment by Lan2u** [comment]
> > Now that we have goal symbol support (in the form of #486) is it worth giving this a go - do we have any progress already in terms of running test262 on boa (like a rust test runner)?
> 
> No progress yet in terms of setting up the harness of the tests

Ok cool, I can potentially start looking at this
