### ISSUE TITLE
Implement global `globalThis` property

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#120]
**ECMASCript feature**

We can add this by adding a new module like `NaN` https://github.com/boa-dev/boa/tree/master/boa/src/builtins/nan and then adding it to the builtin `init` function in `builtins/mod.rs` the value it should contain should be `global.clone()` (this is the value passed to init function)

More information
	- [ECMAScript reference][spec]
    - [MDN][mdn]

[spec]: https://tc39.es/ecma262/#sec-globalthis
[mdn]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

**Comment by zanayr** [comment]
Hello @jasonwilliams, can I take this? :)

**Comment by HalidOdat** [comment]
> can I take this? :)

Sure. go for it! If you have any questions or need some assistance tell us :)

**Comment by zanayr** [comment]
Hello I have issued a PR #495... I'm not sure if I did it correctly, I am getting several failed checks.. I assume I messed up the testing somehow, any tips on how to fix this? Best,

**Comment by zanayr** [comment]
Coool
