### ISSUE TITLE
Github Action to update github pages when a new version is created

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#122]
This page:
https://boa-dev.github.io/boa

Is often behind the actual release. As its a manual job to push the new version.
`git push && git subtree push --prefix dist origin gh-pages`

It would be nice to update the web assembly page when a new version is rolled out.
We already have a github action here:
https://github.com/boa-dev/boa/blob/master/.github/workflows/pull_request.yml

Is it possible to make one which responds to new versions?
It can then run `yarn build` and push to the `gh-pages` branch

**Comment by jasonwilliams** [comment]
@darrylpargeter sure

**Comment by jasonwilliams** [comment]
@darrylpargeter any luck?

**Comment by jasonwilliams** [comment]
The job would need to:
1. `git checkout master`
2. `git clone git@github.com:boa-dev/boa.git --branch gh-pages dist`
2. `yarn build`
3. git push && git subtree push --prefix dist origin gh-pages

**Comment by FrancisMurillo** [comment]
Can I claim this ticket?

**Comment by Razican** [comment]
> Can I claim this ticket?

Sure, go ahead!
