### ISSUE TITLE
Implement `Map.prototype[ @@toStringTag ]`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#1229]
**ECMASCript feature**

Implement [`Map.prototype[ @@toStringTag ]`][spec], as a reference on how to implement it, you can check #1225 (`Math[ @@toStringTag ]`).

[spec]: https://tc39.es/ecma262/#sec-map.prototype-@@tostringtag

**Example code**
This code should now work and give the expected result:
```javascript
let result = (new Map())[Symbol.toStringTag];

console.log(result);
```
The expected output is `"Map"`.

**Comment by wylie39** [comment]
Can I take a stab at this?

**Comment by HalidOdat** [comment]
> Can I take a stab at this?

Sure :)
