### ISSUE TITLE
Implement `BigInt.prototype[ @@toStringTag ]`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#1230]
**ECMASCript feature**

Implement [`BigInt.prototype[ @@toStringTag ]`][spec], as a reference on how to implement you can check #1225 (`Math[ @@toStringTag ]`).

[spec]: https://tc39.es/ecma262/#sec-bigint.prototype-@@tostringtag

**Example code**
This code should now work and give the expected result:
```javascript
let result = BigInt.prototype[Symbol.toStringTag];

console.log(result);
```
The expected output is `"BigInt"`.

**Comment by n14little** [comment]
I'll take this.
