### ISSUE TITLE
Implement `Symbol.prototype[ @@toStringTag ]`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#1231]
**ECMASCript feature**

Implement [`Symbol.prototype[ @@toStringTag ]`][spec], as a reference on how to implement you can check #1225 (`Math[ @@toStringTag ]`).

[spec]: https://tc39.es/ecma262/#sec-symbol.prototype-@@tostringtag

**Example code**
This code should now work and give the expected result:
```javascript
let result = (Symbol())[Symbol.toStringTag];

console.log(result);
```
The expected output is `"Symbol"`.

**Comment by moadmmh** [comment]
I'll take this
