### ISSUE TITLE
Implement `Symbol.prototype[ @@toPrimitive ]( hint )`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#1233]
**ECMASCript feature**

Implement [`Symbol.prototype[ @@toPrimitive ]( hint )`][spec].

The to primitive function described in [spec][spec] can be created with `FunctionBuilder` and it can be added to `Symbol.prototype` with `ConstructorBuilder::property()` method. 

[spec]: https://tc39.es/ecma262/#sec-symbol.prototype-@@toprimitive

**Comment by moadmmh** [comment]
I'll take this

**Comment by jedel1043** [comment]
@moadmmh Are you still working on this? If you have any questions about the implementation, don't hesitate to ask us! 😁

**Comment by Nimpruda** [comment]
All the tests for Symbol.toPrimitive and there is already a Well Known Symbol named to_primitive. Furthermore, I tried running the example from mdn and it works just like it's supposed to. 

What am I supposed to fix this ? Could you tell me where I should start ? 

Thanks and sorry for my english I'm not native.

**Comment by jedel1043** [comment]
> All the tests for Symbol.toPrimitive and there is already a Well Known Symbol named to_primitive. Furthermore, I tried running the example from mdn and it works just like it's supposed to.
> 
> What am I supposed to fix this ? Could you tell me where I should start ?
> 
> Thanks and sorry for my english I'm not native.

I think you're confusing `Symbol.toPrimitive` with `Symbol.prototype[ @@toPrimitive ]`
