### ISSUE TITLE
`Math.hypot.length` should be `2`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#1269]
**Describe the bug**
`Math.hypot.length` should be `2` not `1`

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.

This JavaScript code reproduces the issue:
```javascript
var a = Math.hypot.length;
a;
```

**Expected behavior**
Running this code, `a` should be set to `2` and printed, but `a` is instead set to `1`.

[spec](https://tc39.es/ecma262/#sec-math.hypot)

**Comment by Razican** [comment]
As a hint to anyone coming to implement this, this is part of the `Math` builtin implementation :) feel free to ask questions on how this is implemented.

**Comment by moadmmh** [comment]
I can fix this
