### ISSUE TITLE
Implement String prototype methods

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#13]
## String prototype methods
These methods would be added to the String prototype object which is implemented here:
https://github.com/boa-dev/boa/blob/master/boa/src/builtins/string/mod.rs

Spec: https://tc39.es/ecma262/#sec-properties-of-the-string-prototype-object

**Implementation Example?**
See [charAt()](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/string/mod.rs#L77-L119) and charCodeAt() for a good example

- [x] charAt()
- [x] codePointAt()
- [x] charCodeAt()
- [x] concat() 
- [x] endsWith()
- [x] includes()
- [x] indexOf()
- [x] lastIndexOf()
- [ ] localeCompare()
- [x] match()
- [x] matchAll()
- [x] normalize()
- [x] padEnd()
- [x] padStart()
- [x] repeat()
- [x] replace()
- [x] replaceAll()
- [x] search()
- [x] slice()
- [x] split()
- [x] startsWith()
- [x] substring()
- [ ] toLocaleLowerCase()
- [ ] toLocaleUpperCase()
- [x] toLowerCase()
- [x] toString()
- [x] toUpperCase()
- [x] trim()
- [x] trimEnd()
- [x] trimStart()
- [x] toString()
- [x] valueOf()
- [x] [@@iterator]()

**Comment by callumquick** [comment]
I have started to write some implementations for concat() and repeat() but have encountered an issue: currently none of the String prototype methods work, even existing charAt and charCodeAt:

Using:
```
let a = "Hello world".chatAt(2);
console.log(a);
```

Results in the buffer holding only: "Error: undefined"

Is this a known issue or needs to be resolved before prototype methods can be added?

**Comment by jasonwilliams** [comment]
Hey @callumquick hmm that’s interesting, I will take a look, I wonder if some of the changes have caused this to no longer work.

**Comment by callumquick** [comment]
Thanks @jasonwilliams, generating the string via `new String(..)` is working with charAt(), charCodeAt(). Will now test with my new implementations.

**Comment by callumquick** [comment]
On the topic of the boxing of the primitive string, the only current issue with concat(), repeat(), slice() and the other methods that should return strings is that through `to_value()` they come out as "string literals" again. This means you can't do the following:
```
let a = new String("Hello world");
a.concat("! ").repeat(2);
```
Is there an easy way to cause concat, repeat etc to return not just string "values" but string objects? Would this be solved by auto-boxing string literals (#29)?

**Comment by jasonwilliams** [comment]
Now you're asking the right questions!
We can't do this because the return type of those methods are `string` types not objects. 
Those strings would need to be re-boxed again (yep this is why boxing/un-boxing is a big performance hit and engines often try to find ways around it). 

It would be against the spec to return a String instance instead of a string literal.
https://tc39.es/ecma262/#sec-string.prototype.concat

I once thought a nice optimisation would be to just convert a string value to a string instance and leave it at that, but then that would break `typeof` checks in your code, as you're changing the type of an object underneath someone, so this is impossible.

> Would this be solved by auto-boxing string literals (#29)?
Basically yeah

**Comment by callumquick** [comment]
@jasonwilliams Thanks for clarifying the spec's position (I had overlooked the subtlety of the concat/repeat/slice methods returning values only). 

As a heads up, next I will probably take a look at the set of these methods which take a "searchString" argument (so not patterns yet): startsWith(), endsWith(), includes(), indexOf() and lastIndexOf().

**Comment by brian-gavin** [comment]
Hey, the links in this issue are out of date due to some code reorg!

Current location of String is [here](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/string/mod.rs)

**Comment by Razican** [comment]
> Hey, the links in this issue are out of date due to some code reorg!
> 
> Current location of String is [here](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/string/mod.rs?rgh-link-date=2020-06-01T02%3A38%3A22Z)

Good catch! I updated the links, but note that some of this is probably blocked until #419 lands :)

**Comment by HalidOdat** [comment]
@joshwd36 has implemented `String.prototype[@@Symbol.iterator]` in #576

**Comment by RageKnify** [comment]
Added `split()`, being worked on in #1026

**Comment by neeldug** [comment]
@jasonwilliams I believe this list is missing [replaceAll](https://tc39.es/ecma262/#sec-string.prototype.replaceall).

**Comment by RageKnify** [comment]
@neeldug there's still a few methods in the check list, should this issue be closed?

**Comment by neeldug** [comment]
Shouldn’t be closed, only checked off.

**Comment by jedel1043** [comment]
Closing in favour of #1562.
