### ISSUE TITLE
Some Test262 tests run forever

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1306]
**Describe the bug**
We are ignoring some Test262 tests because they run forever. Here you have the list of them:

 - [`test/built-ins/String/prototype/padStart/fill-string-empty.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/String/prototype/padStart/fill-string-empty.js)
 - [`test/built-ins/String/prototype/padEnd/fill-string-empty.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/String/prototype/padEnd/fill-string-empty.js)
 - [`test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js)
 - [`test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js)
 - [`test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js)
 - [`test/built-ins/Array/prototype/includes/length-boundaries.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/includes/length-boundaries.js)

**To Reproduce**
You can reproduce any of them by running the following command after removing them from the `test_ignore.txt` file:
```bash
cargo run --release --bin boa_tester -- run -s {test_path}
```

**Expected behavior**
These tests should run reasonably fast (usually not more than a second), but they run forever. A fix should make this happen. Some of them might be easier to fix than others.

**Comment by neeldug** [comment]
For the concat, I understand there is a check missing from spec here: `iii. If n + len > 253 - 1, throw a TypeError exception.`, however, I'm unable to understand completely how the implementation follows the spec for the spreadable section [here](https://github.com/boa-dev/boa/blob/9497636e6ca4dc7b449591b3b481a270cec3141b/boa/src/builtins/array/mod.rs#L423).
