### ISSUE TITLE
Support for shorthand object literals

### ISSUE THREAD

**Issue by ClementNerma** [boa-dev/boa#1308]
**Describe the bug**
The following code doesn't compile:

```js
const message = 'Hello world!';
const wrapper = { message };
```

**Expected behavior**
It should work as an equivalent of `const wrapper = { message: message };`

**Build environment:**
Boa Playground

**Comment by Razican** [comment]
For anyone willing to implement this, this requires a change in the parser.

The spec on object initializers can be found [here](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-object-initializer). And our implementation can be found in the [`boa/src/syntax/parser/expression/primary/object_initializer/mod.rs`](https://github.com/boa-dev/boa/blob/f8d0b66daf92c52c187c43eb3b3e18fbe71b4da0/boa/src/syntax/parser/expression/primary/object_initializer/mod.rs) file.

As you can see, an `ObjectInitializer` is a `PropertyDefinition` list. In our implementation of the parser for a `PropertyDefinition` we don't check for all the options in the spec. In particular, we would need to check for the `IdentifierReference` option.

One option would be to create sub-parsers for those, and somehow decide which of them to use, or to just extend this method to check for the rest of the options.

I think that for `IdentifierReference` we already have one parser implemented so it could be used.

**Comment by davimiku** [comment]
Hi @Razican , I would like to try implementing this. Do you think the scope of this issue would include adding `IdentifierReference`  in the [Executable trait for Object](https://github.com/boa-dev/boa/blob/master/boa/src/syntax/ast/node/object/mod.rs#L98) also?

**Comment by Razican** [comment]
> Hi @Razican , I would like to try implementing this. Do you think the scope of this issue would include adding `IdentifierReference`  in the [Executable trait for Object](https://github.com/boa-dev/boa/blob/master/boa/src/syntax/ast/node/object/mod.rs#L98) also?

Let's assign it to you then :)

I don't think we need to change that. This is just a shorthand for a "property definition" right? Where the name of the property is the name of the variable containing the value. I think we just need to generate a `PropertyDefinition` from the parser itself.
