### ISSUE TITLE
Add Garbage Collection Triggering Function

### ISSUE THREAD

**Issue by evalPenny** [boa-dev/boa#1315]
Add Garbage Collection Triggering Function since I have a huge amount of data.
*Note: I don't think this function exists, yet.*

**Comment by Razican** [comment]
Can't this be done by running [`gc::force_collect()`](https://docs.rs/gc/0.4.1/gc/fn.force_collect.html)?

**Comment by evalPenny** [comment]
> Can't this be done by running [`gc::force_collect()`](https://docs.rs/gc/0.4.1/gc/fn.force_collect.html)?

Probably, but I want a built-in function to trigger the garbage collection. So, I could trigger the garbage collection in JavaScript as well.

**Comment by Razican** [comment]
> > Can't this be done by running [`gc::force_collect()`](https://docs.rs/gc/0.4.1/gc/fn.force_collect.html)?
> 
> Probably, but I want a built-in function to trigger the garbage collection. So, I could trigger the garbage collection in JavaScript as well.

Is this part of the ECMAScript specification? If it's not, it should not be included in a JS engine. It can, however, be easily extended using the Boa API.

You just need to define the function and add it to the global object:

```rust
/// `gcCollect()` function triggers garbage collection.
fn gc_collect(_this: &Value, _aargs: &[Value], _context: &mut Context) -> boa::Result<Value> {
    gc::force_collect();
	Ok(Value::undefined())
}

fn main() {
	// [...]

	let mut context = Context::new();

	context
        .register_global_function("gcCollect", 0, gc_collect)
        .map_err(|e| {
            format!(
                "could not register the global gcCollect() function:\n{}",
                e.display()
            )
        })?;

	// [...]
}
```

You can later use the `context` object in the `main()` function to run any JS that calls the `gcCollect()` function that will manually trigger garbage collection.
