### ISSUE TITLE
Split `Node` into `Expression`, `Statement` and `Declaration`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#1371]
Currently `Node` is both a expression, statement and declaration. It would be better if `Node` was split into how the spec describes it `Expression`, `Statement` and also `Declaration`. Why do we want this? Right now we don't differentiate between statements (like `if`, `while`, etc) and expressions (like `2 + 2`), while we could make it work like this, it makes somethings awkward like `if (cond) {}`, `cond` should only an expression, and when we parse it we check for this, but some checks can be elided if we leverage the type system, making illegal state unrepresentable.

We want to match to what [astexplorer](https://astexplorer.net/#/gist/ecf73e65e156aa22ecf8f5d3c1d67613/584573b039b672ba14605eb3208bb7f0057499c7) outputs.

**Comment by jtmorrisbytes** [comment]
Is anyone working on this?

**Comment by Razican** [comment]
> Is anyone working on this?

I don't think so, do you want me to assign it to you?

**Comment by pdogr** [comment]
If this is still available, can I work on this?

**Comment by jedel1043** [comment]
> If this is still available, can I work on this?

We haven't assigned someone, so please do! Let me assign it to you

**Comment by jedel1043** [comment]
I'll work on this in the next days :)
