### ISSUE TITLE
Implement function declaration on VM

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#1430]
@HalidOdat as the VM doesn't support function declarations yet do you have any idea in mind how we would do this?
im guessing a new code block would need to be created and instructions within that function would need to be added to `code_block.code`.

We would need a stack to hold `code_block`s and switch over to one when calling the function

**Comment by HalidOdat** [comment]
Yeah. I already have a semi-working implementation, it will require a lot of refactoring to make it fully functional.
