### ISSUE TITLE
`delete` failure should throw on strict mode

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#1504]
Subtask of #815

With #1499 we got a regression on a test that showed we aren't handling correctly `delete`. This is the new test:
```Javascript
// CHECK#1
verifyNotConfigurable(Boolean, "prototype");

assert.throws(TypeError, () => {
  delete Boolean.prototype;
});
```

And this is the previous version of the same test:
```Javascript
// CHECK#1
verifyNotConfigurable(Boolean, "prototype");

try {
  if (delete Boolean.prototype !== false) {
    $ERROR('#1: Boolean.prototype has the attribute DontDelete');
  }
} catch (e) {
  if (e instanceof Test262Error) throw e;
  assert(e instanceof TypeError);
}
```

`delete` should throw an error on strict mode, but on

https://github.com/boa-dev/boa/blob/59c56c50f31075b1b7df17948d1e3dd2470c04ea/boa/src/syntax/ast/node/operator/unary_op/mod.rs#L93-L108

we don't consider strict mode when deleting.

If we want to closely follow the spec, we would need to refactor `Executable::run` to return a `CompletionRecord | ReferenceRecord` type, or split operations that return `ReferenceRecord` and operations that return `CompletionRecord`. It's not trivial whether there is a way to recognize if an `Executable::run` was executed inside strict code.

Suggestions are greatly appreciated.

**Comment by Razican** [comment]
We will need a "strict" variable in the context, that we will set to `true` or `false` if we are or not in strict mode. We already do so for parsing and lexing.
