### ISSUE TITLE
Moving a `JsObject` inside a closure causes a panic

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#1515]
**Describe the bug**
Currently moving any `Gc<T>` inside a closure causes a panic. This issue comes from https://github.com/Manishearth/rust-gc/issues/50, and it doesn't seem like it will get fixed until there's some API for garbage collectors in rustc.
However, we currently allow moving `JsObjects` and `JsValues` inside closures, which causes a panic on destruction.

**To Reproduce**
```Rust
use boa::{Context, JsValue};

fn main() -> Result<(), JsValue> {
    let mut context = Context::new();

    let object = context.construct_object();

    let moved_object = object.clone();

    context.register_global_closure("closure", 0, move |_, _, _| {
        // This value is captured from main function.
        moved_object.is_array();
        Ok(JsValue::Undefined)
    })?;

    Ok(())
}

```

**Additional comments**
Should we restrict closures to only `Fn(..) + Copy`? Or should we allow any Fn and document that moving a `JsObject` into a closure causes a panic?
Maybe we could even make all closures `Fn(..) + Copy` and ask the user to pass a `Captures` type, then we change the definition of our closures to `Fn(&JsValue, &[JsValue], &mut Closure, Box<dyn Any>)` and ask the user to downcast the `dyn Any` to the type of its `Captures`. This allows maximum flexibility because the user can pass `JsValue` and `JsObject`, but it's also not very ergonomic.

**Comment by Razican** [comment]
@HalidOdat does it make sense to not have the `register_global_closure()` API for 0.13?
