### ISSUE TITLE
Implement `CompletionRecord` type

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#1542]
Related discussion on #1541 

The [`Completion Record`](https://tc39.es/ecma262/#sec-completion-record-specification-type) type should live in the `exec` module, inside `mod.rs` if the implementation is simple enough or in a standalone file otherwise.

This feature is being developed in the https://github.com/boa-dev/boa/tree/feature/completion_records branch.

**Comment by Razican** [comment]
Should it be part of the AST? I would say this is only related to execution, since it's the completion of a execution, right?

**Comment by jedel1043** [comment]
> Should it be part of the AST? I would say this is only related to execution, since it's the completion of a execution, right?

Hmm... Yeah, you're right, it should be on the `exec` module.

**Comment by jedel1043** [comment]
Closing in favour of the current implementation. We can revisit this if we reassess that a more spec-compliant design is required.
