### ISSUE TITLE
Remove `InterpreterState` from `Context`

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#1545]
Related discussion on #1541.

Follows from #1544.

After returning every corresponding `CompletionRecord` in the spec, we can remove `InterpreterState`; at this point `CompletionRecord` should manage the execution state of its `Node`, so an additional `InterpreterState` should be unnecessary.

This feature is being developed in the https://github.com/boa-dev/boa/tree/feature/completion_records branch.

**Comment by Razican** [comment]
This needs to be reviewed for the VM branch

**Comment by jedel1043** [comment]
Closing since the VM now manages this using the `FinallyReturn` type
