### ISSUE TITLE
Implement `[[Call]]` and `[[Construct]]` as Object Internal Methods

### ISSUE THREAD

**Issue by raskad** [boa-dev/boa#1579]
The spec defines `[[Call]]` and `[[Construct]]` to be Object Internal Methods. Exotic objects like the `Proxy` object depend on this functionality. We currently only `call` on explicit function objects, but it should be the other way around: everything that has a `[[Call]]` internal method is a function object (there is no `isFunction` operation in the spec, only a `IsCallable`).
This change should affect all places where  `[[Call]]` or `[[Construct]]` are mentioned in the spec.

https://tc39.es/ecma262/#sec-object-internal-methods-and-internal-slots
https://tc39.es/ecma262/#table-additional-essential-internal-methods-of-function-objects
https://tc39.es/ecma262/#sec-iscallable
https://tc39.es/ecma262/#sec-isconstructor

**Comment by jedel1043** [comment]
@raskad Are you planning to implement this? If not, I can take it :)

**Comment by raskad** [comment]
Take it :) I just stumbled upon it during my work in the Proxy object.
