### ISSUE TITLE
Some benchmarks need rebasing (tidy up)

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#1591]
Taking a look at https://boa-dev.github.io/boa/dev/bench/ some benchmarks are no longer useful. Mainly because we've changed how we count or the improvements have been so vast that the order of magnitude no longer works.

Should we just remove older data? It might be the easiest option
We could take a snapshot of how it is today then store it somewhere

For example:
* Create realm
* Symbols (Execution)
* For loop (Execution)
* The one underneath for loop has no title and I don't know what its measuring
* Long file (Parser)

Benchmark data is collected here:
https://github.com/boa-dev/boa/blob/gh-pages/dev/bench/data.js

The job to add new benchmarks is here:
https://github.com/boa-dev/boa/blob/master/.github/workflows/master.yml#L8-L54

The action is from:
https://github.com/jasonwilliams/github-action-benchmark

**Comment by Razican** [comment]
This has already been done.
