### ISSUE TITLE
Implement Array.prototype.at()

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#1596]
**ECMASCript feature**
https://tc39.es/ecma262/#sec-array.prototype.at

**Example code**
This is the same feature added for String.prototype.at() - https://github.com/boa-dev/boa/pull/1375

This code should now work and give the expected result:
```javascript
const arr1 = [1,5,6,2];
arr1.at(-1) // 2
```
The expected output is `2`.

**Comment by nekevss** [comment]
Hi! I'd definitely be interested in trying to implement this. I'm sort of new to helping with an open source project, should I just make a pull request for array/mod.rs?

**Comment by jedel1043** [comment]
@nekevss I've assigned the issue to you.

> should I just make a pull request for array/mod.rs?

Yep, pretty much.
You need to fork this repo, then branch, code the changes, commit and create a new PR against this repo. Here's an useful guide if you still have some questions about the process :)
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by jedel1043** [comment]
@nekevss Also, if you have any questions about the codebase or if you need some mentoring, ping us and we'll try to help you asap 😊

**Comment by nekevss** [comment]
Hi! I submitted a pull request for the implementation. Hopefully, I didn't do anything wrong or overlook anything.

I could probably use some mentoring in general as I'm mostly self-taught. Although, this issue seemed to be easy enough (knock on wood).

Definitely planning to try and contribute more to boa as it seems like a great way to learn JS/TS at a greater depth WHILE playing around with Rust.
