### ISSUE TITLE
Fix remaining `Math` tests

### ISSUE THREAD

**Issue by raskad** [boa-dev/boa#1599]
We currently have some 262 tests failing for the `Math` suite. This is the full list of tests that should be fixed for 100% `Math` compliance:

- [ ] [test/built-ins/Math/imul/length](https://github.com/tc39/test262/blob/16dae73171ba048d91a62d0942b450d253db4c10/test/built-ins/Math/imul/length.js)
- [ ] [test/built-ins/Math/min/zeros](https://github.com/tc39/test262/blob/16dae73171ba048d91a62d0942b450d253db4c10/test/built-ins/Math/min/zeros.js)
- [ ] [test/built-ins/Math/round/S15.8.2.15_A6](https://github.com/tc39/test262/blob/16dae73171ba048d91a62d0942b450d253db4c10/test/built-ins/Math/round/S15.8.2.15_A6.js)
- [ ] [test/built-ins/Math/round/S15.8.2.15_A7.js](https://github.com/tc39/test262/blob/16dae73171ba048d91a62d0942b450d253db4c10/test/built-ins/Math/round/S15.8.2.15_A7.js)
- [ ] [test/built-ins/Math/pow/applying-the-exp-operator_A7.js](https://github.com/tc39/test262/blob/16dae73171ba048d91a62d0942b450d253db4c10/test/built-ins/Math/pow/applying-the-exp-operator_A7.js)
- [ ] [test/built-ins/Math/pow/applying-the-exp-operator_A8.js](https://github.com/tc39/test262/blob/16dae73171ba048d91a62d0942b450d253db4c10/test/built-ins/Math/pow/applying-the-exp-operator_A8.js)
- [ ] [test/built-ins/Math/max/zeros.js](https://github.com/tc39/test262/blob/16dae73171ba048d91a62d0942b450d253db4c10/test/built-ins/Math/max/zeros.js)

**Comment by bhh32** [comment]
I'd like to work on this issue.

**Comment by jedel1043** [comment]
@bhh32 I've asigned it to you. Let us know if you need any help or if you have any questions about the codebase! ☺

**Comment by bhh32** [comment]
Thank you! I cloned the repo, and don’t quite understand where the changes
need to be made. Maybe I could get an explanation of the code base and
where to start? Thank you for your help.
Very Respectfully,
  Bryan Hyland

**Comment by raskad** [comment]
Sure!

The best place to start for this would be the file https://github.com/boa-dev/boa/blob/master/boa/src/builtins/math/mod.rs.
As you can see we have the `Math` struct that corresponds to the `Math` object in javascript. In the [`impl Math` block](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/math/mod.rs#L95) you can find all of the methods that are implemented for the `Math` object. Every method should already have links in the documentation comment to the corresponding spec reference.

For example the [`max`](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/math/mod.rs#L609) function has a link to it's spec over [here](https://tc39.es/ecma262/#sec-math.max). In most functions you can also find the corresponding spec documentation as comments in the function body.

The failing tests mentioned in this issue probably appear, because there are some slight differences between the spec and the actual implementation. If the difference is not obvious at first, the tests themselves also have some helpful documentation on what is being tested.

For testing if your changes work, you can just `cargo run` the project and manually do the test step by step (for single tests, you can also run the whole 262 suite described [here](https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md#testing)).

Hope that helps :)

**Comment by bhh32** [comment]
That absolutely does!! Thank you! I’ll get to work on this ASAP!
