### ISSUE TITLE
Allow `BindingPattern` as `CatchParameter`

### ISSUE THREAD

**Issue by raskad** [boa-dev/boa#1600]
**ECMASCript feature**
Currently we only allow `BindingIdentifier`s in the `CatchParameter` of the `try...catch` statement.  `BindingPattern`s should be also allowed.

[ECMAScript specification][spec]

[spec]: https://tc39.es/ecma262/#prod-CatchParameter

**Example code**
This code should work and give the expected result:
```javascript
try {
  throw { a: 1, b: 2 }
} catch ({ a, b }) {
  console.log(a, b)
}
// prints `1 2`
```

Good starting points would be the `catch` parsing in https://github.com/boa-dev/boa/blob/master/boa/src/syntax/parser/statement/try_stm/catch.rs and the `BindingPattern` parsing in https://github.com/boa-dev/boa/blob/master/boa/src/syntax/parser/statement/mod.rs

**Comment by am-a-man** [comment]
hey,
I'd like to work on this, please assign this to me.

**Comment by lowr** [comment]
Hi, I saw comments at #1601, and looks like this issue hasn't been taken yet. I'd like to give it a shot!

**Comment by jedel1043** [comment]
@lowr Please do! I've assigned it to you, let us know if you have any questions or if you need any pointers to get started 😊
