### ISSUE TITLE
Fix `Number.toExponential` and `Number.toFixed`

### ISSUE THREAD

**Issue by raskad** [boa-dev/boa#1602]
The functions `toExponential` and `toFixed` of the `Number` prototype are currently not implemented spec compliant. All of the tests for those two functions should pass if they do not rely on other features that are not implemented.

To see the exact failed tests, take a look at the current results at https://boa-dev.github.io/boa/test262/

Spec references:
- https://tc39.es/ecma262/#sec-number.prototype.toexponential
- https://tc39.es/ecma262/#sec-number.prototype.tofixed

**Comment by nrabulinski** [comment]
Hi, I'd like to work on this issue! I've gotten all but `exactness.js` from toFixed to pass, but it seems like calling `as_number` on `1000000000000000128` actually returns `1000000000000000000.0`, is this a known issue? The `toString` part of that test is also failing because of that.

**Comment by jedel1043** [comment]
> Hi, I'd like to work on this issue! I've gotten all but `exactness.js` from toFixed to pass, but it seems like calling `as_number` on `1000000000000000128` actually returns `1000000000000000000.0`, is this a known issue? The `toString` part of that test is also failing because of that.

I think that's because Javascript only supports i32 integers, so any number that exceeds `u32::MAX` is automatically converted to an `f64`. The fix probably would be to check if a `JsValue::Rational` number is an integer when printing.

**Comment by nrabulinski** [comment]
> > Hi, I'd like to work on this issue! I've gotten all but `exactness.js` from toFixed to pass, but it seems like calling `as_number` on `1000000000000000128` actually returns `1000000000000000000.0`, is this a known issue? The `toString` part of that test is also failing because of that.
> 
> 
> 
> I think that's because Javascript only supports i32 integers, so any number that exceeds `i32::MAX` is automatically converted to an `f64`. However, `1000000000000000128` is not representable with an f64, so it should return `1000000000000000100` instead.

Yes, it should and that's how `toString` is defined (it should round to 1000000000000000100). I'll investigate further later :)
