### ISSUE TITLE
Implement increment/decrement in VM

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#1611]
Location of unimplemented feature:
https://github.com/boa-dev/boa/blob/master/boa/src/bytecompiler.rs#L369-L372

This would involve creating 2 new opcodes (Inc and Dec) [here](https://github.com/boa-dev/boa/blob/master/boa/src/vm/opcode.rs#L6-L534) see https://searchfox.org/mozilla-central/source/js/src/vm/Opcodes.h#649-650 for reference.

Once added the VM would need to act on it. You can copy over some of the [unary actions](https://github.com/boa-dev/boa/blob/master/boa/src/syntax/ast/node/operator/unary_op/mod.rs#L53-L127) and convert them into VM instructions like [EQ](https://github.com/boa-dev/boa/blob/master/boa/src/vm/mod.rs#L188-L193) for example

code to test:
```js
const a =  1;
a++
```

If using VSCode (Launch VM) or run with `---features vm` flag

**Comment by abhishekc-sharma** [comment]
Can I have a go at this issue ?

**Comment by jedel1043** [comment]
@abhishekc-sharma Of course :)
I've assigned the issue to you, please ping us if you need mentoring or if you want some pointers on how to start 😊
