### ISSUE TITLE
Symbol.prototype.valueOf.call(x) gives different results than x.valueOf()

### ISSUE THREAD

**Issue by hle0** [boa-dev/boa#1617]
**Describe the bug**

`Symbol` gives different results depending on how `valueOf` is called, which causes various tests to fail, like [this one](https://github.com/tc39/test262/blob/10ad4c159328d12ad8d12b95a8f8aefa0e4fd49b/test/built-ins/Symbol/prototype/valueOf/this-val-symbol.js) for example.

Here's an example session from boa-cli:
```
>> a = Symbol('s')
Symbol(s)
>> Symbol.prototype.valueOf.call(a) == a.valueOf()
false
>> Symbol.prototype.valueOf.call(a) == a
false
>> a.valueOf() == a
false
>>
```

**To Reproduce**
See above. `boa-cli` was run with `cd boa_cli; cargo run`.

**Expected behavior**

The `valueOf` a `Symbol` should always `==` the Symbol, no matter how `valueOf` is called. Here's an example from Node.js:

```
> a = Symbol('s')
Symbol(s)
> a.valueOf() == a
true
```

This behavior should be made the same in Boa.

**Build environment (please complete the following information):**

- OS: Artix Linux
- Kernel Version: 5.13.12-artix1-1
- Target triple: e.g. x86_64-unknown-linux-gnu
- Rustc version: rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Additional context**

**Comment by jedel1043** [comment]
@hle0 Thank you for taking this!

`JsSymbol` resides on https://github.com/boa-dev/boa/blob/master/boa/src/symbol.rs, and its built-in representation on https://github.com/boa-dev/boa/blob/master/boa/src/builtins/symbol/mod.rs so these should be good starting points.

You can comment here or ping us on discord if you have any questions ☺️
