### ISSUE TITLE
Implement `SharedArrayBuffer` built-in object

### ISSUE THREAD

**Issue by raskad** [boa-dev/boa#1642]
Additional to the implementation of the `SharedArrayBuffer` built-in object, the corresponding uses in `TypedArray` should be implemented.

**ECMASCript feature**
The `SharedArrayBuffer` object is used to represent a generic, fixed-length raw binary data buffer, similar to the `ArrayBuffer` object, but in a way that they can be used to create views on shared memory. Unlike an `ArrayBuffer`, a `SharedArrayBuffer` cannot become detached.

[ECMAScript specification](https://tc39.es/ecma262/#sec-sharedarraybuffer-objects)
[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer)

**Comment by jedel1043** [comment]
Uh so I reevaluated this and it should be fine to treat `Context` as our agent. Anyways, this is not blocked on that, but the implementation is a bit complex because of overlapping atomics of different sizes, so I'll unblock this but mark it as hard.

**Comment by raskad** [comment]
Implemented in #3384
