### ISSUE TITLE
Retrieve feature-based results for Test262 runs

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1645]
The current implementation of the Tes262 compliance results page shows the compliance test suite by test suite, which is straightforward, since we run the tests suite by suite, test by test, and then we just collect the information about it.

It would be very nice to have the option to also see it feature by feature. Some tests, such as [this one](https://github.com/tc39/test262/blob/12e9d67bb529474ad1ffddca92361512ab30c4c0/test/language/block-scope/syntax/redeclaration/async-function-name-redeclaration-attempt-with-const.js) have a list of features (only one in this case). This information is already being stored in the `MetaData` information structure [here](https://github.com/boa-dev/boa/blob/main/boa_tester/src/read.rs#L18).

In order to show these results, we first need to gather them. Currently, when we run a test suite, we get a `SuiteResult`, as you can see [here](https://github.com/boa-dev/boa/blob/main/boa_tester/src/exec/mod.rs#L16). These results are generated from the `TestResult` each test returns, as it can be seen [here](https://github.com/boa-dev/boa/blob/main/boa_tester/src/exec/mod.rs#L88). The definition of both structures can be seen in the `main.rs` file of the `boa_tester` project, [here](https://github.com/boa-dev/boa/blob/main/boa_tester/src/main.rs#L299-L329).

We should change the `SuiteResult` structure to include information on the features each test had. This would allow having feature coverage per test-suite. Since the top-most suite will include feature information for all the suites below it, we can store that information on a JSON file, as we do with the rest of the `SuiteResult`.

Note that we want to store this information in a separate JSON file, so we will need to ignore part of the `SuiteResult` structure when serializing it, and extract that information to a new structure that will be stored in a new JSON file. Similarly to what we do with the [`ReducedResultInfo` structure](https://github.com/boa-dev/boa/blob/main/boa_tester/src/results.rs#L24-L37). Note that there should be also results for "no features", for base language tests.

After this, we should be able to use that file in the results page.

**Comment by NorbertGarfield** [comment]
@Razican, I've got two questions:
1. Has anybody already taken this issue?
2. I could not figure out which output format is expected. Currently I stick to the following:
```
{
    "c" : "",
    "u" : "0bccacda693ada2cd1736d35eb912b27291ac6ff",
    "n" : "types",
    "f" : "Proxy, Symbol, cross-realm"
}
```

Where 'n' stands for 'name' and 'f' means 'features'. Do I need to add the information about passed tests or features here?

**Comment by Razican** [comment]
> @Razican, I've got two questions:
> 
> 1. Has anybody already taken this issue?

Nobody has taken this issue :) let me assign it to you

> 2. I could not figure out which output format is expected. Currently I stick to the following:
> 
> ```
> {
>     "c" : "",
>     "u" : "0bccacda693ada2cd1736d35eb912b27291ac6ff",
>     "n" : "types",
>     "f" : "Proxy, Symbol, cross-realm"
> }
> ```
> 
> Where 'n' stands for 'name' and 'f' means 'features'. Do I need to add the information about passed tests or features here?

This looks pretty good :) for simplicity, I would use an array for the features: `["Proxy", "Symbol", "cross-realm"]`. The rest looks good, I think it doesn't need any extra information, and you can use the current structure :)
