### ISSUE TITLE
Use in wasmtime or outside of browser

### ISSUE THREAD

**Issue by lastmjs** [boa-dev/boa#1670]
Hi, I'm trying to get boa to work on the Internet Computer (IC): https://smartcontracts.org/docs/introduction/welcome.html

The IC uses wasmtime, and whenever I try to deploy a local Wasm module to my local IC environment I get errors similar to the following:

```bash
Module imports function '__wbindgen_describe' from '__wbindgen_placeholder__' that is not exported by the runtime.
```

AFAIK, I cannot control the wasmtime host environment on the IC, as that would require larger changes to the IC itself. Is there some way to turn off the need for wasm-bindgen, or somehow get boa to work well in non-browser environments? It seems boa is assuming the end Wasm module will be running in a JavaScript environment, whereas in my case (and possibly others' in the future) we don't necessarily want to run our Rust code in the browser, even if the Rust code is compiled to Wasm.

**Comment by jasonwilliams** [comment]
Thanks for raising this @lastmjs, building for wasm outside the browser isn't something we've explored before so it makes sense for you to come across this. Im glad you have a workaround for now, i think we'll need to discuss how to maintain such an environment, as i think up until this point it isn't something any of us have tested. 

I've marked this as discussion for now. Could you tell us a little bit more about how you use the engine?

**Comment by lastmjs** [comment]
I can confirm this is working for me, appreciate it!
