### ISSUE TITLE
Fix remaining `DataView` tests

### ISSUE THREAD

**Issue by Nimpruda** [boa-dev/boa#1689]
These are the last failing tests for the `DataView` builtin:
- prototype/setInt16/set-values-return-undefined.js
- prototype/setInt8/set-values-return-undefined.js
- prototype/setUint8/set-values-return-undefined.js
- prototype/setUint16/set-values-return-undefined.js
- proto-from-ctor-realm.js

I couldn't manage to make them pass. Here are the failinf assertions for the set-values-return-undefined:
Int16 and Int8:
-1 0 value: -0.1
-2 -1 value: -1.1

Uint16:
`65535 0 value: -0.1
65534 65535 value: -1.1`

Uint8:
`255 0 value: -0.1
254 255 value: -1.1`

The following code is what I used to find the failing values:
```js
var buffer = new ArrayBuffer(8);
var sample = new DataView(buffer, 0);

var values = byteConversionValues.values;
var expectedValues = byteConversionValues.expected.Uint8;

values.forEach((value, i) => {
  var expected = expectedValues[i];

  var result = sample.setUint8(0, value);
  if (sample.getUint8(0) !== expected) {
    console.log(sample.getUint8(0), expected, "value: " + value);
  }
  if (result !== undefined) {
    console.log(result, undefined, "return is undefined, value: " + value);
  }
});
```

**Comment by jedel1043** [comment]
Fixed on main
