### ISSUE TITLE
Easy conversion from JsValue to serde_json::Value

### ISSUE THREAD

**Issue by lastmjs** [boa-dev/boa#1693]
In my quest to convert a `JsValue` into a Rust struct, a necessary intermediate step seems to be converting a `JsValue` into a `serde_json::Value`. This would make it very easy to then create a Rust struct. For example, this functionality might look like the following: `let my_struct: MyStruct = serde_json::from(jsValue.to_serde_json_value());`.

Without this, I either have to implement my own conversion from `JsValue` to `serde_json::Value`, or I have to `JSON.stringify` my JS value before returning it to the Rust environment, where I can then use `serde_json::from_str` to continue the conversion.

And I'm not sure this is the best way to do it, but somehow allowing `JsValue`'s to be easily converted into Rust structs is what I'm after.

**Comment by schrieveslaach** [comment]
I ran into the same issue when i tried to upgrade from 0.11.

**Comment by bartlomieju** [comment]
Just drive-by comment: in Deno we created something called `serde_v8` which is a bijection layer between `v8::Value` and `serde_json::Value`. This project proved to be hugely successful and efficient. For anyone interested I'm leaving a link to the source code (https://github.com/denoland/deno/tree/main/serde_v8) that you might find useful for inspiration for similar mechanism in `boa`.
