### ISSUE TITLE
There are no quotes around a String value

### ISSUE THREAD

**Issue by IovoslavIovchev** [boa-dev/boa#172]
Provided you have something like:
```rust
const o = { str: 'String' };

o;
```
the output would be:
```
"{ str: String }"
```

The issue is due to the [implementation](https://github.com/jasonwilliams/boa/blob/master/src/lib/js/value.rs#L579) of `Display` for `ValueData::String`, which simply displays the value of the `String`.

> Note that currently in `master` objects are displayed simpy as `{}` but you can see the issue in the branch for #171.

**Comment by jasonwilliams** [comment]
The change would be made here:
https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L728-L783

**Comment by RageKnify** [comment]
It would just be replacing the string used in https://github.com/jasonwilliams/boa/blob/f02babf0bd254b37920206b0ce0089bb9b01ba50/boa/src/builtins/value/mod.rs#L841
from `write!(f, "{}", v)` to `write!(f, "\"{}\"", v)`, right?

**Comment by jasonwilliams** [comment]
@RageKnify i think so yup

**Comment by RageKnify** [comment]
I'll open a PR soon.
