### ISSUE TITLE
Implement Array.from(arrayLike, mapFn)

### ISSUE THREAD

**Issue by pedropaulosuzuki** [boa-dev/boa#1784]
**ECMASCript feature**

Hello everyone! Hope y'all fine! 

I think it would be nice to see `Array.from(arrayLike, mapFn)` implemented in Boa. [ECMAScript specification here][spec]. Currently passing Array.from returns `undefined`, which means it is not defined yet. (Tested on Boa Playground).

[spec]: https://262.ecma-international.org/#sec-array.from

**Example code**

This code should work and give the expected result: (Used a Map as an example).
```js
const map = new Map();
map.set('a', 1);
map.set('b', 2);
const array = Array.from(map);
console.log(array);  // [ [ "a", 1 ], [ "b", 2 ] ]
```
The expected output is `[ [ "a", 1 ], [ "b", 2 ] ]`.

**Example code 2**

This code should work and give the expected result: (Used a string as an example).
```js
Array.from('Boa');  // [ "B", "o", "a" ]
```
The expected output is ` [ "B", "o", "a" ]`.

**Example code 3**

This code should work and give the expected result: (Using the mapping function as the second parameter).
```js
Array.from([1, 2, 3], x => x ** 2) // [ 1, 4, 9 ]
```
The expected output is ` [ 1, 4, 9 ]`.

Thanks!

**Comment by nrabulinski** [comment]
If there's nothing blocking this and no one is already at it, I'd like to give it a shot :)

**Comment by Razican** [comment]
@nrabulinski do you have any updates on this?
