### ISSUE TITLE
`"true"[3]` is `undefined`

### ISSUE THREAD

**Issue by icecream17** [boa-dev/boa#1788]
**Describe the bug**
String indexing doesn't work (gets `undefined`)

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.

```js
"true"[3]
```

```js
"another example"[0]
```

**Expected behavior**
Should get the character (er, code point) at that index

**Build environment (please complete the following information):**

<https://boa-dev.github.io/boa/>

**Comment by Razican** [comment]
This seems to be that this function is not fully spec compliant:
https://github.com/boa-dev/boa/blob/f66324cdf54357e92dfcd80f28419b365e410147/boa/src/object/internal_methods/string.rs#L144-L189

But I thought this should be working since #1354. @jedel1043 could you check this?

**Comment by jedel1043** [comment]
I'll give it a look

**Comment by jedel1043** [comment]
Ah, I think it's github pages, because locally it works correctly.
I checked the version published on the gh-pages branch and apparently it's the 0.10.0.
We would need to modify the action to recompile boa on each deploy.

**Comment by Razican** [comment]
> Ah, I think it's github pages, because locally it works correctly.
> 
> I checked the version published on the gh-pages branch and apparently it's the 0.10.0.
> 
> We would need to modify the action to recompile boa on each deploy.

In GitHub pages we have the 0.13 version, so I guess that's the reason. 0.14 should be released reasonably soon, and that will be implemented.

**Comment by jedel1043** [comment]
> In GitHub pages we have the 0.13 version, so I guess that's the reason. 0.14 should be released reasonably soon, and that will be implemented.

Hmm, that's weird. IIRC, #1354 was implemented before we released 0.13, so it should be on the release already...

**Comment by Razican** [comment]
Maybe it didn't do the release in GH pages

**Comment by Razican** [comment]
Indeed, the release workflow is failing, so the release in GitHub Pages is v0.10.0. I'm going to try and release v0.13, and see if there is something that can be fixed with the release workflow.
