### ISSUE TITLE
Async Arrow Function parsing

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1805]
**ECMASCript feature**
Implementing parsing for AsyncArrowFunctions is one of the missing parsing features to implement asynchronous execution. Documentation can be found here: https://tc39.es/ecma262/#sec-async-arrow-function-definitions

Async arrow functions are produced in assignment expressions: https://tc39.es/ecma262/#prod-AssignmentExpression
In Boa, this is defined in https://github.com/boa-dev/boa/blob/main/boa/src/syntax/parser/expression/assignment/mod.rs

You can follow any of the existing parsers to see how to do this:
 - https://github.com/boa-dev/boa/tree/main/boa/src/syntax/parser/expression/primary
 - https://github.com/boa-dev/boa/blob/main/boa/src/syntax/parser/expression/assignment/arrow_function.rs

**Comment by lastmjs** [comment]
I would like to start working on this issue

**Comment by raskad** [comment]
@lastmjs Are you still working on this? Otherwise I would take it over.

**Comment by lastmjs** [comment]
@raskad Please take it over, I haven't done anything yet
