### ISSUE TITLE
Async function expression execution

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1806]
**ECMASCript feature**
Boa is already capable of parsing async functions, but it's not able to execute them. The current implementation just returns an "undefined" value if one gets executed: 

https://github.com/boa-dev/boa/blob/672eede30d7bcc46a58ae08acdb864678a54d46b/boa/src/bytecompiler.rs#L879-L882

You can learn about runtime semantics here: https://tc39.es/ecma262/#sec-runtime-semantics-instantiateasyncfunctionobject

You will need to implement async function objects:
 - https://tc39.es/ecma262/#sec-async-function-objects

Note that the implementation of `await` is out of the scope of this issue.

**Comment by raskad** [comment]
Implemented in #2158
