### ISSUE TITLE
Divide the byte compiler

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1808]
Currently, the byte compiler is written in [a file](https://github.com/boa-dev/boa/blob/672eede30d7bcc46a58ae08acdb864678a54d46b/boa/src/bytecompiler.rs) with almost 2,000 lines. Each execution path should be divided in submodules, in order to reduce the size of the file and to make it more maintainable.

**Comment by justunkn** [comment]
@Razican can I take a deal with the issue?

**Comment by jasonwilliams** [comment]
@justunkn sure

**Comment by Razican** [comment]
@justunkn do you have any news on this?

**Comment by e-codes-stuff** [comment]
Does this issue still need to be worked on? It appears that #2343 fixes it, I would be willing to attempt some work on it otherwise though.

**Comment by jedel1043** [comment]
> Does this issue still need to be worked on? It appears that #2343 fixes it, I would be willing to attempt some work on it otherwise though.

It doesn't fix it though. The byte compiler and the VM are in separate modules

**Comment by e-codes-stuff** [comment]
Ah okay, in that case I'll see if I can do anything wrt fixing up the byte compiler organization. I'm assuming it makes the most sense to extract each of the longer match arm paths into separate files/functions?

**Comment by jedel1043** [comment]
Yep!

**Comment by e-codes-stuff** [comment]
Quick question: Within the bytecompiler module, theres some code that feels confusing to read because of the ambiguity about which `Literal` type the code is using at any given time, currently this is resolved by explicitly using the path to the `ast::expression::literal::Literal` type, would it make sense for me to use it as `AstLiteral` or something more easily understood as different from the `bytecompiler::Literal` type?

**Comment by jedel1043** [comment]
> Quick question: Within the bytecompiler module, theres some code that feels confusing to read because of the ambiguity about which `Literal` type the code is using at any given time, currently this is resolved by explicitly using the path to the `ast::expression::literal::Literal` type, would it make sense for me to use it as `AstLiteral` or something more easily understood as different from the `bytecompiler::Literal` type?

AstLiteral sounds good!

**Comment by Razican** [comment]
I think this happens in multiple places, where we have the parser and the AST node with the same time. Maybe we should have a review on all these names.
