### ISSUE TITLE
The RegExp structure has too many booleans

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1819]
As Clippy warns, the RegExp structure in [src/builtins/regexp/mod.rs](https://github.com/boa-dev/boa/blob/main/boa/src/builtins/regexp/mod.rs#L35-L61) has too many booleans (one for each flag). This is bad, because it might not get correctly optimised by the compiler. Ideally, we would want to use a bitflags structure such as the RegExpFlags one in https://github.com/boa-dev/boa/blob/60b7eb89340c266a2b4f180690e8781245b6a1c8/boa/src/syntax/lexer/regex.rs#L133-L144

For this particular case, I would recommend to just re-use that structure, and at some point, we want to create some kind of optimisation that doesn't just convert those flags to string to then run a RegExp constructor, which would again parse the flags and convert them to the RegExpFlags structure. For this we will almost certainly need a new AST node, but it's out of the scope of this issue.

**Comment by aaronmunsters** [comment]
I would like to work on this issue :)
