### ISSUE TITLE
Adjust `Realm` visibility

### ISSUE THREAD

**Issue by raskad** [boa-dev/boa#1835]
Currently `Realm` is a public struct and it's only public method is `crate()`. The only reason for this seems to be, so that we can benchmark the creation of a realm.

Either
1. `Realm` is fully private and we need to change how we benchmark it, or
2. we should provide some functionality for the public `Realm` e.g; changing the `Realm` of a `Context`. But is that api usefully in any way?

**Comment by wusyong** [comment]
For the entry point of DOM types, I think we also have to set a `Window` instance to be realm's global object.
https://html.spec.whatwg.org/multipage/window-object.html#script-settings-for-window-objects

**Comment by jedel1043** [comment]
Resolved by #2801
