### ISSUE TITLE
Boa wrongly assumes that allocating never fails and writes to a null pointer

### ISSUE THREAD

**Issue by y21** [boa-dev/boa#1847]
Boa assumes that `std::alloc::alloc` never fails (returning a null pointer) even though it can.

https://github.com/boa-dev/boa/blob/29cd909f88d9bcab59eedda95639756a45235d70/boa/src/string.rs#L219-L223

Quoting the [docs](https://doc.rust-lang.org/stable/core/alloc/trait.GlobalAlloc.html#tymethod.alloc):
> `unsafe fn alloc(&self, layout: Layout) -> *mut u8`
> Allocate memory as described by the given layout.
> Returns a pointer to newly-allocated memory, **or null to indicate allocation failure**.

If the allocation fails, then there will be a write on a null pointer on L223, which is considered [UB](https://doc.rust-lang.org/stable/std/ptr/index.html#safety):
> - A [null](https://doc.rust-lang.org/stable/std/ptr/fn.null.html) pointer is never valid, not even for accesses of [size zero](https://doc.rust-lang.org/stable/nomicon/exotic-sizes.html#zero-sized-types-zsts).

This also leads to violating the `NonNull::new_unchecked` invariant:
> `ptr` must be non-null.

https://github.com/boa-dev/boa/blob/29cd909f88d9bcab59eedda95639756a45235d70/boa/src/string.rs#L241

**To Reproduce**
```rs
use boa::JsString;

fn main() {
    // choose a string length that's large enough to cause an allocation error when concatenated later but
    // not too large so the initial allocation still succeeds
    let string = "a".repeat(1000 * 1000 * 1000);
    let ve = vec![&string as &str; 1000];

    // this is almost certainly going to cause an allocation error unless you've got lots of RAM
    // if it does, then this will write to a null pointer 💥
    let _ = JsString::concat_array(&ve);
}
```
Alternatively, one can override the global allocator and return null for that specific allocation: [link](https://gist.github.com/y21/64d8f2ebb9635b3e4fa95ca0a87bc497).
Implementing `GlobalAlloc` requires unsafe due to the nature of allocators being unsafe, but I'm fairly certain it's totally valid (albeit weird) for a crate to expose a safe API for an allocator like that.
Running the code under valgrind sums it up:
```sh
==22393== Process terminating with default action of signal 11 (SIGSEGV)
==22393==  Access not within mapped region at address 0x0
==22393==    at 0x110477: boa::string::JsString::concat_array
==22393==    by 0x11019F: boatest::main

[1]    22393 segmentation fault (core dumped)  valgrind ./target/release/boatest
```

**Expected behavior**
Handling null pointers, e.g. `assert!(!inner.is_null())`. Or better yet, calling [`std::alloc:handle_alloc_error`](https://doc.rust-lang.org/stable/alloc/alloc/fn.handle_alloc_error.html) as suggested in the docs

**Build environment**
- OS: Ubuntu
- Version: 20.04
- Target triple: x86_64-unknown-linux-gnu (installed)
- Rustc version: rustc 1.60.0-nightly (75d9a0ae2 2022-02-16)

**Comment by Razican** [comment]
Maybe this is addressed by #1659
