### ISSUE TITLE
Break in nested try/catch/finally cause multiple panics

### ISSUE THREAD

**Issue by addisoncrump** [boa-dev/boa#1900]
**Describe the bug**
Several panic variants caused by breaks in nested try/catch/finally. I have lumped them together as they appear to be caused by similar issues, but I have not yet identified a cause.

**To Reproduce**
This JavaScript crashes with `thread 'main' panicked at 'stack was empty', boa_engine/src/vm/mod.rs:145:36`
```javascript
while (true) {
    try {
        try {
            break;
        } catch (e) {
        } finally {
        }
    } finally {
    }
}
```

This JavaScript crashes with `thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 25344', boa_engine/src/vm/mod.rs:396:39`
```javascript
while (true) {
    try {
        try {
            throw "h";
        } catch (e) {
            break;
        } finally {
        }
    } finally {
    }
}
```

This JavaScript crashes with `thread 'main' panicked at 'attempt to subtract with overflow', boa_engine/src/vm/call_frame.rs:64:9`
```javascript
while (true) {
    try {
        try {
        } catch (e) {
        } finally {
            break;
        }
    } finally {
    }
}
```

**Expected behavior**
None of these should panic.

**Comment by tsutton** [comment]
Additional information: it appears that with nested `try ... finally` blocks, the outer `finally` is skipped if there's a break or return:

```javascript
 function f(){
    try {
        try {
	    return;
        } finally {
	console.log("inner")
        }
    } finally {
	console.log("outer")
    }
}

f();
```

Under `node`, this prints `"inner"` and `"outer"`. Under `boa` (via `cargo run`), this just prints `inner`.

**Comment by VTCAKAVSMoACE** [comment]
Error messages have changed but behaviour persists.

**Comment by jedel1043** [comment]
Closing since this is now fixed.
