### ISSUE TITLE
Move syntax errors from the compiler to the parser

### ISSUE THREAD

**Issue by raskad** [boa-dev/boa#1907]
Currently we have some syntax errors that are being thrown in the compiler. They should be already be thrown in the parser.

The best case to search for them is to look for `throw_syntax_error` and `construct_syntax_error` in `boa_engine/src/bytecompiler.rs`. There may be state that must be added during the parsing for all of the errors to be moved to the parsing phase.

After this is fixed, `Context::compile` should not need to return a `Result` anymore.

**Comment by Razican** [comment]
After #2027, what's missing here?

**Comment by raskad** [comment]
There are still some syntax errors in the bytecompiler left:

* Check for undeclared labels at parse time to avoid [this](https://github.com/boa-dev/boa/blob/f0378068a0a2add5b7110addc875aa266f28cc38/boa_engine/src/bytecompiler.rs#L1609)
* Check if `continue` statements occur within a loop to avoid [this](https://github.com/boa-dev/boa/blob/f0378068a0a2add5b7110addc875aa266f28cc38/boa_engine/src/bytecompiler.rs#L1627)
* Check if `break` statements occur within loop or switch to avoid [this](https://github.com/boa-dev/boa/blob/f0378068a0a2add5b7110addc875aa266f28cc38/boa_engine/src/bytecompiler.rs#L1677)
* Check for invalid left-had-side in assignments (all others)
