### ISSUE TITLE
The cli parameter `--dump-ast Json` panics

### ISSUE THREAD

**Issue by raskad** [boa-dev/boa#1920]
**Describe the bug**
Whey trying to output the AST with the cli parameter `--dump-ast Json` or `--dump-ast JsonPretty` boa panics.

**To Reproduce**

This JavaScript code reproduces the issue:
run the following code with `cargo run -- --dump-ast Json`
```javascript
let a = 1
```

`thread 'main' panicked at 'could not convert AST to a pretty JSON string: Error("can only flatten structs and maps (got a sequence)", line: 0, column: 0)', boa_cli/src/main.rs:181:30`

**Expected behavior**
Print the AST in JSON format.

**Comment by hemantku** [comment]
Hi, My name is Vineet. I would work on this issue if this is still available

**Comment by raskad** [comment]
Hi @hemantku, thank you for your interest in contributing to boa!
(Un)fortunately this will already be fixed in #1959

I noticed, that we don't have many good first issues currently. If you do not find one that looks interesting to you, I recommend heading to our [conformance page](https://boa-dev.github.io/boa/test262/) and checking out some currently failing tests, for which we do not have an issue open. That may be a good starting point if you want to help us improve our test coverage :)
