### ISSUE TITLE
Panic when invoking functions which use themselves as default parameter values

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [boa-dev/boa#1922]
**Describe the bug**
Invoking a function which uses itself as a default parameter value puts the VM's stack in an invalid state. This could be used to create invalid or unexpected execution states.

**To Reproduce**

This JavaScript code reproduces the issue:
```javascript
(function F(x = F) {})();
```
(Induces `thread 'main' panicked at 'assertion failed: self.stack.len() > 1', boa_engine/src/environments/runtime.rs:120:9`)

**Expected behavior**
The stack should not be put into an invalid state.

**Additional context**
Discovered by #1902.

**Comment by HalidOdat** [comment]
> `(function F(x = F) {})();`

The code example works and returns undefined as expected. So closing this :)
