### ISSUE TITLE
Unidentified panic in vm/mod.rs

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [boa-dev/boa#1926]
**Describe the bug**
I tried for some time to identify the cause of this panic, but I'm just not finding it so I'm putting it here for other eyes. I've minified the example the best I could.

**To Reproduce**
This JavaScript code reproduces the issue:
```javascript
[(function(...{}) { await 1; })()][0];
```

This causes the following panic:
```
thread 'main' panicked at 'should be an object', boa_engine/src/vm/mod.rs:198:43
```

**Expected behavior**
No panic should occur; program should execute successfully.

**Additional information**
Discovered by #1902.

**Comment by dranikpg** [comment]
It's because of pushing an redundant PushUndefined opcode [in the bytecompiler](https://github.com/boa-dev/boa/blob/e2630faf82a27e958d0ca6c9b1c81554bcc07ff3/boa_engine/src/bytecompiler.rs#L1032).

This should resolve automatically once async/await is supported properly

**Comment by VTCAKAVSMoACE** [comment]
This no longer crashes. Huzzah!
