### ISSUE TITLE
Panic when errors are thrown while assigning function parameters to default values

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [boa-dev/boa#1930]
**Describe the bug**
A panic in runtime.rs is induced when processing an error induced during function parameter assignments to default values. The error does not have to be thrown during the assignment of a default value.

**To Reproduce**
Any of the following javascript lines can induce the crash.
```javascript
(function({}, x = "") {})(); // destructures undefined
(function(x = "", {}) {})(); // destructures undefined
(function(x = []()){})(); // [] is not a function
(function(x = new []()){})(); // [] is not a constructor
```

**Expected behavior**
The program should not panic and should instead throw the appropriate error.

**Additional context**
Discovered by #1902. May be related to #1922.

**Comment by HalidOdat** [comment]
> ```js
> (function({}, x = "") {})(); // destructures undefined
> (function(x = "", {}) {})(); // destructures undefined
> (function(x = []()){})(); // [] is not a function
> (function(x = new []()){})(); // [] is not a constructor
> ```

The above mentioned code seems to be fixed and throws the correct errors. So closing this, If there are any panic related to this please comment and we will open this issue again :)
