### ISSUE TITLE
Migrate release workflow to Cargo Workspaces

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#1956]
We had a lot of trouble with releasing v0.14. We should probably move to [cargo-workspaces](https://crates.io/crates/cargo-workspaces) similar to rust analyzer. Here is an example from them.

This should help release the crates in the correct order.

https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/publish.yml#L17-L45

**Comment by Razican** [comment]
Most of the work is done. The only thing left is to avoid publishing `boa_cli`, `boa_tester`, `boa_wasm` and `boa_examples`. At the same time, we should check that none of the crates has more than 5 keywords (`boa_cli` has 6, for example), since this was making the workflow fail.

**Comment by raskad** [comment]
@jedel1043 with the latest path releases everything worked, right? I think we can close this now.

**Comment by jedel1043** [comment]
Yep, we can close :)
