### ISSUE TITLE
invalid type: floating point after math operations

### ISSUE THREAD

**Issue by lastmjs** [boa-dev/boa#1962]
**Describe the bug**

I have been using the new JsValue `to_json` functionality and I'm running into some issues. I am dealing with numbers in JS that should be valid integers, whether they be u32, i32, etc. boa seems to have issues with `to_json` because it is converting them into `Rational`s for an unknown reason. This might be related to https://github.com/boa-dev/boa/issues/1961.

**To Reproduce**

```rust
fn main() {
    println!("get_u32: {}", get_u32());
}

fn get_u32() -> u32 {
    let mut context = boa_engine::Context::default();

    let return_value = context.eval(r#"
        1000000 - 500
    "#).unwrap();

    serde_json::from_value(return_value.to_json(& mut context).unwrap()).unwrap()
}
```

**Expected behavior**

This should print `get_u32: 999500` and should not error out. Instead I get this error:

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: floating point `999500`, expected u32", line: 0, column: 0)', src/main.rs:12:74
```

**Build environment (please complete the following information):**

- OS: Ubuntu 20.04
- Version: latest main
- Target triple: wasm32-unknown-unknown or x86_64-unknown-linux-gnu
- Rustc version: rustc 1.58.1 (db9d1b20b 2022-01-20)

**Additional context**

It seems like certain math operations are causing a Rust representation of `Rational` unnecessarily.

**Comment by jedel1043** [comment]
This is pretty unrelated to #1961 :)
We currently convert to f64 when any operation between i32 is executed, but we should be checking whether the result is representable by a i32, or else, convert both operands to f64 and execute the operation. I'll work on this while we discuss #1961

**Comment by RageKnify** [comment]
I sort of mentioned this before in #1147

**Comment by Razican** [comment]
> I am dealing with numbers in JS that should be valid integers, whether they be u32, i32, etc. boa seems to have issues with `to_json` because it is converting them into `Rational`s for an unknown reason.

Just to explain this. The reason is that there is no such thing as an "integer" type in JavaScript. All numeric types are 64-bit floating point numbers. So this should never work like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#number_type
