### ISSUE TITLE
Implement `i128` to `JsValue` conversions

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1970]
We can currently convert most of Rust's basic types to `JsValue`, but since the `i128` type was a late addition to Rust, we don't offer that conversion. You can implement it by checking how this is done for `i64`:
https://github.com/boa-dev/boa/blob/e2630faf82a27e958d0ca6c9b1c81554bcc07ff3/boa_engine/src/value/mod.rs#L1003-L1008

**Comment by Shreyan11** [comment]
Just to be clear, you want to convert all i28 types to JsValue?

**Comment by sudosmile** [comment]
I'd like to work on this issue

**Comment by jonah-saltzman** [comment]
Could I work on this issue? It seems to have not been solved on main or the latest commit.

**Comment by lastmjs** [comment]
I believe there's an open pull request for this: https://github.com/boa-dev/boa/pull/1971

**Comment by Razican** [comment]
This will be handled in #2276.
