### ISSUE TITLE
Add full support for SHA-2 in recipes

### ISSUE THREAD

**Issue by woodgiraffe** [boa-dev/boa#2063]
**Add full support for SHA-2**
recipe.yaml/`.source` currently allows these properties along a `.source.url`:

```
                   'md5': {'maxLength': 32,
                           'minLength': 32,
                           'pattern': '^[0-9a-fA-F]{32}$',
                           'title': 'Md5',
                           'type': 'string'},
                   'patches': {'items': {'type': 'string'},
                               'title': 'Patches',
                               'type': 'array'},
                   'sha1': {'maxLength': 40,
                            'minLength': 40,
                            'pattern': '^[0-9a-fA-F]{40}$',
                            'title': 'Sha1',
                            'type': 'string'},
                   'sha256': {'maxLength': 64,
                              'minLength': 64,
                              'pattern': '^[0-9a-fA-F]{64}$',
                              'title': 'Sha256',
                              'type': 'string'},
```

Sha256 is already supported, however other SHA-2 hash functions are not supported,  
yet some projects provide (sometimes exclusively) at least sha512 sums.

I'd propose to support the remaining SHA-2 hash functions ( sha224sums, sha384sums, sha512sums ), or at the very least sha512.

Thanks for your consideration and your efforts!

**Comment by raskad** [comment]
Hi @woodgiraffe, I think you are searching for a different project named `boa`. My guess is this here: https://github.com/mamba-org/boa

**Comment by jedel1043** [comment]
Closing since this issue is not about this repo.
