### ISSUE TITLE
Separate `JsObjectType` implementors to their own module 

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#2080]
Our safe wrappers around Javascript objects are not easily identifiable by looking at the docs, as you can see from the next screenshot:

![image](https://user-images.githubusercontent.com/38230983/169442395-16c444ab-f53e-465a-8072-647180ccdf55.png)

I would propose moving all implementors of the `JsObjectType` trait to a standalone module and point to that module in the home page of our documentation.

**Comment by jonah-saltzman** [comment]
I was interested in trying this issue out but it looks like it's already been done? Although I may be missing something because I only see 4 impls of `JsObjectType` in the whole repo

**Comment by jedel1043** [comment]
@jonah-saltzman Not really. If you check the doc website, all the implementors are listed along `JsObject`, `Object`, `ConstructorBuilder`, etc.

https://boa-dev.github.io/boa/doc/boa_engine/object/index.html

Ideally, the implementors should be on their own module, and the module should document that these are wrappers for Javascript built-in objects.

**Comment by CalliEve** [comment]
Hi! I am interested in this issue and would like to work on it, if that's alright?

**Comment by jedel1043** [comment]
@CalliEve Please do! I'll assign you the issue, let us know if you have any questions or if you need some guidance ☺️
