### ISSUE TITLE
Implement Spread operator for Objects

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#214]
The rest operator has been implemented to arrays. `[a,b,...c]`
But it is not implemented for objects.

## test case

```js
const b = {
  a: 1,
  b: 2,
  c: 3
};

const a = {
  a: "a",
  b: "b",
  ...b
};

console.log(a);

```
The array implementation exists here inside of exec.rs:
https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L218-L223

Tests for this exist here too:
https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L850-L862

https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L202-L213 will need to do something similar.

There will need to be changes to the parser so spread can be parsed within an object. The above code will currently error in the parser as spread syntax isn't expecting within an object.
Parsing objects happens here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/parser.rs#L522-L574

**Comment by gomesalexandre** [comment]
Will take a look at this one soon

**Comment by FrancisMurillo** [comment]
Can I take this?
