### ISSUE TITLE
labeled block support

### ISSUE THREAD

**Issue by SheetJSDev** [boa-dev/boa#2243]
The following example is from MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label#using_a_labeled_block_with_break

> You can use labels within simple blocks, but only break statements can make use of non-loop labels.

```js
foo: {
  console.log('face');
  break foo;
  console.log('this will not be executed');
}
console.log('swap');

// this will log:

// "face"
// "swap"
```

Saving that to a file and testing with `cargo run -- test.js` prints the error

```
Uncaught "SyntaxError": "Cannot use the undeclared label 'foo'"
```

**Comment by meirochun** [comment]
Looks like this bug already in execution since Feb 23. #1852

**Comment by Razican** [comment]
This might be related to the fact that we don't use completion records. We only check for labels on loops, afaik, instead of on "any labeled statement", which should be the case. But we also don't have the notion of a "labeled statement" I think.
