### ISSUE TITLE
String indexOf is extremely slow

### ISSUE THREAD

**Issue by t2k269** [boa-dev/boa#2316]
The execution performance of indexOf method of String is extremely slow for long string (23000+ characters), the calls used around 10 seconds to complete. I tried to implement a rust method to override it. It used just 0.01s. please help to improve.

Thanks

**Comment by Razican** [comment]
Hello @t2k269, thank you for reporting this. Do you have an example string we can use to test this? Also, could you share the rust method you implemented to make this go faster?

**Comment by Razican** [comment]
Thanks for the example!

I have to say that the playground will always be slower than the chrome console, since the playground is a VM in Webassembly running JS.

We will check if it's possible to optimize that function. Note that the function you propose is probably not 100% spec compliant, and sometimes, doing it spec compliant makes it slower. We will check it, though, to see if it could be optimized.

**Comment by t2k269** [comment]
Hello Razican,

Thanks for your explanation. I understand that BOA must follow the JS spec. However, I notice that the indexOf slow problem appear only when I force to build my project with tag "v0.16". Previously, my project build with BOA dependency on "main" branch. On main branch, the indexOf is fast and I didn't notice any performance issue.

The reason of why I suddenly build my project with tag "v0.16" is that I saw the news from BOA that supported "async/await" officially in v0.16. The hash in main branch that I used to build my project previously is 9dda8d3eaef4a2d8e90a9ceb4857a3c7f2de084a

Hope these information can help to feature out the issue.

Thanks!

**Comment by jedel1043** [comment]
Thankfully, this is fixed by #1659. Running the original snippet on https://github.com/boa-dev/boa/pull/1659/commits/11e5bdec3fc262862767269d4f6f36905be3a81f returns:
```
"Result: 10000, Used 0.002s"
```

**Comment by t2k269** [comment]
I tried to run the slow script with following 3 BOA versions
- rev = 9dda8d3eaef4a2d8e90a9ceb4857a3c7f2de084a
- tag = v0.16
- branch = main
- rev = 0e6bb74d641a5c3282b1181cc7fd6f7f3796a32a (latest v0.17)

The execution time is 0.003s, 2.6s, 0.002s and 3.4s respectively.

Therefore, the problem appear on v0.16 and the current v0.17. Thanks!

**Comment by Razican** [comment]
Hi @t2k269 yes, that PR has not been merged yet. You can test it in the `utf16-str` branch.

**Comment by t2k269** [comment]
Oh! Great. The execution time is 0.001s on utf16-str branch, extremely fast now, thanks.
