### ISSUE TITLE
Boa REPL behavior differs from Node REPL with ObjectLiteral

### ISSUE THREAD

**Issue by bcr** [boa-dev/boa#2318]
**Describe the bug**
If you enter a valid `ObjectLiteral` in the Boa REPL, the behavior (generates syntax error) is different than the Node REPL (generates object)

**To Reproduce**

```
➜  boa git:(ffi) ✗ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/boa`
>> {}
undefined
>> {a:7}
7
>> {a:7, b:8}
Uncaught: "SyntaxError": "expected token ';', got ':' in expression statement at line 1, col 8"
```

**Expected behavior**
```
➜  boa git:(ffi) ✗ node
Welcome to Node.js v17.6.0.
Type ".help" for more information.
> {}
{}
> {a:7}
{ a: 7 }
> {a:7, b:8}
{ a: 7, b: 8 }
```

**Build environment (please complete the following information):**

- OS: macOS
- Version: 12.6
- Target triple: arm64-apple-darwin21.6.0
- Rustc version: rustc 1.64.0 (a55dd71d5 2022-09-19)

**Additional context**

My guess is that the initial state of the REPL is to expect `Statement` (first squiggle bracket matching `Block` and eventually getting sad.) So this may not be a bug (I did not enter a statement.) But the user expectation might be that it more closely matches other JavaScript REPL practice.

**Comment by jedel1043** [comment]
Interestingly, the Firefox REPL and the Chromium REPL differ on their treatment of that expression:

![image](https://user-images.githubusercontent.com/38230983/193400682-ee506b1e-d5d4-40ba-b797-8c42f600f4e4.png)

![image](https://user-images.githubusercontent.com/38230983/193400700-d654c09a-ed0c-40ed-b317-7a51fe07c954.png)

**Comment by Razican** [comment]
This is indeed a syntax error, and not valid JavaScript, so getting a `SyntaxError` is to be expected. Nevertheless, having the REPL show information about expressions too, could be useful for development, but it can be tricky to implement (might need changes in the parser).

**Comment by bcr** [comment]
I presume if Node and Chromium are using the same engine they have the same behavior. SpiderMonkey and Boa are more principled. I kinda like the V8 behavior, but it's not a big deal, certainly not enough to spend a lot of cycles on. I'll close this.
