### ISSUE TITLE
String regex match is slow

### ISSUE THREAD

**Issue by t2k269** [boa-dev/boa#2321]
I use BOA to parse a HTML. I try to use regex match, but it is slow. Here is an example:

```
    const a = "0123456789"
    let s = ""
    for (let i = 0; i < 200; i++) {
      s += a;
    }
    s = s + "<form ajah>" + s + "</form>" + s
    const start = new Date().getTime()
    let r = s.match(/<form.*<\/form>/)
    log = `Result: ${r.length}, Used ${(new Date().getTime() - start) / 1000}s`
```

in my windows PC, it used around 10s to finish.

Thanks

**Comment by ItsEthra** [comment]
Only happens in debug build though

**Comment by Razican** [comment]
@t2k269 did you build your project in `--release` mode?

**Comment by Razican** [comment]
I'm closing this, since it seems it only happens in debug mode, and that is expected, and there was no further response.
