### ISSUE TITLE
Asynchronous Rust Native Functions

### ISSUE THREAD

**Issue by lastmjs** [boa-dev/boa#2345]
The 0.16 release of Boa now enables Promises and async/await in JavaScript, which is absolutely fantastic. But what about asynchronous native functions in Rust? The project I am working on, [Azle](https://github.com/demergent-labs/azle), is a JS environment for a decentralized cloud that runs in a wasm32-unknown-unknown environment. We need to expose async Rust functions to JS, but because we only have the synchronous NativeFunction interface, we are forced to use generators to emulate asynchronous behavior. This works well, but we really want to give users the beauty of async/await.

So, are there plans for asynchronous Rust native functions? I'm imagining `NativeFunctionAsync` which would have nearly the same signature as `NativeFunction`, but would return a future.

**Comment by jedel1043** [comment]
Oops, didn't close the issue when we merged #2542.
