### ISSUE TITLE
Static blocks and properties cannot reference class by identifier

### ISSUE THREAD

**Issue by dapper-gh** [boa-dev/boa#2399]
**Describe the bug**
In a static block or property within a class definition, the class cannot be referenced by its variable name.

**To Reproduce**
The following code results in: `ReferenceError: A is not initialized`.
```javascript
let A = class {
    static {
        let _dummyVariable = A;
    }
};
```
The following code has the same effect:
```javascript
class A {
    static _dummyProperty = A;
};
```

**Expected behavior**
The identifier `A` in the above code should refer to the constructor of the class. The code should not throw an error. Note that the [ECMAScript specification: Section 15.7.14 Step 3.a](https://tc39.es/ecma262/#sec-runtime-semantics-classdefinitionevaluation) states that an immutable binding should be created in the context of a class definition.

**Build environment (please complete the following information):**

- OS: Arch Linux
- Version: rolling release
- Target triple: `x86_64-unknown-linux-gnu`
- Rustc version: `rustc 1.64.0 (a55dd71d5 2022-09-19)`

**Comment by jedel1043** [comment]
Fixed now!
