### ISSUE TITLE
Default cases on switch statements not cascading to below cases

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#2405]
**Describe the bug**
This is mainly a bug divided in possibly two separate, unintended behaviours:
- `default` is assumed to always be the last case of a switch (which is not true), and automatically breaks out of the case statement. The correct behaviour should be to cascade to subsequent cases.
- Cases that come after the `default` case are not tested for.

**To Reproduce**
```Javascript
let foo = 1;
switch (foo) {
  case 2:
    console.log(2);
    break;
  default:
    console.log('default');
  case 1:
    console.log(1);
}
```

**Expected behaviour**
When foo is 1, it should only print `1`. When foo is neither 1 nor 2, it should print `default` and then `1`.

**Current behaviour**
When foo is not 2, it always prints `default`, even if foo is 1.

**Comment by karol-janik** [comment]
Hello!

I would love to try to solve this problem!

**Comment by jedel1043** [comment]
@karol-janik Thank you very much! Let me give you some pointers on what it needs to be done.

The AST corresponding to a switch statement lives here:

https://github.com/boa-dev/boa/blob/c4eabd20c7bbbaed81a94b49b8d25cac69df6b5f/boa_ast/src/statement/switch.rs#L89-L93

Right now, the structure assumes the `default` variant is the last `Case` of every `Switch`, which is not true. This should be changed to also store the position of `default` in the list of `Case`'; this can be accomplished either by removing default and adding a `is_default: bool` in `Case` or by somehow storing the relative position of the `default` with respect to the `cases` array. Both options are good, but the latter option would be better to ensure there are no duplicate default `Case`s in the `case` array. Just an observation though, it could be that there are better solutions I'm not seeing right now.

Next, I'm seeing no problems on the parser side:

https://github.com/boa-dev/boa/blob/c4eabd20c7bbbaed81a94b49b8d25cac69df6b5f/boa_parser/src/parser/statement/switch/mod.rs#L75-L79

Apparently the parser already tries to parse all `Case`s even if it already parsed the default case, so it will need just small adjustments on the construction of the AST node.

Finally, the VM byte compiler:

https://github.com/boa-dev/boa/blob/c4eabd20c7bbbaed81a94b49b8d25cac69df6b5f/boa_engine/src/bytecompiler/statement/mod.rs#L152-L198

This needs to be rewritten in order to make the default case cascade to lower cases. I think this is the most difficult part of this problem, since you'll need to preserve the branch order of the switch case while testing for values after the default case.

Let me know if you have some questions about the codebase! 😁

**Comment by HalidOdat** [comment]
#2907 Seems to have fixed this
