### ISSUE TITLE
Test262 action gives warnings in GitHub actions

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#2415]
We are getting these warnings that we should fix in PR Test262 checks. They might become hard errors in the future:
![image](https://user-images.githubusercontent.com/597469/200281684-04960c33-6281-445d-8736-95e6d7817b80.png)

**Comment by karol-janik** [comment]
Hi! 

I've created a [PR](https://github.com/boa-dev/boa/pull/2500) for (I hope) fixing this issue! :)
