### ISSUE TITLE
Panic when using unary operations on `this`

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [boa-dev/boa#2416]
**Describe the bug**
Using a unary operator on `this` causes boa to panic.

**To Reproduce**
Execute the following script:

```js
++this;
```

Which causes the following error:

```
thread 'main' panicked at 'not yet implemented: access_set `this`', boa_engine/src/bytecompiler/mod.rs:828:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
Boa should issue a syntax error with an invalid operand.

**Additional context**
Discovered by #2401

**Comment by e-codes-stuff** [comment]
This is only disallowed for specifically the unary operations which would assign to `this` right? I think it would be possible to add in the error by turning this code in `bytecompiler/expression/unary.rs` from this:
```rust
            UnaryOp::DecrementPost => {
                // TODO: promote to an early error.
                let access = Access::from_expression(unary.target()).ok_or_else(|| {
                    JsNativeError::syntax().with_message("Invalid decrement operand")
                })?;
```
To something like this:
```rust
            UnaryOp::DecrementPost => {
                // TODO: promote to an early error.
                let access = Access::from_expression(unary.target())
                    .filter(|a| a != Access::This)
                    .ok_or_else(|| {
                        JsNativeError::syntax().with_message("Invalid decrement operand")
                    })?;
```

For anyone more knowledgeable, does this seem to be correct?

**Comment by jedel1043** [comment]
It is correct, but I would very much prefer if we moved the error to the parser.

**Comment by veera-sivarajan** [comment]
Hi, can I work on this issue?

**Comment by jedel1043** [comment]
@veera-sivarajan Seems like @e-codes-stuff was checking out the issue, so maybe they have some WIP fix?

**Comment by e-codes-stuff** [comment]
No WIP fix here aside from the code I posted above which just adds a method
call to something that should be moved into the parser

**Comment by VTCAKAVSMoACE** [comment]
With this fixed, there are no currently bugs found by the fuzzer with implied oracles. Huzzah!
