### ISSUE TITLE
"not a callable function" is thrown in playgroud while works fine in browser

### ISSUE THREAD

**Issue by piaoger** [boa-dev/boa#2428]
**Describe the bug**

Below code is carefully dropped   from minified code with minor adjustment for better readability.
While running the code, type error "not a callable function" is thrown but works fine in browser. If change  "GP(true)" to "GP(false)", it works fine too.

```javascript
 function A(x) {
     var d = P();
     return d + x;
 }

 function P() {
     return "P";
 }

 function GP(cond) {
     var x = 0, n = "S";

     if (cond) {
         for (x = 1, P = x + 1; x < 5; x++) {
             n += A(x);
         }
     } else {
         for (x = 1; x < 5; x++) {
             var P = 3;
             n += A(P);
         }
     }

     return n;
 }

// works!!
// playgroud:  > "SP3P3P3P3"
// browser:  SP3P3P3P3
// GP(false);

// wrong!!
// playground:  Uncaught "TypeError": "not a callable function"
// browser: SP1P2P3P4
GP(true);
```

**To Reproduce**

Just run the code in playground, you will find the type error.
  
**Expected behavior**

Alight with other environment, such as browser.
 
- Environment:  Boa Playground

**Comment by jedel1043** [comment]
The playground tracks the newest released version (0.16), so a lot of fixes won't show until we release 0.17. Closing this by that reason.
