### ISSUE TITLE
Various problems around async/await/setTimeout

### ISSUE THREAD

**Issue by mlafeldt** [boa-dev/boa#2471]
Hey, while exploring Boa as an alternative to Deno, I noticed a couple of problems:

**Describe the bugs**

1. Async arrow functions are not being parsed correctly,
  see https://github.com/mlafeldt/boa-playground/blob/main/broken/asyncArrow.js
1. `setTimeout` seems to do nothing
  see https://github.com/mlafeldt/boa-playground/blob/main/broken/setTimeout.js
1. `await new Promise` seems to do nothing inside a function
  see https://github.com/mlafeldt/boa-playground/blob/main/broken/topLevelAwait.js
1. top-level await can crash
  see https://github.com/mlafeldt/boa-playground/blob/main/broken/topLevelAwait.js

Happy to create individual issues if warranted. :)

**To Reproduce**

The linked repo contains everything required to reproduce the results.

**Build environment (please complete the following information):**

- OS: macOS Monterey
- Target triple: aarch64-apple-darwin
- Rustc version: rustc 1.65.0 (897e37553 2022-11-02)

**Comment by jedel1043** [comment]
Thank you for the extensive test cases! I have some comments about this bug report; more specifically, about case 2 and case 4:

- 2: Boa is NOT a runtime, and is NOT a replacement for Deno. In fact, we have an issue talking about exposing an API for Deno to use. `SetTimeout` is usually implemented by the runtime (Node/Deno), not by the engine (Boa), because it's very entangled with how the event loop works internally.

- 4: The spec specifically denies top-level awaits outside of module scripts. If this bug is fixed, it'll change to throw an error, not to execute that code. We're currently implementing module parsing and execution, which will eventually support top-level await.

**Comment by raskad** [comment]
Regarding case 1; async arrow functions should be working on the current `main` branch. You are probably using `0.16` right?

**Comment by mlafeldt** [comment]
> Regarding case 1; async arrow functions should be working on the current `main` branch. You are probably using `0.16` right?

Yes, I am. https://github.com/mlafeldt/boa-playground/blob/dc6033d0f55fc99b7fcc7dc1f7315d37aa63c32a/Cargo.toml#L7

**Comment by mlafeldt** [comment]
> * 2: Boa is NOT a runtime, and is NOT a replacement for Deno. In fact, we have an issue talking about exposing an API for Deno to use. `SetTimeout` is usually implemented by the runtime (Node/Deno), not by the engine (Boa/V8), because it's very entangled with how the event loop works internally.

Well, that *is* interesting. So it's not possible to use `setTimeout` right now? What other parts won't work (or execute fine but won't do anything) right now due to missing runtime features?

> * 4: The spec specifically denies top-level awaits outside of module scripts. If this bug is fixed, it'll change to throw an error, not to execute that code. We're currently implementing module parsing and execution, which will eventually support top-level await.

Yeah, that's right. I mainly reported it because [in some cases it appears to be working](https://github.com/mlafeldt/boa-playground/blob/dc6033d0f55fc99b7fcc7dc1f7315d37aa63c32a/broken/topLevelAwait.js#L22-L23) - assuming that's non-standard behavior itself?

**Comment by raskad** [comment]
> Well, that _is_ interesting. So it's not possible to use `setTimeout` right now? What other parts won't work (or execute fine but won't do anything) right now due to missing runtime features?

Boa implements the [`ECMAScript` specification](https://tc39.es/ecma262/). The `setTimeout` function is not part of `ECMAScript` but is defined in the [whatwg HTML Standard](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-settimeout-dev). A good place to check where a specific functionality is specified is on the relevant MDN pages. Most MDN pages have a `Specifications` section that points to the specifications.

Boa does not implement anything that is not part of the `ECMAScript` specification. For example `setTimeout` just throws a reference error:

```js
setTimeout();
// Uncaught: ReferenceError: setTimeout is not defined
```

**Comment by mlafeldt** [comment]
> Boa does not implement anything that is not part of the `ECMAScript` specification. For example `setTimeout` just throws a reference error:

I see. I actually never saw that `ReferenceError` during testing because these promises aren't being resolved: https://github.com/mlafeldt/boa-playground/blob/main/broken/setTimeout.js

**Comment by mlafeldt** [comment]
> 3\. `await new Promise` seems to do nothing inside a function
>     see https://github.com/mlafeldt/boa-playground/blob/main/broken/topLevelAwait.js

This is also a no-op without any error:

```js
async function go() {
   return await xxx
}
go()
```

**Comment by lastmjs** [comment]
Are there plans to eventually implement setTimeout or things outside of the ECMAScript specification? We need this kind of functionality for our project, we aren't running in Node, Deno, or the browser, but a Wasm decentralized computing environment.

We would very much like to allow things like setTimeout without too much hassle on our part so that we can support as much JS code and as many JS libraries as possible.

**Comment by lastmjs** [comment]
Maybe I just don't understand what's currently possible with the async/await and Promises implementation currently. Does Boa have any kind of event loop that we can put tasks onto?

**Comment by postmeback** [comment]
After reading through all the comments, I understood that there is an issue with arrow functions, if that is true, I would like to brainstorm here.

~New to rust~Will take some time~

**Comment by mlafeldt** [comment]
I'm going to close this. As of Boa v0.17, everything except for `setTimeout` works. 👍

I know that `setTimeout` is a Web API just like `console.log`. While it would be nice for Boa to include it out of the box, it's definitely not a bug.
