### ISSUE TITLE
Date() is needed https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#252]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by adumbidiot** [comment]
Maybe we could use [chrono](https://docs.rs/chrono/0.4.10/chrono/)?

**Comment by jcdickinson** [comment]
I'm rolling off my "learn Rust" project after learning the important 40%. Is anyone else working on this?

**Comment by jasonwilliams** [comment]
@jcdickinson i don't think so!

**Comment by Lan2u** [comment]
@jcdickinson did you make any progress on this?

**Comment by jcdickinson** [comment]
Slow progress, I have most of the ctor stuff done. It's a pretty hairy spec.

**Comment by Lan2u** [comment]
> Slow progress, I have most of the ctor stuff done. It's a pretty hairy spec.

Shall I add you as assigned to this issue then? 😃

**Comment by jcdickinson** [comment]
@Lan2u sure, I can do a WIP PR for now.
