### ISSUE TITLE
"Invalid regular expression literal: Invalid character escape"

### ISSUE THREAD

**Issue by SheetJSDev** [boa-dev/boa#2601]
**Describe the bug**

See title

**To Reproduce**

```javascript
var re = /sheet\,js/;
```

Test with

```bash
cargo run -- test.js
```

**Expected behavior**

No error.

**Build environment (please complete the following information):**

- OS: macOS
- Version: 12.6.3
- Target triple: `x86_64-apple-darwin`
- Rustc version: `rustc 1.66.1 (90743e729 2023-01-10)`

**Additional context**

This is a valid regular expression according to 12.9.5 "Regular Expression Literals" and 22.2.1 "Patterns".

**Comment by SheetJSDev** [comment]
A few more examples:

```js
var re2 = /sheet\-js/;
var re3 = /sheet[\=]js/;
```

**Comment by shqld** [comment]
https://tc39.es/ecma262/#prod-AtomEscape

**Comment by SheetJSDev** [comment]
Based on the EBNF, the last example parses as

```
CharacterClass [\=]
  literal [
  ClassRanges \=
    NonemptyClassRanges \=
      ClassAtom \=
        ClassAtomNoDash \=
          literal \
          ClassEscape =
            "SourceCharacter but not one of \ or ] or -" =
              literal =
  literal ]
```

**Comment by jedel1043** [comment]
Fixed in the main branch.
