### ISSUE TITLE
cargo test fails for code in docs

### ISSUE THREAD

**Issue by tunz** [boa-dev/boa#2605]
The following 4 tests are failing in my machine:
```
failures:
    src/class.rs - class (line 4)
    src/context/hooks.rs - context::hooks::HostHooks (line 20)
    src/context/mod.rs - context::Context<'_>::eval_module (line 179)
    src/object/mod.rs - object::ObjectInitializer (line 2039)
```

It seems like they are all code in docs. Is CI missing these tests?

**Build environment (please complete the following information):**

- OS: MacOS 13.1
- Version: main
- Target triple: arm64
- Rustc version: 1.67.1

**Comment by jedel1043** [comment]
Yeah, apparently `nextest` doesn't support doc tests at the moment. Opened #2606.
