### ISSUE TITLE
Wrong result from `Number.prototype.toFixed`

### ISSUE THREAD

**Issue by magic-akari** [boa-dev/boa#2609]
**Describe the bug**
Wrong result from `Number.prototype.toFixed`

**To Reproduce**

```javascript
const a = 1.25.toFixed(1);
console.log(a);
```

**Expected behavior**

Running this code, `a` should be set to `"1.3"` and printed, but `a` is instead set to `"1.2"`. The expected behaviour can be found in the [ECMAScript specification][spec].

[spec]: https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-number.prototype.tofixed

**Build environment (please complete the following information):**

- OS: macOS arm64
- Version: latest
- Target triple: aarch64-apple-darwin
- Rustc version: rustc 1.67.0 (fc594f156 2023-01-24)

**Additional context**

**Comment by vncsalencar** [comment]
As per my understanding this is because of https://github.com/boa-dev/boa/blob/4750e8d53aa1f7dddff157fd3f2eae8c8d27e762/boa_engine/src/builtins/number/mod.rs#L281
Which, as https://github.com/rust-lang/rust/pull/102935 shows, Rust's `format!` rounds `x.5` to whichever even number is closest.
So `1.25.toFixed(1)` rounds down to `1.2` but `1.35.toFixed(1)` rounds up to `1.4`.

![Screenshot 2023-02-22 at 11 01 19](https://user-images.githubusercontent.com/42007303/220642421-185a5195-de55-40f1-bacb-0510578e1fc0.png)

**Comment by magic-akari** [comment]
Is there any progress here?

>Regarding the one failing test; I think we should merge this without that one.
>
>But we may have an easier solution that to fix the issues in `std`. We already use [`ryu-js`](https://crates.io/crates/ryu-js) crate that converts numbers to strings. Conveniently the repository for the crate is in the boa-dev org: https://github.com/boa-dev/ryu-js ;)
>
>Without looking further into it, my idea would be to implement the functionality of `num_to_exponential` and `num_to_exponential_with_precision` there. @HalidOdat I think you probably know the most about this, do you think we should try to do that, or is `ryu-js` not the right place?

_Originally posted by @raskad in https://github.com/boa-dev/boa/issues/1620#issuecomment-933025305_
            
I have found a recommended fix mentioned in this issue, and I believe it should be implemented in ryu-js.
Is there any plans to implement `to_precision` and `to_fixed` in ryu-js?

**Comment by HalidOdat** [comment]
> I have found a recommended fix mentioned in this issue, and I believe it should be implemented in ryu-js.

I think putting it in the `ryu-js` crate is a good place. (maybe feature gated) :)

> Is there any plans to implement `to_precision` and `to_fixed` in ryu-js?

I don't think there has been any work done on this, I created Issues to track the progress (https://github.com/boa-dev/ryu-js/issues/33, https://github.com/boa-dev/ryu-js/issues/32, https://github.com/boa-dev/ryu-js/issues/31)

**Comment by HalidOdat** [comment]
I have started work on `Number.prototype.toFixed()` implementation in the ryu algorithm in `ryu-js` locally, Hopefully will create a PR on `ryu-js` repo when It passes all the tests, then create a PR for `boa_engine` with the changes here :)
