### ISSUE TITLE
Collect ES5 conformance information

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#2629]
It would be good to show our current spec conformance for ES5 exclusively, since many transpilers assume all engines support at least ES5.

# Preliminar research

We currently parse a struct that stores the full metadata of every test being run:

https://github.com/boa-dev/boa/blob/c15bf73b65a7d666e9e01be16cca9a82b45a8746/boa_tester/src/read.rs#L20-L37

Could be good to check if we can use the `es[56]?id` fields to determine if a test covers the ES5 spec or not.

We could also check how other engines that exclusively target ES5 run the test suite.

**Comment by ZackMitkin** [comment]
Can I get assigned? :)

**Comment by jedel1043** [comment]
@ZackMitkin I think we forgot to update this issue. We asked the Test262 folks about how to proceed on this and one of them said
> ... I don't think there's a particular branch or tag that corresponds to a particular ES edition - you might be able to find a point in time where all features in that edition were covered, but there would still be other tests present for things that were only stage 3 at the time.
off the top of my head, your best avenue might be to keep a list of feature flags to include and exclude for a particular edition.
`es5id` is deprecated, it's a section number in the ES5 document (which doesn't tell you much useful information these days).
The esid is the name of the HTML anchor corresponding to the section in the living spec document/

So I think this task will be a bit more convoluted than expected. 

However, I saw that you had a [branch](https://github.com/ZackMitkin/boa/commit/345535074bc9ff25566634d56af33ca26a8a082f) where you used the `es5/6id` flags for this, and I think we can merge that as a first step then expand it with some additional logic to consider tests that don't contain a `es5id` flag on them, so feel free to open a PR and I'll review it ASAP :)
