### ISSUE TITLE
Support destructuring assignment

### ISSUE THREAD

**Issue by afinch7** [boa-dev/boa#265]
Support destructuring assignment syntax:
```
const object = {
  name: "text",
  size: 4,
};

const { name, size } = object;
```

**Comment by vapour101** [comment]
I'd like to work on this, if that's good?

**Comment by jasonwilliams** [comment]
Go for it @vapour101 !

**Comment by vapour101** [comment]
Sorry, seems like I had less time to devote to this than I realised. I'm not going to be able to complete this issue.

**Comment by SamuelQZQ** [comment]
@afinch7 Could I have a try?

**Comment by raskad** [comment]
@SamuelQZQ Are you still working on this? I just started some basic implementation and am currently at +128 tests passing. I think I could pick this up if you are not working on it.


@davimiku you referenced #1324, that seems to implement shorthand syntax for [Object Initializers](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-object-initializer) right? I think this issue would be also about [Destructuring Binding Patterns](https://tc39.es/ecma262/#sec-destructuring-binding-patterns). Just to make sure I'm not workin on something you already started.

**Comment by davimiku** [comment]
@raskad That's correct, #1324 only implements initializing objects with the short-hand notation (on the "right-hand side"), i.e.

```js
const message = "hello"
const obj = { message }
```

That PR didn't cover destructuring assignment (on the "left-hand side"), so great that you've started! I didn't start / wasn't planning on implementing destructuring assignment. 

Maybe if you don't hear from SamuelQZQ try asking a maintainer to change the assignment?

**Comment by SamuelQZQ** [comment]
@raskad Go ahead. I gave up. Haha.
