### ISSUE TITLE
Consistent website

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#2705]
Currently boajs.dev is a bit inconsistent. We have a "blog" page, that includes a top bar and our blog posts, and then we have a link to our "development" documentation, but not to the usage documentation (in docs.rs). The benchmarks, conformance and playground pages have no navigation bar, and the conformance and playground pages cannot switch between a light & dark theme as the rest of the pages can, with a switch.

We should make the website experience more consistent for our users, make sure it's easy to navigate, and see if we can integrate all pages under the same `npm build` command, since currently, some of the pages have their own CDN dependencies.

**Comment by jasonwilliams** [comment]
I think we could assign this to @ZackMitkin if he’s happy

**Comment by jedel1043** [comment]
Closing since the new website is done.
