### ISSUE TITLE
Display ES5 conformance information in our webpage

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#2710]
With #2690 merged, we have all we need to display our current ES5 conformance in https://boajs.dev/boa/test262. Ideally we'd have some kind of version selector at the top of the page to change between spec versions, but this is just a suggestion and the assignee could try to come up with their own UX for this feature.

**Comment by ZackMitkin** [comment]
Sure, this will take some time though as I'm busy with work, you can assign to me but anyone should also feel free to help out :)

I'll be investigating docusaurus this week and create a prototype with it for docs, blog and all other pages. Migration will be the hard part and most likely iterative over some time

**Comment by jedel1043** [comment]
Forgot to close this 😅
