### ISSUE TITLE
cannot access 'i' before initialization

### ISSUE THREAD

**Issue by lastmjs** [boa-dev/boa#2760]
**Describe the bug**

I am trying to use an npm package called [elliptic](https://www.npmjs.com/package/elliptic). This is a popular library, and with that knowledge it is a safe assumption that it works well in the common JS engines. I have tested it locally in Node.js and it works fine.

Unfortunately when trying to import the most basic functionality in Boa, this error is thrown:

```
cannot access 'i' before initialization
```

I have looked through the source code, and the variable referenced in the error is always declared with `var` and never `const` or `let`, so I don't think this error should be thrown.

**To Reproduce**

Just throw this code into a Boa script and execute it: https://github.com/indutny/elliptic/blob/master/dist/elliptic.min.js

The error will be thrown.

**Expected behavior**

This error should not be thrown, and the code should work just fine.

**Build environment (please complete the following information):**

I don't believe this information is relevant.

- OS: Ubuntu
- Version: 20.04
- Target triple: wasm32-unknown-unknown and probably all triples
- Rustc version: rustc 1.66.1 (90743e729 2023-01-10)

**Additional context**

I believe this issue has a high likelihood of being related: https://github.com/boa-dev/boa/issues/1393

**Comment by jedel1043** [comment]
Huh, I tried to reproduce it in the `main` branch but it successfully runs. Are you maybe running it in the 0.16v?

**Comment by lastmjs** [comment]
I've reproduced it with multiple versions, let me double check.

**Comment by lastmjs** [comment]
I can confirm that the issue presents on the latest commit hash on main.

Here's the commit hash: cf85843dc838c7c36e6b635b34f31d100e64c63b

Here's the `Cargo.toml` that I'm using:

```toml
[package]
name = "boa_uint8array"
version = "0.0.0"
edition = "2018"

[dependencies]
boa_engine = { git = "https://github.com/boa-dev/boa", rev = "cf85843dc838c7c36e6b635b34f31d100e64c63b" }
```

**Comment by lastmjs** [comment]
Did you ensure to paste this exact minified code in? https://github.com/indutny/elliptic/blob/master/dist/elliptic.min.js

**Comment by lastmjs** [comment]
Here's the Rust without that minified code pasted in without modification:

```rust
fn main() {
    let mut context = boa_engine::Context::default();

    let exports_js_value = context
        .eval_script(boa_engine::Source::from_bytes(r#""#))
        .unwrap();

    println!("{:#?}", exports_js_value);
}
```

**Comment by jedel1043** [comment]
Finally could reproduce the issue, I was accidentally running the unminified script instead of the minified one 😅

The upside is that elliptic.js does work without problems, it's just the minified version the one that is giving the engine some trouble. I'll put this in the pre-v1 tracker, and I'll probably debug it next week.

**Comment by lastmjs** [comment]
I think the issue still presents when you try to use the library using the non-minified version, unfortunately.
