### ISSUE TITLE
Keywords with Unicode escapes should throw syntax errors

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#2771]
**Describe the bug**
Currently, if we use a keyword with an Unicode escape, it will just work, and interpret it as the keyword itself. This is a follow-up from #1117.

**To Reproduce**
The following JavaScript code reproduces the issue:

```javascript
let x = f\u{61}lse;
```

**Expected behavior**
This should throw a syntax error. Instead, it just assigns the `false` boolean value to the `x` variable.

**Comment by veera-sivarajan** [comment]
Hi, I'd like to work on this.
