### ISSUE TITLE
regex: Dash character is always recognized as a range operator

### ISSUE THREAD

**Issue by vfosnar** [boa-dev/boa#2794]
**Describe the bug**
Dash (`-`) is recognized as a range operator even in situations where it shouldn't and it should be treated as a simple "match single character" rule.

**To Reproduce**
`/[a-\s]/g` should be treated as matching "a" or "-" or some whitespace ([regexr](https://regexr.com/7bo0j)). Instead the parser throws "Invalid regular expression literal"

**Comment by HalidOdat** [comment]
This is part of the `Annex-B` extension, #2864 should resolve this issue :)

**Comment by HalidOdat** [comment]
This was fixed in https://github.com/boa-dev/boa/pull/2888 , so closing this :)
