### ISSUE TITLE
var hoisting in functions is not working

### ISSUE THREAD

**Issue by vfosnar** [boa-dev/boa#2795]
**Describe the bug**
Javascript supports "var hoisting", this means that `var` declaration can be located anywhere in the function/global scope. As of now it looks like var hoisting is supported only in the global scope but not in function scope.

**To Reproduce**
```js
function a() {
    tmp = "hello";
    console.log(tmp);

    var tmp;
}
a();
```

**Expected behavior**
The code snippet should declare `tmp` **before any code is executed**, then set it's value to `"hello"` and log it to the console.

[var hoisting on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var#var_hoisting)

**Comment by Razican** [comment]
Un general we're not doing hoisting correctly. We re-order statements after parsing, instead of keeping track in the parser of the `var_declared_names`. We did this "trick" for the global scope, but not for the function scope. We should fix this for good in all scopes.

**Comment by vfosnar** [comment]
I might take a look at it, but I'm a beginner in Rust so no promises.

Taking a quick look at the source code, can't `BindingLocator` keep an information if it is a `var` and then before running opcode of the function initialize every `BindingLocator` that is a `var` to `undefined`?

**Comment by vfosnar** [comment]
or in some other way keep track of what bindings are declared using `var`

**Comment by jedel1043** [comment]
> Taking a quick look at the source code, can't `BindingLocator` keep an information if it is a `var` and then before running opcode of the function initialize every `BindingLocator` that is a `var` to `undefined`?

I'm pretty sure the compiler has enough information to initialize all `var` bindings to `undefined`:

https://github.com/boa-dev/boa/blob/928d67b28e12072fc450fda8c64fcceec1e60f1e/boa_engine/src/environments/compile.rs#L92

The `create_mutable_binding` function already receives a `function_scope` parameter, which is the same as saying "this binding is a `var`", so maybe we could initialize to `undefined` from here?

**Comment by jasonwilliams** [comment]
@vfosnar did you want to be assigned this one?

**Comment by vfosnar** [comment]
probably not as I don't have much time, but if I fix it I'll make a PR
