### ISSUE TITLE
boa_engine builtin::date unit tests fail for DST timezones

### ISSUE THREAD

**Issue by MisterEggnog** [boa-dev/boa#2874]
**Describe the bug**
Running the unit tests fails for 2 tests, regarding builtin::date, apparently due to issues with floating point equality.
Test fails with variations on the form of
```
thread 'builtins::date::tests::date_proto_set_month' panicked at 'assertion failed: `(left == right)`
  left: `Rational(1607444175779.0)`,
 right: `Rational(1607447775779.0)`:
```
these should likely be found equal.

**To Reproduce**
```bash
cargo test -p boa_engine --lib -- builtins::date::tests::date_proto_set_full_year builtins::date::tests::date_proto_set_month
```

**Expected behavior**
The equality of floating points should be checked within the epsilon.

**Build environment (please complete the following information):**

- OS: Ubuntu 20.04.6 LTS, Windows 10
- Version: [e.g. 32]
- Target triple: x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc
- Rustc version: rustc 1.69.0 (84c898d65 2023-04-16)

**Additional context**
This likely just needs to checked that the difference between the two numbers is less that epsilon.

**Comment by jedel1043** [comment]
Uh the differences between numbers are fairly big to be an equality issue.
Just to confirm a theory I have about this, do you live in a timezone with variable UTC offset e.g. daylight time?

**Comment by Razican** [comment]
It happens to me too on MacOS, in DST too

**Comment by MisterEggnog** [comment]
By difference between the numbers I mean the equation for checking that the difference between the numbers is within the error range of the floating point. iirc the equation $|a - b| \leq \epsilon$ where $\epsilon$ is [f64::EPSILON]. This is just a guess, just due to the fact that the (truncated) numbers it prints out is that they are the same.

I do live in an area with DST.

[f64::EPSILON]: https://doc.rust-lang.org/std/primitive.f64.html#associatedconstant.EPSILON

**Comment by jedel1043** [comment]
Yeah, I think our recent `HostHooks` change broke for DST timezones, since only returning the `FixedOffset` of a timezone doesn't consider that some timezones are dynamic with respect of the date.

**Comment by MisterEggnog** [comment]
Looking over it again I realize that the numbers are not close to each other. So likely it is related to DST timezones.
