### ISSUE TITLE
ES5 selector in conformance website not working correctly

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#2886]
Some ES6 stuff appears when selecting ES5 in the conformance website, like for-of, computed property names, etc. which have the `es6id` field.

As described by @Razican, the issue is in the way we filter test:

> I think the issue is mostly here: https://github.com/boa-dev/boa/blob/main/boa_tester/src/edition.rs#L342-L357, where we first check async and module flags, then the list of features. But if there is no feature and no flag, it defaults to ES5. Which should only be the case if es5id is found, ideally (or if no es6id, esid is found)

**Comment by veera-sivarajan** [comment]
Hi, can I take a shot at it?

**Comment by HalidOdat** [comment]
Sure, go ahead! :)
