### ISSUE TITLE
Add WebAssembly support

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#289]
WASM is now in everywhere, and a JavaScript engine should include support for it, I think. We could take [this][article] for ideas.

[article]: https://medium.com/@richardanaya/lets-write-a-web-assembly-interpreter-part-1-287298201d75

**Comment by jasonwilliams** [comment]
@Razican what needs to change here that we're not doing already?

**Comment by Razican** [comment]
We don't have any support for executing we assembly binaries inside of Boa. It would be nice to be able to run Boa in Boa, for example.
