### ISSUE TITLE
Discord Invite Expired

### ISSUE THREAD

**Issue by sno2** [boa-dev/boa#3050]
Hello, the Discord invite links in the GitHub issue templates directory and the README are expired.

**Comment by jedel1043** [comment]
Uh I tested the link and everything looks good... Can you confirm that the link you see is https://discord.com/invite/tUFFk9Y ?

**Comment by sno2** [comment]
Hmm, interesting. When I copy and paste the link into my browser it works, but when I click on the direct GitHub links it does not. For example:

![image](https://github.com/boa-dev/boa/assets/43641633/1c9800b6-04eb-44f3-9cb3-1b5a5390a0df)

Thanks for sending the link again.
