### ISSUE TITLE
Consider removing tc39/test262 submodule and download lazily

### ISSUE THREAD

**Issue by mattsse** [boa-dev/boa#3095]
Due to how cargo handles submodules (or rather doesn't): https://github.com/rust-lang/cargo/issues/4247

a fresh cargo build with boa as git dependency `boa { git = "..."}` will download all submodules and it takes some time to download https://github.com/tc39/test262

Perhaps it's possible to download the repo lazily instead, for example:

https://github.com/dtolnay/syn/pull/183

**Comment by gakonst** [comment]
hi @HalidOdat - just flagging again...also I think doing a release would also fix this?

**Comment by HalidOdat** [comment]
> I think doing a release would also fix this?

This would be a temporary fix though, I'll create a PR with a proper fix :)
