### ISSUE TITLE
Implement `findLast` & `findLastIndex` on TypedArray's

### ISSUE THREAD

**Issue by dirkdev98** [boa-dev/boa#3100]
**ECMASCript feature**

Implement missing [`%TypedArray%.prototype.findLast ( predicate [ , thisArg ] )`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.findlast) and [`Array.prototype.findLastIndex ( predicate [ , thisArg ] )`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.findlastindex) features.

Implementing these should fix most of the remaining test262 tests with feature `array-find-from-last`.

**Example code**

```js
// From test/built-ins/TypedArray/prototype/findLastIndex/return-index-predicate-result-is-true.js

var sample = new Int32Array([39, 3, 9]);
var called = 0;

var result = sample.findLastIndex(function() {
  called++;
  return true;
});

assert.sameValue(result, 2, "returned true on sample[2]");
assert.sameValue(called, 1, "predicate was called once");
```

**Comment by dirkdev98** [comment]
I want to implement this!

At some point the spec changed to use [`FindViaPredicate ( O, len, direction, predicate, thisArg )`](https://tc39.es/ecma262/#sec-findviapredicate) for `Array.prototype.find`, `Array.prototype.findLast`, `%TypedArray%.prototype.findLast`, et al. Do we want to refactor the existing implementations to use this? 

If so, where would be a good place to add this? Under `built-ins/array/mod.rs` as a `pub(crate) fn find_with_predicate`? I don't have any experience with Rust modules yet, so a bit unsure what the way to go would be.

**Comment by HalidOdat** [comment]
> At some point the spec changed to use [`FindViaPredicate ( O, len, direction, predicate, thisArg )`](https://tc39.es/ecma262/#sec-findviapredicate) for `Array.prototype.find`, `Array.prototype.findLast`, `%TypedArray%.prototype.findLast`, et al. Do we want to refactor the existing implementations to use this?

Yes, that would be optimal, This could be done In a separate PR.

> If so, where would be a good place to add this? Under built-ins/array/mod.rs as a pub(crate) fn find_via_predicate? I don't have any experience with Rust modules yet, so a bit unsure what the way to go would be.

Yes, that's a good place :) , I usually put the helper fuctions based where it is defined in the spec then by frequency of use, since they are both used equally. array module is best.

**Comment by dirkdev98** [comment]
Alright, will do the refactor first and implement the new functions afterwards. Thanks!
