### ISSUE TITLE
As a beginner, which file or module should I start with?

### ISSUE THREAD

**Issue by xusanduo08** [boa-dev/boa#3138]
Hi
I am a frontender, use react to build web pages  and also  a beignner of rust.
I learned this project from InfoQ websit, and I know that boa can run javascript.
As a beginner, Which part or module or file should I start with? Or any concepts should I familier with?

Thanks.

**Comment by nekevss** [comment]
Hi @xusanduo08!😄  We have some issues that are currently marked as `E-Easy`. You can start out with those if you want some more entry level issues. The documentation for the current main branch can be found [here](https://boajs.dev/boa/doc/boa_engine/index.html)

If you're looking to just get a grasp of the repository itself. There are a few general places that may be of interest. There's Boa's Parser/Lexer in the `boa_parser` crate and the ECMAScript parse nodes in the `boa_ast` crate. If you want to see Boa's implementation of ECMAScript's builtins, you can find them under `boa_engine/src/builtins`
