### ISSUE TITLE
New logo proposal

### ISSUE THREAD

**Issue by kelbazz** [boa-dev/boa#3158]
Hey, I've made a new logo for boa, because I feel like the current one is a bit classic. What do you think of it?
I have the svgs if needed.

![BoaJS](https://github.com/boa-dev/boa/assets/81097895/1df8b9bd-a692-434a-a9ad-e0905c40cc25)
![boadev_l](https://github.com/boa-dev/boa/assets/81097895/988179b1-c46b-4c67-a35f-ee14444f4768)
![boadev_d](https://github.com/boa-dev/boa/assets/81097895/ec2afed5-da87-4b98-bf67-54332b21c570)

**Comment by kelbazz** [comment]
This logo is working great small, works with multiple colors and textures and is modernized. Hope this can help!

**Comment by Razican** [comment]
These logos look great! It would be best if you added the SVGs as well :)

We are in the process of enhancing the website, so this could be a great addition. Thanks!

**Comment by kelbazz** [comment]
[BoaJS_logos.zip](https://github.com/boa-dev/boa/files/12139036/BoaJS_logos.zip)
Here there are!

**Comment by ahaoboy** [comment]
Can we add this logo to boa_cli?
https://github.com/mxre/winres

**Comment by kelbazz** [comment]
Yes for sure!
