### ISSUE TITLE
not support unescape and escape function on boa_engine?

### ISSUE THREAD

**Issue by paomian** [boa-dev/boa#3257]
**Describe the bug**
not support `unescape` and `escape` function?
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JsError { inner: Native(JsNativeError { kind: Reference, message: "unescape is not defined", cause: None, .. }) }'
```

**To Reproduce**
code on https://github.com/brix/crypto-js/blob/develop/src/core.js#L526
In the following is the code for minimal reproduction
```
        let mut context = Context::default();
        let c = r#"unescape(encodeURIComponent("abc"))"#;
        let result = context.eval(Source::from_bytes(c.as_bytes())).unwrap();
        println!("xxxxxxxxx {:#?}", result.as_string().unwrap());
```

**Expected behavior**
can print `abc` and It work well on boa playground.

**Build environment (please complete the following information):**

- OS: Fedora
- Version: 38

```
rustc --version -v
rustc 1.71.0 (8ede3aae2 2023-07-12)
binary: rustc
commit-hash: 8ede3aae28fe6e4d52b38157d7bfe0d3bceef225
commit-date: 2023-07-12
host: x86_64-unknown-linux-gnu
release: 1.71.0
LLVM version: 16.0.5
```

**Comment by jedel1043** [comment]
`unescape` is deprecated, and by [Mozilla's recommendation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape) we didn't implement it intentionally. Please use `decodeURI` instead.

**Comment by paomian** [comment]
Yes, `unescape` is deprecated. but so many js libs are use it. 
Compatibility is a complex topic.

**Comment by jedel1043** [comment]
Ah, forgot to mention that if you need to use deprecated methods, you can enable the `annex-b` feature flag to expose those inside the global object.
