### ISSUE TITLE
Optimize the lexer by iterating over bytes

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#335]
As `maciejh` mentioned in [Reddit][reddit_comment], iterating over characters is not fast. We should iterate over bytes, but we have to take into account that identifiers, strings, comments and more can have non-ASCII characters, since JavaScript is UTF-8.

Nonetheless, we can use byte-iteration for detecting language features much faster.

The comment:
> Iterating over bytes rather than chars is inherently much faster, non-ascii UTF8 bytes are all >=128, and you might only really care about those being correct when parsing idents.

[reddit_comment]: https://www.reddit.com/r/rust/comments/g3m5i7/boa_releases_v07_with_a_much_faster_parser/fnsng09

**Comment by jevancc** [comment]
Hi @Razican, I'd like to work on this issue. I can also look into how the new lexer can fix the utf-8 /utf-16 issues.

**Comment by jasonwilliams** [comment]
Awesome @jevancc assigned
