### ISSUE TITLE
Implement `[[HostDefined]]` for `Module` and `Script`

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#3379]
We left the implementation of `[[HostDefined]]` fields for `Script` and `Module` as a future improvement, but it's pretty necessary for users that want to store additional data on a runnable.

`Script`:

https://github.com/boa-dev/boa/blob/348c757b94a251f65c65b88dd41bb860c8e46862/boa_engine/src/script.rs#L45-L53

`Module`:

https://github.com/boa-dev/boa/blob/348c757b94a251f65c65b88dd41bb860c8e46862/boa_engine/src/module/mod.rs#L284-L291

Probably a simple `GcRefCell<Box<dyn NativeObject>>` and an accessor/mutable accessor should be enough for both.

**Comment by arexon** [comment]
I'm willing to work on this.

> Probably a simple GcRefCell<Box<dyn NativeObject>> and an accessor/mutable accessor should be enough for both.

Wouldn't this use [`HostDefined`](https://github.com/boa-dev/boa/blob/cdd5712d0fe50763cf3fb748c10b1d58b2de6b13/boa_engine/src/host_defined.rs#L18)? Or is `[[HostDefined]]` meant to store only 1 object in `Script` and `Module`?

**Comment by jedel1043** [comment]
> Wouldn't this use [`HostDefined`](https://github.com/boa-dev/boa/blob/cdd5712d0fe50763cf3fb748c10b1d58b2de6b13/boa_engine/src/host_defined.rs#L18) struct? Or is `[[HostDefined]]` meant to store only 1 object in `Script` and `Module`?

Both are good. We can implement it using `HostDefined` for now and if there's not much usage for storing multiple objects, we can just return to a simple `Box<dyn NativeObject>`.
