### ISSUE TITLE
Promise all runs concurrently instead of joining

### ISSUE THREAD

**Issue by ezenkico** [boa-dev/boa#3395]
Promise all seems to run the promises concurrently and does not join them and run them in async parallel.

I wrote this to test this
Javascript
`
async function testD(amount){
  await delay(amount);
}
print("start");
let res = 5.5;
let p = []
p.push(testD(5));
p.push(testD(10));
p.push(testD(10));
p.push(testD(10));
Promise.all(p).then(() => {
  print("delay");
  res = 4;
})
print("after");

res
`

Rust delay function
`
let delay = NativeFunction::from_async_fn(|
        _this: &JsValue,
    args: &[JsValue],
    _context: &mut Context<'_>
        |{
            let mut args: Vec<JsValue> = args.into_iter().map(|arg|arg.clone()).collect();
            async move{
                if args.is_empty(){
                    return Ok(JsValue::Undefined);
                }
                match args.remove(0){
                    JsValue::Integer(d) => {
                        sleep(Duration::from_secs_f64(d as f64)).await;
                    }
                    JsValue::Rational(d) => {
                        sleep(Duration::from_secs_f64(d)).await;
                    }
                    JsValue::BigInt(d) => {
                        sleep(Duration::from_secs_f64(d.to_f64())).await;
                    }
                    _ => {}
                }
                Ok(JsValue::Undefined)
            }
        });
`

My test takes 35 seconds when it should only take 10

**Comment by jedel1043** [comment]
I suspect you're using the default sync runtime which just uses `pollster`.

See https://github.com/boa-dev/boa/blob/main/boa_examples/src/bin/futures.rs for an example on how to bind to an async runtime and drive futures concurrently.

**Comment by ezenkico** [comment]
This seems to be what I'm looking for.

You guys respond quickly

Thanks
