### ISSUE TITLE
Array.shift is very slow

### ISSUE THREAD

**Issue by ahaoboy** [boa-dev/boa#3402]
**Describe the bug**
 Array.shift is very slow
 
**To Reproduce**
 ```
let n = 5000;
let a = Array(n).fill(0);

while (a.length) a.shift()

```
### node 92ms
```
 time node  ./test.js

________________________________________________________
Executed in   92.91 millis    fish           external
   usr time    0.00 millis    0.00 micros    0.00 millis
   sys time   15.00 millis    0.00 micros   15.00 millis

```
### boa 37s 
```
 time boa-windows-amd64 ./test.js 
0

________________________________________________________
Executed in   37.36 secs      fish           external
   usr time   16.00 millis   16.00 millis    0.00 millis
   sys time   15.00 millis    0.00 millis   15.00 millis

```
### qjs 45ms

```
 time qjs ./test.js 

________________________________________________________
Executed in   45.28 millis    fish           external
   usr time    0.00 micros    0.00 micros    0.00 micros
   sys time    0.00 micros    0.00 micros    0.00 micros
```

**Expected behavior**
 Array.shift should have better performance

**Build environment (please complete the following information):**

- OS: win11 boa 0.17.3 
- Version: [e.g. 32]
- Target triple: [e.g. x86_64-unknown-linux-gnu]
- Rustc version: [e.g. rustc 1.43.0 (4fb7144ed 2020-04-20), running `rustc -V`]

**Additional context**
 
The performance of the  Array.pop function is the same as  the others, all taking around 100ms. However, the  Array.pop operation is exceptionally slow, especially when the array length exceeds 10,000.

```
let n = 5000;
let a = Array(n).fill(0);

while (a.length) a.pop()
```

**Comment by ahaoboy** [comment]
@jedel1043 How about Array.unshift,  unshift and shift functions are quite similar, and both are very slow. Can similar methods be used for optimization?

**Comment by jedel1043** [comment]
> @jedel1043 How about Array.unshift,  unshift and shift functions are quite similar, and both are very slow. Can similar methods be used for optimization?
> 
> Array.splice is also a commonly used method for modifying arrays, and it's slow in Boa as well.
> 
> ```
> let a = [];
> let n = 10000;
> while(n--) a.splice(0,0,n)
> console.log(a)
> ```
> 
> 

Yeah, array operations in general need a lot of extra work. I'll open a tracking issue for that.

**Comment by jedel1043** [comment]
https://github.com/boa-dev/boa/issues/3407
