### ISSUE TITLE
Web Api support?

### ISSUE THREAD

**Issue by ahaoboy** [boa-dev/boa#3408]
https://developer.mozilla.org/en-US/docs/Web/API
https://developer.mozilla.org/en-US/docs/Web/API/URL_API
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder
**ECMASCript feature**
 I'm not sure if it should be supported in Boa, but there are some commonly used APIs built into Node and Deno.

**Comment by Razican** [comment]
This has been discussed quite a bit. The thing is that Boa is currently a JS engine (like V8) not a runtime. We might want to create a runtime in the future, but the ideal situation would be for Deno/Node to offer using Boa instead of V8. But that's a difficult proposal.

**Comment by jedel1043** [comment]
Closing since it isn't in our plans to implement runtime features.
