### ISSUE TITLE
Implement the optional `reviver` parameter in `JSON.parse( text [, reviver] )` 

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#344]
Currently the `JSON.parse( text[, reviver] )` method only supports the first parameter which takes in a `String` and converts into an `Object`.
But, there is an optional function argument that `JSON.parse( text[, reviver] )` method takes. It prescribes how the value originally produced by parsing is **transformed**, before being returned.

Example:
```javascript
JSON.parse('{"1": 1, "2": 2, "3": {"4": 4, "5": {"6": 6}}}', (key, value) => {
  console.log(key); // log the current property name, the last is "".
  return value;     // return the unchanged property value.
});
```

More information:
 - [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)
 - [ECMAScript reference](https://tc39.es/ecma262/#sec-json.parse)

You can check the [`Array.prototype.every`](https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/array/mod.rs#L491) implementation to see how to deal with JavaScript callback functions.

**Comment by abhijeetbhagat** [comment]
I can take this. Btw, the link to `Array.prototype.every` is pointing to the wrong line number. It should be 491.

**Comment by Razican** [comment]
> I can take this. Btw, the link to `Array.prototype.every` is pointing to the wrong line number. It should be 491.

Sure! Go for it :)

I think I fixed the link 😅

**Comment by abhijeetbhagat** [comment]
Can you please assign it to me?
