### ISSUE TITLE
Implement the optional `replacer` parameter in `JSON.stringify( value[, replacer [, space] ] )`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#345]
The `JSON.stringify(value[, replacer[, space]])` takes in three arguments.

The `replacer` argument is a **function** that alters the behavior of the `stringification` process, or an **array** of `String` and `Number` objects that serve as a whitelist for selecting/filtering the properties of the value object to be included in the `JSON` string. If this value is `null` or not provided, all properties of the object are included in the resulting `JSON` string.

Example:
```JavaScript
function replacer(key, value) {
  // Filtering out properties
  if (typeof value === 'string') {
    return undefined;
  }
  return value;
}

var foo = {foundation: 'Mozilla', model: 'box', week: 45, transport: 'car', month: 7};
JSON.stringify(foo, replacer);
// '{"week":45,"month":7}'
```
More information:
 - [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)
 - [ECMAScript reference](https://tc39.es/ecma262/#sec-json.stringify)

**Comment by n14little** [comment]
I’ll take this one.

**Comment by HalidOdat** [comment]
> I’ll take this one.

Sure! Go for it.
