### ISSUE TITLE
RegExp exec failed 

### ISSUE THREAD

**Issue by ahaoboy** [boa-dev/boa#3474]
**Describe the bug**
When the matching string is Chinese, the RegExp (`new RegExp("[\x00-\x1f\x7f-\x9f]", "g") `) fails to execute 

**To Reproduce**
```js
let string = "我"
const StringPrototypeReplace = (that, ...args) =>
  String.prototype.replace.call(that, ...args);

const ESCAPE_PATTERN2 = new RegExp("[\x00-\x1f\x7f-\x9f]", "g");

StringPrototypeReplace(string, ESCAPE_PATTERN2)

```

```
thread 'main' panicked at C:\Users\XXX\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\regress-0.7.1\src\indexing.rs:223:9:
assertion failed: pos == self.right_end() || is_seq_start(self.getb(pos))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:/Users/Ace/ct\debug\loadfile.exe` (exit code: 101)
```

**Expected behavior**
No error
 

**Build environment (please complete the following information):**

- OS: win11
- Rustc version: rustc 1.76.0-nightly (2c1b65ee1 2023-11-11)

**Comment by jedel1043** [comment]
Seems like a `regress` bug. Can you try to reproduce it using the `regress` crate directly?

**Comment by jedel1043** [comment]
Or maybe it's a bug with our index handling? I'll investigate that.

**Comment by ahaoboy** [comment]
> ```js
> [\x00-\x1f\x7f-\x9f]
> ```

It's a regress bug
https://github.com/ridiculousfish/regress/issues/73

**Comment by jedel1043** [comment]
Cool, I'll close this then.
