### ISSUE TITLE
Implement `Number.prototype.toPrecision`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#349]
The `toPrecision()` method returns a string representing the `Number` object to the specified precision.

More information:
 - [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Number/toPrecision)
 - [ECMAScript reference](https://tc39.es/ecma262/#sec-number.prototype.toprecision)

**Comment by zanayr** [comment]
I think I can handle this. :)

I assume it'll live in number/mod.rs?

**Comment by HalidOdat** [comment]
> I assume it'll live in number/mod.rs?

Yes. There already is the `to_precision` function but its not implemented [here](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/number/mod.rs#L165-L188)

**Comment by zanayr** [comment]
Hello, I'm finally moving on this, sorry for the delay. I understand what we are trying to do with toPercision, but I have a few questions concerning the ECMA documentation:

1. In step 9.a, "let e and n..." I'm going to need an explainer on this math.. or a resource.. I understand some of it, but I'm not really familiar with range math? I think..
2. In step 9.b, "let m be the String..." Does that me something like: '.0001'?
3. In step 9.c.ii.1, "Let a be the first code unit..." I assume they mean the 0x value for whatever character is first in m?

Thanks! Best,

**Comment by zanayr** [comment]
Actually I think I just figured out #1. It's just a fancy way of saying n * 10^(e - p + 1) - x
The other questions still stand, but I think my assumptions are correct with those as well.

Best,

**Comment by HalidOdat** [comment]
Hi @zanayr 

Maybe checking other engines implementation will help:
V8: <https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/conversions.cc#L1159-L1225>
SpiderMonkey: <https://searchfox.org/mozilla-central/source/mfbt/double-conversion/double-conversion/double-to-string.cc#241-293>

**Comment by Razican** [comment]
Hello @zanayr, how is this going?

**Comment by zanayr** [comment]
> Hello @zanayr, how is this going?

Hello @Razican, Apologies I have been extremely busy and this slipped my mind. I think I left off somewhere still trying to figure out the math behind 9a. I don't know if I can figure it out, perhaps I should've picked an easier issue. 😅

**Comment by Razican** [comment]
> > Hello @zanayr, how is this going?
> 
> Hello @Razican, Apologies I have been extremely busy and this slipped my mind. I think I left off somewhere still trying to figure out the math behind 9a. I don't know if I can figure it out, perhaps I should've picked an easier issue. sweat_smile

Would you like us to un-assign it from you? Or would you like to create a draft PR to get some feedback / help?

**Comment by zanayr** [comment]
> > > Hello @zanayr, how is this going?
> > 
> > 
> > Hello @Razican, Apologies I have been extremely busy and this slipped my mind. I think I left off somewhere still trying to figure out the math behind 9a. I don't know if I can figure it out, perhaps I should've picked an easier issue. sweat_smile
> 
> Would you like us to un-assign it from you? Or would you like to create a draft PR to get some feedback / help?

I probably should be un-assigned, I don't have the bandwidth to work on it right now, and I didn't really get that far to begin with. Apologies again, as soon as I am more free, I will return for to help on this project.

**Comment by AlfredTH** [comment]
Hey ! I'm currently working on this.

**Comment by NathanRoyer** [comment]
Hey ! I'm currently working on this.
