### ISSUE TITLE
Variables declared without var are not recognized as global in Non-Strict Mode.

### ISSUE THREAD

**Issue by mvrius** [boa-dev/boa#3532]
**Describe the bug**
Variables declared without `var` are not registered globally.

**To Reproduce**
Following the example here: https://github.com/boa-dev/boa/blob/70c235ea86dde183006397fca45e7dda3f96d010/examples/src/bin/synthetic.rs

I'm loading a module file as such:

```rust
 let js_file_path = "./scripts/helloworld.js";
    let source = Source::from_filepath(Path::new(js_file_path))?;
 let context = &mut Context::builder().build()?;
 add_runtime(context);
let module = Module::parse(source, None, context)?;
let promise_result = module.load_link_evaluate(context);
context.run_jobs();
let namespace = module.namespace(context);
```

And calling a function inside the module a such:

```rust
let helloWorld= namespace
    .get(js_string!("helloWorld"), context)?
    .as_callable()
    .cloned()
    .ok_or_else(|| JsNativeError::typ().with_message("helloWorld export wasn't a function!"))?;
 ```
 The issue arrises when the script function tries to access global variables
 
 ```js
var gVar1 = 'test';
gVar2 = 'test;
export function helloWorld(delta) {
console.log('hello');
console.log(gVar1);
console.log(gVar2);
}
 ```
It throws this error:
Error: JsError { inner: Native(JsNativeError { kind: Reference, message: "gVar2" is not defined", cause: None, .. }) }

**Expected behavior**

In non-strict mode I would expect the object to be created on the global scope and accessible.

**Additional context**

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment

> `// In non-strict mode, assumes you want to create a property named `foo` on the global object`

> `In [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#assigning_to_undeclared_variables), assignment to an unqualified identifier in strict mode will result in a ReferenceError, to avoid the accidental creation of properties on the global object.`

I did try setting strict mode off explicitly on the context but that didn't fix the issue.:

```rust
    let context = &mut Context::builder().build()?;
    context.strict(false);
```

**Comment by jedel1043** [comment]
Ummm, modules can never be non-strict per the spec...

**Comment by mvrius** [comment]
Thanks, missed that.

I'm noticing that if I'm declaring the variables with `var`, like in example above. The functions always reads the values as undefined. 

Is that also expected?

```js
console.log('hello');
console.log(gVar1);
```

The output of above is:
```
hello
undefined
```

**Comment by mvrius** [comment]
I also tried exporting the defined variable to see if it makes any difference, and it's value is not accessible in a module function.

```js
export var gVar1 = 'test';
```

**Comment by jedel1043** [comment]
Closing since I ran the scripts on `main` and everything looks fine.
