### ISSUE TITLE
Realm `host_defined` and `host_defined_mut` functions aren't accessible

### ISSUE THREAD

**Issue by zlindner** [boa-dev/boa#3544]
**Describe the bug**
Realm's `host_defined` and `host_defined_mut` aren't accessible on `Realm`.

**To Reproduce**
Following the `host_defined.rs` example ([here](https://github.com/boa-dev/boa/blob/main/examples/src/bin/host_defined.rs)):
```
let mut context = Context::default();
let realm = context.realm().clone();
let host_defined = realm.host_defined_mut();
```

Gives the following compiler error:
```
error[E0599]: no method named host_defined_mut found for struct boa_engine::realm::Realm in the current scope
  --> src/main.rs:28:34
   |
28 | let host_defined = realm.host_defined_mut();
   |                          ^^^^^^^^^^^^^^^^ method not found in Realm
```

**Expected behavior**
`host_defined` and `host_defined_mut` should be accessible, so we can store shared user defined state between Rust and JS.

**Build environment (please complete the following information):**

- OS: macOS
- Version: boa_engine 0.17.3
- Rustc version: rustc 1.75.0 (82e1608df 2023-12-21)

**Comment by jedel1043** [comment]
Uh the `host_defined` API was introduced after version 0.17.3 released, and will be publicly available on the next release. If you want to experiment with the new features in the meantime, feel free to [specify the dependency using git urls](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).

**Comment by zlindner** [comment]
Ah I see my bad, thanks :)
