### ISSUE TITLE
Can't regex match on string containing emoji

### ISSUE THREAD

**Issue by gschier** [boa-dev/boa#3589]
**Describe the bug**
Regex throws error if matching on string containing emoji.

**To Reproduce**
Run this JavaScript code in the playground (or anywhere):

```javascript
`🐞`.match(/anything/);
```

![CleanShot 2024-01-15 at 21 16 40@2x](https://github.com/boa-dev/boa/assets/587576/f76da1d8-a33a-488b-a546-e3f19fcd3596)

**Expected behavior**
The error `Failed to get byte index from utf16 encoded string` is emitted. There's an error message silenced [here](https://github.com/boa-dev/boa/blob/d09bcc8f2de4a7da0a5dca3059c8b6f96bfc8a4a/core/engine/src/builtins/regexp/mod.rs#L930), which I printed out and got the following `invalid utf-16: lone surrogate found`.

**Build environment (please complete the following information):**
The hosted [Boa Playground](https://boajs.dev/boa/playground/);

**Comment by jedel1043** [comment]
Thanks to #3627, this is fixed on the main branch :)

**Comment by gschier** [comment]
Awesome! 🤩
