### ISSUE TITLE
Implement Array prototype methods

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#36]
Similar to https://github.com/boa-dev/boa/issues/13 but for the Array 

- [x] Array.of() (#1127)
- [x] Array.prototype.concat()
- [x] Array.prototype.copyWithin()
- [x] Array.prototype.entries()
- [x] Array.prototype.every()
- [x] Array.prototype.fill()
- [x] Array.prototype.filter()
- [x] Array.prototype.find()
- [x] Array.prototype.findIndex()
- [x] Array.prototype.flat()
- [x] Array.prototype.flatMap()
- [x] Array.prototype.forEach()
- [x] Array.prototype.includes()
- [x] Array.prototype.indexOf()
- [x] Array.prototype.join()
- [x] Array.prototype.keys()
- [x] Array.prototype.lastIndexOf()
- [x] Array.prototype.map()
- [x] Array.prototype.pop()
- [x] Array.prototype.push()
- [x] Array.prototype.reduce()
- [x] Array.prototype.reduceRight()
- [x] Array.prototype.reverse()
- [x] Array.prototype.shift()
- [x] Array.prototype.slice()
- [x] Array.prototype.some()
- [x] Array.prototype.sort()
- [x] Array.prototype.splice()
- [ ] Array.prototype.toLocaleString()
- [x] Array.prototype.toString()
- [x] Array.prototype.unshift()
- [x] Array.prototype.values()
- [x] Array.prototype[@@iterator]()

Implementation happens here: https://github.com/boa-dev/boa/blob/master/boa/src/builtins/array/mod.rs

**Comment by callumquick** [comment]
@jasonwilliams For the array, what is a Javascript array represented as in Boa? From my investigation appears to be as an Object, so in the underlying Rust a hashmap mapping from index to value: is that accurate? 

Does that mean in Boa there's no Javascript difference between arrays and objects? Is that intentional or just because Array isn't implemented yet? Should we have an "Array" entry in the ValueData enum?

**Comment by jasonwilliams** [comment]
That's a very good point, and yes, what you said is accurate. There is no Array primitive value in JavaScript, so we can't have an array datatype in the value enum.  (for now) An Array is just an Object with a prototype of Array methods.

V8 do some optimisations with arrays with a backing store: https://v8.dev/blog/fast-properties
I'm not sure we need to worry about fast property access just yet.

For now we just need to create a global constructor (Array), similar to what we do with strings.
Arrays are then objects who's prototype is set to `Array.prototype`.

**Comment by callumquick** [comment]
I think my main questions would likely be whether in order to implement the majority of Array prototype methods we should be converting to real Rust arrays/Vectors/etc under the covers or just using hashmaps for now?

**Comment by jasonwilliams** [comment]
I would go hashmaps for now, you will hit way too many edge/corner cases if you try to convert them to Rust Vectors (i.e length shouldn't be counted). It's not the most performant but the most correct. We can fix speed later on with some optimisations.

**Comment by simonbrahan** [comment]
I'll take a look at `indexOf` and `lastIndexOf`.

**Comment by jasonwilliams** [comment]
@simonbrahan ok great

**Comment by IovoslavIovchev** [comment]
I'd like to take a look at `indexOf` and possibly `map`.

**Comment by muskuloes** [comment]
I'll like to work on `slice`

**Comment by jasonwilliams** [comment]
@IovoslavIovchev  can you put yourself on (or reply to) this issue https://github.com/jasonwilliams/boa/issues/176

@muskuloes same for https://github.com/jasonwilliams/boa/issues/177

**Comment by simonbrahan** [comment]
Can I take `includes`?

**Comment by HalidOdat** [comment]
A lot of those methods have already been implemented. Such as `every`, `find`, `some` and some others.
I think we should update the check list. :)

**Comment by Razican** [comment]
I updated the checklist. I noticed that the `Array.prototype.includes()` does not have documentation.

**Comment by HalidOdat** [comment]
> I updated the checklist. I noticed that the `Array.prototype.includes()` does not have documentation. 

I will documentation for it

I

**Comment by brian-gavin** [comment]
Hey, like String the links are out of date now.

Array can now be found [here](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/array/mod.rs)!

**Comment by Razican** [comment]
> Hey, like String the links are out of date now.
> 
> Array can now be found [here](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/array/mod.rs?rgh-link-date=2020-06-01T02%3A39%3A29Z)!

Yep! I updated the link, and once again, this might be blocked in #419.

**Comment by benjaminflin** [comment]
I'd like to take a look at `reduce`

**Comment by Razican** [comment]
> I'd like to take a look at `reduce`

Go ahead! :D

**Comment by benjaminflin** [comment]
Also Since I did `reduce`, `reduceRight` should be pretty straightforward to implement.

**Comment by HalidOdat** [comment]
@joshwd36 has implemented `Array.prototype.keys()`, `Array.prototype.entries()`, `Array.prototype.values()` and `Array.prototype@@iterator` in #704

**Comment by davidmikulis** [comment]
Hi all, I would like to work on `Array.prototype.flat` and `Array.prototype.flatMap` if those are available.

**Comment by HalidOdat** [comment]
Go ahead @davidmikulis :)

**Comment by davidmikulis** [comment]
The Pull Request for `Array.prototype.flat` and `Array.prototype.flatMap` is available at #1132 for whenever anyone has time to review. Thanks!

**Comment by jedel1043** [comment]
Should `Array.prototype.toSource()` be implemented at all? [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSource) shows that there's barely any support for this method, as it was deprecated many years ago.

**Comment by Razican** [comment]
> Should `Array.prototype.toSource()` be implemented at all? [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSource) shows that there's barely any support for this method, as it was deprecated many years ago.

It shouldn't be implemented, since it's not in the spec.

**Comment by jedel1043** [comment]
@raskad We're still missing `toLocaleString`.

**Comment by Razican** [comment]
> We're still missing `toLocaleString`. Maybe we could transfer all internationalization missing features into its own issue to close this one.

Yes, let's move localization yo a different issue. Is everything else done?

**Comment by jedel1043** [comment]
> > We're still missing `toLocaleString`. Maybe we could transfer all internationalization missing features into its own issue to close this one.
> 
> Yes, let's move localization yo a different issue. Is everything else done?

Yep, everything else is implemented

**Comment by jedel1043** [comment]
Closing in favour of #1562.
