### ISSUE TITLE
Divide the `run()` function in smaller portions

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#366]
Currently, the `run()` function is around 500 lines long. This is going to quickly become unmaintainable, so we need to divide this.

The first thing that comes to my mind to improve this is to just create new function for each `match` arm, but as we saw in the parser, we can probably do this better and easier to understand.

One option is to have an `Executable` trait, as I proposed in #304. This trait would just be as simple as this:

```rust
trait Executable {
	fn run<E>(interpreter: &mut E) -> ResultValue where E: Executor;
}
```

Then, I think that we should change the `Node` enum to be just a `Box<dyn Executable>`. And each `Node` type should be a struct where we could use `Box` to box dynamic types, or we could use compile-time generics to have less allocations (but longer compile times).

Then we implement this trait individually for each of the node types, which is easily extensible, and we reduce the `run()` function to:

```rust
fn run(&mut self, node: &Node) -> ResultValue {
	node.run(&mut self)
}
```

Tracking:

 - [x] `Node::ArrayDecl`
 - [x] `Node::ArrowFunctionDecl`
 - [x] `Node::Assign`
 - [x] `Node::BinOp`
 - [x] `Node::Block`
 - [x] `Node::Break`
 - [x] `Node::Call`
 - [x] `Node::ConditionalOp`
 - [x] `Node::Const`
 - [x] `Node::ConstDeclList`
 - [x] `Node::Continue`
 - [x] `Node::DoWhileLoop`
 - [x] `Node::FunctionDecl`
 - [x] `Node::FunctionExpr`
 - [x] `Node::GetConstField`
 - [x] `Node::GetField`
 - [x] `Node::ForLoop`
 - [x] `Node::If`
 - [x] `Node::LetDeclList`
 - [x] `Node::Identifier`
 - [x] `Node::New`
 - [x] `Node::Object`
 - [x] `Node::Return`
 - [x] `Node::Switch`
 - [x] `Node::Spread`
 - [x] `StatementList`
 - [x] `Node::Throw`
 - [x] `Node::Try`
 - [x] `Node::This`
 - [x] `Node::UnaryOp`
 - [x] `Node::VarDeclList`
 - [x] `Node::WhileLoop`

**Comment by HalidOdat** [comment]
Hmmm. I think doing this at compile time is better than having to do it at runtime.
Using `Box<dyn Trait>` has to allocate and use dynamic dispatch (`vtable`) which would worsen the execution time.

**Comment by Razican** [comment]
> Hmmm. I think doing this at compile time is better than having to do it at runtime.
> Using `Box<dyn Trait>` has to allocate and use dynamic dispatch (`vtable`) which would worsen the execution time.

So, `Node` would be `Node<T: Executable>`, but that would make it more difficult to have for example a `Vec<Node>` of different kinds, and we already use `Box` inside of nodes, this would just make a `Box` and only one allocation per node.

**Comment by Razican** [comment]
A different option would be to still have an `enum`, but each of the enum members would be just a box to a given `Executable`.

**Comment by Razican** [comment]
Tracking list of  nodes added, now that we have the infrastructure in place.

This could be a very good first issue, since it shows you how the AST nodes work, so feel free to claim it and to ask for help!

**Comment by Lan2u** [comment]
I shall give it a go :)

**Comment by Razican** [comment]
> I shall give it a go :)

Go ahead!
