### ISSUE TITLE
custom `JsValue` for better embed 

### ISSUE THREAD

**Issue by yuyang-ok** [boa-dev/boa#3729]
When I want to embed `Boa`, I found it is hard to embed to my project.
I want to add a global varaible such as `DB` where I can receive some data from database.
Is that possible add a trait JsValue,
such as
~~~
pub trait JsValueTrait {
  fn access_field(&self , name : String) -> JsResult<JsValue>;
   ...
}

pub enum JsValue {
    Null,
    Undefined,
    ...
    TraitObject(Box<dyn JsValueTrait >)
}

~~~

**Comment by jedel1043** [comment]
We do support custom data on `JsValue`! It's just behind APIs offered by `JsObject` instead. A good starting point is the `JsObject::from_proto_and_data` method, which accepts any type that implements `NativeObject`.

You can also check out our `class.rs` example for more complex embeddings using the `Class` trait.
