### ISSUE TITLE
Hoisting variables

### ISSUE THREAD

**Issue by hello2dj** [boa-dev/boa#376]
now not founding Identifier will always be undefined, for `function` or  `var` this is wrong.

[moreinfo](https://www.ecma-international.org/ecma-262/10.0/index.html#prod-HoistableDeclaration)

example:
```
// v8
console.log(A); // [Function: A]
function A() {}
```

```
// boa
console.log(A); // undefined
function A() {}
```

**Comment by Razican** [comment]
This seems to be related to the fact that we execute nodes in order, instead of having a special category for this. These functions should be evaluated first, and then start evaluating the rest of statements.

**Comment by jasonwilliams** [comment]
I don't think v0.9.0 is realistic for this, for hoisting to work would require a big refactor of how execution works, including having some pre-parsing step.

We're no where near that point yet.

**Comment by Razican** [comment]
> I don't think v0.9.0 is realistic for this, for hoisting to work would require a big refactor of how execution works, including having some pre-parsing step.
> 
> We're no where near that point yet.

Actually, this seems to be already working in #392.

**Comment by jasonwilliams** [comment]
oh ok interesting.
Should we be doing something more closely related to https://v8.dev/blog/preparser#variable-allocation? is reordering sound?

**Comment by Razican** [comment]
> Should we be doing something more closely related to https://v8.dev/blog/preparser#variable-allocation?

Definitelly, but I think it's a reasonable workaround in the meantime.

> is reordering sound?
It should be, it's  slower, as we will be doing a sort, but it's always maintaining ordering, so it's sound as far as I can tell.
