### ISSUE TITLE
Restrict Direct Construction of `JsValue` to Ensure Invariants

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#3761]
The problem lies in the ability for users to manually construct a `JsValue::Rational` from a `f64` value that fits within an `i32`, as `JsValue` is a public enum.

A proposed solution is to introduce a struct that encapsulates the `JsValue` enum. By doing so, construction of `JsValue::Rational` would be limited to its respective constructor functions.

This would allow us to remove many checks that are done to see if a `JsValue::Rational` f64 value can fit in a `i32`.

#### Additional Information

Related to #1373 , something similar was done in #1830 [here](https://github.com/boa-dev/boa/pull/1830/files#diff-4ceaca6aca7724add3b14ceb8c1c859ad48c404924be9b48cc0a407e6e2340e6R7-R34)

**Comment by jedel1043** [comment]
@MartiPresa Sure! Let me assign it to you.

**Comment by MartiPresa** [comment]
I will start checking on this.
Thanx!
