### ISSUE TITLE
Relative imports in SimpleModuleLoader fail to resolve

### ISSUE THREAD

**Issue by hansl** [boa-dev/boa#3782]
`SimpleModuleLoader` is a file-based `ModuleLoader` implementation that is used in examples and tests and suggested as a first step when starting using Boa.

It is very straightforward in its implementation; normalize the module specifier relative to the root of the asset path, and load the file. Normalization will make sure all paths exist on the filesystem.

Unfortunately, it does not resolve relative to the module doing the import. The specifier is passed as is (from the JavaScript) with the referrer, but it is impossible to resolve from that point because the referrer does not expose any path information.

This is shown in PR https://github.com/boa-dev/boa/pull/3781 that adds a test for this specific issue.

This highlight an issue with the design of the `ModuleLoader` trait. There is currently no way to access the path of the module doing the import, and so there's no way to do relative imports. This is a major flaw that might prevent Boa from being considered at all, at least for my project.

It is unclear if the resolution of relative imports should be done prior from sending to the `ModuleLoader` or as part of the `ModuleLoader` itself. I would suggest the former solution if the specifier starts with `./` or `../`, to streamline how the normalization of the specifier is done across the engine. That being said, I'll defer to people with more knowledge of the project.

**Comment by jedel1043** [comment]
Ah, that's easy to fix! We just need to add a path property to the `Module` struct (or possibly only to `SourceTextModule`, but I could see it being useful to set a synthetic module to a fake path), and have it being set at creation time.

Should probably be a good idea to also add this to `Source`, since it should be a pretty straightforward change. Then, we could expose a `Referrer::path() -> Option<&Path>` method for ease of use.

**Comment by jedel1043** [comment]
To clarify, the exact implementation steps would be:
1. Expose the `path` property of the [`Source`](https://github.com/boa-dev/boa/blob/2b7c7050fb879051650c4a1e8b84d9be4a7158c4/core/parser/src/source/mod.rs#L20-L23) type with a getter.
2. Modify [`ModuleRepr`](https://github.com/boa-dev/boa/blob/5c200103286de44fc87756536b6081467d4b9187/core/engine/src/module/mod.rs#L73-L78) and [`source::Inner`](https://github.com/boa-dev/boa/blob/5c200103286de44fc87756536b6081467d4b9187/core/engine/src/script.rs#L43-L50) to have a `path: PathBuf` property, and set it on their respective `parse` methods from the `path` property of `Source`.
3. Add a new `path` method to [`Referrer`](https://github.com/boa-dev/boa/blob/5c200103286de44fc87756536b6081467d4b9187/core/engine/src/module/loader.rs#L18-L25) that gets a reference to the `path` property of `Source` and `Module`.

**Comment by hansl** [comment]
So it would be the responsibility of the `ModuleLoader` to implement (or not) resolution of specifiers?

**Comment by jedel1043** [comment]
Yes, simply because the core engine shouldn't have a notion of a "filesystem", since that would break the sandboxing we have in place for it. Implementors of `ModuleLoader` can decide if they want to preserve the sandbox or if they want to allow filesystem calls.
