### ISSUE TITLE
`Context::get_active_script_or_module` should return a script or module when using import in a generator

### ISSUE THREAD

**Issue by hansl** [boa-dev/boa#3790]
This is a pretty hard problem to fix for me at the moment, as I lack a lot of the internal knowledge around realms and call frames.

In the test262 `test/language/expressions/dynamic-import/for-await-resolution-and-error-agen-yield.js`, the following code:

```js
async function * agen1() {
    yield import('./for-await-resolution-and-error-a_FIXTURE.js');
    yield import('./for-await-resolution-and-error-b_FIXTURE.js');
    yield import('./for-await-resolution-and-error-poisoned_FIXTURE.js');
}
```

Will load the call `load_imported_module` with the right `Referrer` (this file) and its path, but the second and third `yield` will have a `Referrer` of `Realm` which means they'll have no path associated with them and thus cannot import with a relative path.

These tests were passing before but were a false positive as the path was always resolved from the root of the module loader (which in this case is the parent of the script being run).

**Comment by jedel1043** [comment]
That's interesting! We supposedly store the whole execution context before every yield, so it should be restored after a suspension, but this shows that it apparently doesn't.

I'll see what's happening here.
