### ISSUE TITLE
Add Boa Matrix space to the repo

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#3811]
Since we moved all the development discussion to Matrix, it would be good to add some links to the [Boa space](https://matrix.to/#/#boa:matrix.org) on all the places in the repo that also link to the Discord.

**Comment by HalidOdat** [comment]
Can also add a badge [like we do with discord](https://github.com/boa-dev/boa/blob/main/README.md?plain=1#L20), the `img.shields.io` that is used to render the badges supports matrix <https://shields.io/badges/matrix>
