### ISSUE TITLE
Publish nightly artifacts

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#3910]
Publishing nightly artifacts is useful for platforms such as http://test262.fyi which try to test the latest nightly instead of the latest stable version. We should offer something for them so that they don't need to compile the full engine just to run tests.

**Comment by jasonwilliams** [comment]
Looks like we can create a `nightly` release tag and set up an action to keep replacing the artifacts for this release, I will try this:
https://dev.to/derlin/how-to-create-nightly-releases-with-github-actions-fpp
