### ISSUE TITLE
ReferenceError: cannot get uninitialized import `default`

### ISSUE THREAD

**Issue by malezjaa** [boa-dev/boa#3929]
**Describe the bug**
I'm trying to use this example in my project: https://github.com/boa-dev/boa/blob/main/examples/src/bin/module_fetch.rs, and i get error about default export: `error: ReferenceError: cannot get uninitialized import default`. I modified this code a bit to use tokio instead of smol, but i don't think this is an issue.

**Output**
```
Entry { is_file: true, path: Some(".\\playground\\index.ts"), executable: None }
Fetching `https://esm.run/yaml@2.3.4`...
Fetching `https://esm.run/array-from-async@3.0.0`...
Fetching `https://esm.run/js-base64@3.7.6`...
Finished fetching `https://esm.run/yaml@2.3.4`
Finished fetching `https://esm.run/array-from-async@3.0.0`
Finished fetching `https://esm.run/js-base64@3.7.6`
error: Object(("boa_engine::builtins::error::ErrorObject") 0x2728C1070B8)
error: ReferenceError: cannot get uninitialized import `default`
```

**To Reproduce**
https://gist.github.com/malezjaa/db9ea95f8836a96faef2dfc6409785b4

Code i am running
```js
import YAML from 'https://esm.run/yaml@2.3.4';
import fromAsync from 'https://esm.run/array-from-async@3.0.0';
import { Base64 } from 'https://esm.run/js-base64@3.7.6';

const data = `
    object:
    array: ["hello", "world"]
    key: "value"
`;

const object = YAML.parse(data).object;

let result = await fromAsync([
    Promise.resolve(Base64.encode(object.array[0])),
    Promise.resolve(Base64.encode(object.array[1])),
]);

export default result
```

<!-- E.g.:
This JavaScript code reproduces the issue:
```javascript
var a = 10;
a;
```
**Build environment (please complete the following information):**

- OS: Windows
- Version: 10
- Rustc version: rustc 1.79.0 (129f3b996 2024-06-10)

**Comment by jedel1043** [comment]
Ok, I spent an embarrassingly long time debugging this... until I realised it was as simple as enabling the "annex-b" feature for `boa_engine` 🙃

**Comment by jedel1043** [comment]
Probably another instance of #3877.
