### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by BlueSialia** [boa-dev/boa#4016]
The [CONTRIBUTING.md](https://github.com/boa-dev/boa/blob/main/CONTRIBUTING.md) and [docs/debugging.md](https://github.com/boa-dev/boa/blob/main/docs/debugging.md) files mention a Dockerfile that can be used for easier development/testing of Boa. But there is no Dockerfile in the repo that I could find. Is it maybe accidentally gitignored?

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by BlueSialia** [comment]
To whoever is reading this. Watchout for the comment above. It appears to be some kind of spam.

**Comment by 4yman-0** [comment]
Dockerfile is not `.gitignore`d. It does not exist.

**Comment by jasonwilliams** [comment]
Hey @BlueSialia thanks for pointing this out, we did once use a Dockerfile but haven't for a long time. I guess we removed it but didn't update the documentation, feel free to raise a PR to update the docs
