### ISSUE TITLE
Perf: replace `js_str!` with `js_string!` where argument is to be converted to `JsString` to reduce heap allocation

### ISSUE THREAD

**Issue by CrazyboyQCD** [boa-dev/boa#4024]
Examples: `Into<PropertyKey>`, `Into<JsValue>`.
Need to change some API like [`get_option`](https://github.com/boa-dev/boa/blob/e22a703dfd7591ccfd143e1e7ade4c2d2ba55b55/core/engine/src/builtins/options.rs#L51-L68).

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
