### ISSUE TITLE
Add CI for WASM

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#408]
We have no checks whatsoever to make sure that the webassembly target is building properly. We should use [`wasm-pack`](https://crates.io/crates/wasm-pack) to at least build it, and maybe to add some tests if it's possible.

**Comment by tomasol** [comment]
Hi, AFAK wasm-pack creates WASM files that can be executed only in a browser or on nodejs. However there are other areas (WASI, interface types) and runtimes like [wasmtime](https://wasmtime.dev/) which are useful for things like plugins.
I've actually succeeded to run `boa` using `wasmtime`, just by creating `.Cargo/config` with following:
```
[build]
target="wasm32-wasi"
```
BTW it produces a warning [1]. The wasm file can be executed:
```
wasmtime target/wasm32-wasi/debug/boa.wasm
```
and works as expected. It would be great if this was tested on CI as well.
[1]: 
```
warning: output filename collision.
The bin target `boa` in package `boa_cli v0.8.0 (boa_cli)` has the same output filename as the lib target `boa` in package `Boa v0.8.0 (boa)`.
Colliding filename is: target/wasm32-wasi/debug/deps/boa.wasm
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```
