### ISSUE TITLE
Default number formatting is not spec compliant

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#413]
**Describe the bug**

Currently we use the default native Rust formatter to format floating-point numbers, which is not spec compliant.

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.

This JavaScript code reproduces the issue:
```javascript
0.0000001
3.e50
```

**Expected behavior**

In this scenario we should get `1e-7` and `3e+50` back.
Actual output is `0.0000001` and `300000000000000000000000000000000000000000000000000`. 

**Build environment (please complete the following information):**
 - OS: Manjaro Linux
 - Target triple: x86_64-unknown-linux-gnu
 - Rustc version: 1.43.1 (8d69840ab 2020-05-04)

**Additional context**

We need to write our own f64 formatter like V8 `DoubleToCString` (see V8 implementation link bellow)

You can find more information:
 - [ECMAScript spec](https://tc39.es/ecma262/#sec-numeric-types-number-tostring)
 - [V8 implementation](https://chromium.googlesource.com/v8/v8/+/refs/heads/master/src/numbers/conversions.cc#938)
 - [V8 Tests](https://chromium.googlesource.com/v8/v8/+/4.3.18/test/mjsunit/number-tostring.js?autodive=0%2F%2F%2F%2F#30)

**Comment by Tropid** [comment]
I can take this if nobody else wants it :)

**Comment by HalidOdat** [comment]
> I can take this if nobody else wants it :)

Sure! Tell us if you need any help, or if you have any questions
