### ISSUE TITLE
Implement `Number` object constants

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#414]
**ECMASCript feature**

Implement `Number` object constants:
 - [ ] `Number.EPSILON`
 - [ ] `Number.MAX_SAFE_INTEGER`
 - [ ] `Number.MIN_SAFE_INTEGER`
 - [ ] `Number.MAX_VALUE`
 - [ ] `Number.MIN_VALUE`
 - [ ] `Number.NEGATIVE_INFINITY`
 - [ ] `Number.POSITIVE_INFINITY`
 - [ ] `Number.NaN`

This should be very straightforward, to see how we implement constants on objects check [`Math`][math-implementation] object.

For more information check:
 - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)
 - [ECMAScript](https://tc39.es/ecma262/#sec-number-object)

[math-implementation]: https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/math/mod.rs#L509

**Comment by Lan2u** [comment]
I'll have a go at this :)

**Comment by HalidOdat** [comment]
> I'll have a go at this :)

Go for it! If you need any assistance just tell us. :)
