### ISSUE TITLE
Cannot access builtins constants if make_constructor_fn used in create()

### ISSUE THREAD

**Issue by Lan2u** [boa-dev/boa#417]
**Describe the bug**
In relation to issue #414 I added number constants using
```rust
pub fn create(global: &Value) -> Value {
    let number = Value::new_object(Some(global));
    number.set_internal_slot("NumberData", Value::from(0));

    // Constant added
    number.set_field_slice("EPSILON", Value::from(f64::EPSILON));
    number.set_field_slice("MAX_VALUE", Value::from(1.79E+308));

    make_builtin_fn!(to_exponential, named "toExponential", with length 1, of number);
    make_builtin_fn!(to_fixed, named "toFixed", with length 1, of number);
    make_builtin_fn!(to_locale_string, named "toLocaleString", of number);
    make_builtin_fn!(to_precision, named "toPrecision", with length 1, of number);
    make_builtin_fn!(to_string, named "toString", with length 1, of number);
    make_builtin_fn!(value_of, named "valueOf", of number);

    make_constructor_fn(make_number, global, number)

    // number
};
```

However the following minimal test fails:

```rust
#[test]
fn epsilon_constant_test() {
    let realm = Realm::create();
    let mut engine = Executor::new(realm);
    
    let num = forward_val(&mut engine, "Number.EPSILON").unwrap();

    assert!(!num.is_null_or_undefined());
}
```

This test however passes:
```rust
#[test]
fn epsilon_constant_test_prototype() {
    let realm = Realm::create();
    let mut engine = Executor::new(realm);
    
    let num = forward_val(&mut engine, "Number.prototype.EPSILON").unwrap();

    assert!(!num.is_null_or_undefined());
}
```

I expected the first test to pass because Number.EPSILON should be valid javascript.

**Build environment (please complete the following information):**
 - OS: Windows 10
 - Version: 1909
 - Target triple: i686-pc-windows-msvc
 - Rustc version: 1.43.1 (8d69840ab 2020-05-04)

**Comment by Lan2u** [comment]
If the create() method of number is modified to instead return number rather than the result of make_constructor_fn then the first test passes and the second test fails (the expected behaviour).

`
/// Create a new `Number` object
pub fn create(global: &Value) -> Value {
    let number = Value::new_object(Some(global));
    number.set_internal_slot("NumberData", Value::from(0));

    number.set_field_slice("EPSILON", Value::from(f64::EPSILON));
    number.set_field_slice("MAX_VALUE", Value::from(1.79E+308));

    make_builtin_fn!(to_exponential, named "toExponential", with length 1, of number);
    make_builtin_fn!(to_fixed, named "toFixed", with length 1, of number);
    make_builtin_fn!(to_locale_string, named "toLocaleString", of number);
    make_builtin_fn!(to_precision, named "toPrecision", with length 1, of number);
    make_builtin_fn!(to_string, named "toString", with length 1, of number);
    make_builtin_fn!(value_of, named "valueOf", of number);

    // make_constructor_fn(make_number, global, number)

    number
}
`

**Comment by Lan2u** [comment]
The following also produces the expected result:

`
/// Create a new `Number` object
pub fn create(global: &Value) -> Value {
    let number = Value::new_object(Some(global));
    number.set_internal_slot("NumberData", Value::from(0));

    number.set_field_slice("EPSILON", Value::from(f64::EPSILON));
    number.set_field_slice("MAX_VALUE", Value::from(1.79E+308));

    make_builtin_fn!(to_exponential, named "toExponential", with length 1, of number);
    make_builtin_fn!(to_fixed, named "toFixed", with length 1, of number);
    make_builtin_fn!(to_locale_string, named "toLocaleString", of number);
    make_builtin_fn!(to_precision, named "toPrecision", with length 1, of number);
    make_builtin_fn!(to_string, named "toString", with length 1, of number);
    make_builtin_fn!(value_of, named "valueOf", of number);

    make_constructor_fn(make_number, global, number.clone());

    number
}

`

**Comment by HalidOdat** [comment]
```
pub fn create(global: &Value) -> Value {
    let number = Value::new_object(Some(global)); // <<<---- The `number` variable is the prototype (should rename to prototype)
    number.set_internal_slot("NumberData", Value::from(0));

    // Constant added
    number.set_field_slice("EPSILON", Value::from(f64::EPSILON)); // <<<---- Here your adding to the prototype, not Number object
    number.set_field_slice("MAX_VALUE", Value::from(1.79E+308));  // Here too.

    make_builtin_fn!(to_exponential, named "toExponential", with length 1, of number);
    make_builtin_fn!(to_fixed, named "toFixed", with length 1, of number);
    make_builtin_fn!(to_locale_string, named "toLocaleString", of number);
    make_builtin_fn!(to_precision, named "toPrecision", with length 1, of number);
    make_builtin_fn!(to_string, named "toString", with length 1, of number);
    make_builtin_fn!(value_of, named "valueOf", of number);

    make_constructor_fn(make_number, global, number) // <<<---- Here we create the `Number` object and we put inside it the prototype.

    number // <<<--- we return `Number` object here.
};
```
**It should be**:
```rust
pub fn create(global: &Value) -> Value {
    let prototype = Value::new_object(Some(global));
    prototype.set_internal_slot("NumberData", Value::from(0));

    make_builtin_fn!(to_exponential, named "toExponential", with length 1, of prototype);
    make_builtin_fn!(to_fixed, named "toFixed", with length 1, of prototype);
    make_builtin_fn!(to_locale_string, named "toLocaleString", of prototype);
    make_builtin_fn!(to_precision, named "toPrecision", with length 1, of prototype);
    make_builtin_fn!(to_string, named "toString", with length 1, of prototype);
    make_builtin_fn!(value_of, named "valueOf", of prototype);

    let number = make_constructor_fn(make_number, global, prototype);

	number.set_field_slice("EPSILON", Value::from(f64::EPSILON));
	number.set_field_slice("MAX_VALUE", Value::from(1.79E+308));

    number
};
```

**Comment by Lan2u** [comment]
Ah ok makes sense.
