### ISSUE TITLE
`NaN` is lexed as a number, not as an identifier

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#421]
**Describe the bug**
In #397, we modified `NaN` to be lexed as a number, and not as an identifier. This fixed the most common case of using `NaN`, that wouldn't work before, but it won't work for `Number.NaN`, among others.

**To Reproduce**
This now fails:

```javascript
Number.NaN;
```

**Expected behavior**
This should produce `NaN`, since it's almost the same case, but it produces a parsing error.

**Additional context**
We will need to add the associated constant to the "Global" object and to the "Number" for this to work, and make sure that an identifier in the global scope tries to access the constant in the global object.

**Comment by LuoZijun** [comment]
https://www.ecma-international.org/ecma-262/10.0/#sec-value-properties-of-the-global-object

`Infinity`, `NaN` and `undefined` are global property, not a number token.

**Comment by croraf** [comment]
Thanks @LuoZijun . Yes we proceeded to implement it like this as you check in the linked PR. Although I didn't know "undefined" is the same. I thought "undefined" is a reserved keyword, but now I see it is same as NaN.
