### ISSUE TITLE
[Feature Request] - Create benchmark for Array manipulation

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#428]
In order to test the upcoming [optimisation](https://github.com/boa-dev/boa/pull/419) work we're doing around objects it would be good to have a benchmark for Arrays and manipulating them.

## Example
Benchmarks live [here](https://github.com/boa-dev/boa/tree/master/boa/benches)
an array creation and access would be categorised under `exec`.

If exec benchmarks become too big we can compartmentalise them later on.

You can see the fibonacci benchmark here:
https://github.com/boa-dev/boa/blob/master/boa/benches/exec.rs#L49-L66

2 benchmarks could be made, 1 for accessing a value from an array, another for creating an array.
We could introduce more benchmarks here for various methods commonly used on arrays

in order to run the benchmarks you can run `cargo bench` in the root folder

## Contributing
https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md
https://github.com/boa-dev/boa/blob/master/docs/debugging.md

**Comment by abhijeetbhagat** [comment]
I can take this up.
