### ISSUE TITLE
Optimize type comparisons

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#435]
**Current situation**
Currently, if the interpreter wants to know what type a value is, it has to call `get_type()`, which returns a `&str`, and compare it to another `&str`. This takes a pretty log time.

It would be much faster to just compare values in an enumeration, which should be at most 1-word size, and can therefore be stored in the stack easily.

We sill need the `&str` version of the type, though, since for example, the `typeof` operator needs to display it. I think the best option would be for the `Type` enum to implement a function called `as_str()` so that we can get the `&str` value if needed.

So, the idea is to have a `Type` enum, that is returned by the `get_type()` function [here][get_type], and then, that enum to have an `as_str()` function with a similar code to the current function.

[get_type]: https://github.com/boa-dev/boa/blob/82908dfdf457a1e21922bf6684bc77bbe8132423/boa/src/builtins/value/mod.rs#L766-L783

**Comment by Lan2u** [comment]
I'll give this a go
