### ISSUE TITLE
Implement break handling in switch statements

### ISSUE THREAD

**Issue by Lan2u** [boa-dev/boa#439]
Currently, the Switch Executable implementation [at](https://github.com/boa-dev/boa/blob/7733da27c7b4c2b766b67cd2eab41afbb2f8f08e/boa/src/exec/switch/mod.rs#L8-L29) doesn't support break statements as part of a switch statement.

**Example code**
```javascript
let a = "A";
let b = "B";
let c = "hi";
switch (c) {
    case 'hi':
        a = 'hi';
        break;
    case 'hi':
        b = 'hi';
        break;
}
console.log(a);
console.log(b);
```
The expected output is:
'hi'
'B'

Note that the code above won't work until issue #301 is also resolved.

**Comment by Lan2u** [comment]
I can do this as an extension to PR #422

**Comment by Razican** [comment]
> I can do this as an extension to PR #422

Sure, go ahead!
