### ISSUE TITLE
Calling undefined function should throw meaningful exception

### ISSUE THREAD

**Issue by tomasol** [boa-dev/boa#448]
Calling function that was not defined throws `undefined` instead of proper error.

**To Reproduce**
Start CLI, enter
```javascript
notdefinedyet();
```
Response: `undefined`. I checked with try-catch that this is an exception, not returned value.
**Expected behavior**
NodeJS responds with 
```
Thrown:
ReferenceError: notdefinedyet is not defined
```
Chrome:
```
Uncaught ReferenceError: notdefinedyet is not defined
    at <anonymous>:1:1
```
**Build environment (please complete the following information):**
- boa version: master (87aea64c)
 - OS: Ubuntu 
 - Version: 20.04
 - Target triple: x86_64-unknown-linux-gnu
 - Rustc version:  1.43.1 (8d69840ab 2020-05-04)

**Comment by jasonwilliams** [comment]
Thanks for raising this @tomasol 
Will take a look at this bug although i assume it will be encompassed by our work to look into handling errors in general

**Comment by Razican** [comment]
Closing this, as this is related to both functions and identifiers, as stated in #463. This is being worked on in #488.
