### ISSUE TITLE
[runtime] script evaluation should return the value of last Statement that returns value

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#457]
**Describe the bug**
https://tc39.es/ecma262/#sec-block-runtime-semantics-evaluation with focus on NOTE 2

**To Reproduce**
```js
1;
const a = function () {};
```

**Expected behavior**
Should return 1. Instead undefined is returned.

**Comment by jasonwilliams** [comment]
This isn't really a bug, it should output nothing.
If you run this in Node you won't get `1` as an output either.

**Comment by croraf** [comment]
https://repl.it/@croraf/ImpoliteQualifiedRobodoc @jasonwilliams

**Comment by jasonwilliams** [comment]
Thanks for that, I don’t get that locally for some reason.
Is this something you wanted to look at @croraf ?

**Comment by jedel1043** [comment]
Maybe related to #1544

**Comment by raskad** [comment]
This has been fixed for a while. The example now returs the expected `1`.
