### ISSUE TITLE
Possibly use something like rustyline for the cli

### ISSUE THREAD

**Issue by IovoslavIovchev** [boa-dev/boa#464]
[rustyline](https://crates.io/crates/rustyline/) offers some niceties out of the box (history, vi mode, etc.), which would improve the experience when using the boa-cli.

Note that this issue is not about adding `rustyline` specifically but rather about adding features that crates like `rustyline` (and possibly others) already offer and would be nice to have.

**Comment by IovoslavIovchev** [comment]
I can take a look into adding `rustyline` if there are no other suggestions.

**Comment by HalidOdat** [comment]
> I can take a look into adding `rustyline` if there are no other suggestions.

Awesome! as an example use of `rustyline` you can check https://github.com/PaddiM8/kalk

**Comment by HalidOdat** [comment]
Cloasing this issue.
