### ISSUE TITLE
Use ECMAScript syntax for regular expressions

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#478]
**Current situation**
Currently, we use regular expressions from the `regex` crate. They are extremely fast, but they don't support the full ECMAScript syntax like backreferences or lookaround assertions.

**Solution**
We should use a library that does support all this syntax. A nice library that was just released and seems to support this is [`regress`](https://crates.io/crates/regress).

We should remove our dependency on `regex` and use `regress`, and see how the performance gets affected.

**Comment by neeldug** [comment]
Hi!
I've currently looked over the regress API, and it seems to be missing quite a few methods that are necessary, any suggestions on whether to proceed trying to implement regress?

**Comment by Razican** [comment]
One option would be to implement those methods in regress. What would we need?

**Comment by neeldug** [comment]
Specifically I've been looking into regress's API and it actually does have a lot of the methods just labelled differently or structured differently, currently working on trying to refactor everything involving regex into regress atm.

**Comment by neeldug** [comment]
Have been working on refactoring regexp and string, and managed to finish string, however, am a little stuck on the regexp regex implementations, especially with working with the capture groups that regress has got strange methods, if anyone is able to help, would be much appreciated.

**Comment by Razican** [comment]
> Have been working on refactoring regexp and string, and managed to finish string, however, am a little stuck on the regexp regex implementations, especially with working with the capture groups that regress has got strange methods, if anyone is able to help, would be much appreciated.

Hey, do you have the code you are working on? Maybe create a draft PR so that we can give you feedback :)
