### ISSUE TITLE
Implement global `undefined` property

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#481]
**ECMASCript feature**

`undefined` is not a keyword, but a global property.

We can add this by adding a new module like `NaN` https://github.com/boa-dev/boa/tree/master/boa/src/builtins/nan and then adding it to the builtin `init` function in `builtins/mod.rs` the value it should contain should be `Value::undefined()`

More information
	- [ECMAScript reference][spec]
    - [MDN][mdn]

[spec]: https://tc39.es/ecma262/#sec-undefined
[mdn]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined

**Comment by AnirudhKonduru** [comment]
@HalidOdat , I could use some help with testing this. Doing it like NaN is tested won't do much, as 
`
let scenario = r#"
        undeclared_identifier; //or undefined;
        "#;
` 
will always evaluate to `undefined`, even when we don't add undefined as a global property.

**Comment by Razican** [comment]
> @HalidOdat , I could use some help with testing this. Doing it like NaN is tested won't do much, as 
> ```rust
> let scenario = r#"
>         undeclared_identifier; //or undefined;
>         "#;
> ```
> will always evaluate to `undefined`, even when we don't add undefined as a global property. 

Yes, this is a bug we have, where we don't throw a `ReferenceError` exception. This should be solved once #488 gets merged, though.

**Comment by croraf** [comment]
@AnirudhKonduru You can join discord https://github.com/boa-dev/boa#communication. It is much easier to communicate details there :)
