### ISSUE TITLE
Field access should propagate the exception (`Err(_)`)

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#482]
When `ToObject` (`to_object`) throws an error the field accessors don't propagate the error in `GetConstField` and `GetField` nodes

GetConstField: <https://github.com/boa-dev/boa/blob/master/boa/src/exec/field/mod.rs#L12-L13>
GetField: <https://github.com/boa-dev/boa/blob/master/boa/src/exec/field/mod.rs#L25-L26>

To fix this we should change from `.expect("failed to convert to object")` to `?`  try operator.

**Comment by neeldug** [comment]
Hi,

Would like to work on this issue.

Thanks
