### ISSUE TITLE
`ToObject` (`to_object`) should throw `TypeError` when there is `null` and `undefined`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#483]
**Describe the bug**

The problem is that when we try to convert `null` and `undefined` we throw `undefined` this is wrong.

The bug is here: <https://github.com/boa-dev/boa/blob/master/boa/src/exec/mod.rs#L384-L386>
See conversion table for `to_object`: <https://tc39.es/ecma262/#sec-toobject>

To fix this we need to throw a type error with the `Interpreter::throw_type_error()` method the message should be something like `"cannot convert 'null' or 'undefined' to object"`

**Comment by zanayr** [comment]
I'd like to take this one on. :)
