### ISSUE TITLE
`ToObject` (`to_object`) throw `undefined` when converting `ValueData::Integer` to `Number` object

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#484]
**Describe the bug**

The bug is here: <https://github.com/boa-dev/boa/blob/master/boa/src/exec/mod.rs#L384>. When the `ValueData` is `Integer` it returns `Err(undefined)` this is wrong. 

We should have the same logic as the `Rational` case: <https://github.com/boa-dev/boa/blob/master/boa/src/exec/mod.rs#L398-L407>.

**Comment by gvasquez11** [comment]
Hello I would be glad to take this issue :)

**Comment by HalidOdat** [comment]
> Hello I would be glad to take this issue :)

Go for it! Tell us if you have any questions or need some help :)
