### ISSUE TITLE
[try/catch] not returning correct value

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#496]
**Describe the bug**
```js
try {
  a
} catch (err) {
  'asd'
}
```

should return `"asd"`. Instead `undefined` is returned.

**Comment by croraf** [comment]
OK. This will work when #488 will be applied. On master it does not enter the catch block, so it just return `a` which is undefined.

**Comment by Razican** [comment]
I would keep it open until #488 is merged in master.
