### ISSUE TITLE
Regular expression flags should be checked at runtime, not at lexing time

### ISSUE THREAD

**Issue by LuoZijun** [boa-dev/boa#503]
CodeLine: https://github.com/boa-dev/boa/blob/e674da46e720225663be79357703511dd4a54695/boa/src/syntax/ast/token.rs#L109-L116

11.8.5 Regular Expression Literals: https://www.ecma-international.org/ecma-262/10.0/#sec-literals-regular-expression-literals

The ECMAScript spec said, `RegularExpressionFlags` is empty or `IdentifierPart`.

**Comment by LuoZijun** [comment]
The runtime defined flags: g, i, m, s, u, y

[MDN] Advanced searching with flags: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Advanced_searching_with_flags_2

**Comment by Razican** [comment]
Hi @LuoZijun could you explain a bit the issue you found? We are generating the regular expression flags as per the spec, right?

**Comment by LuoZijun** [comment]
@Razican I mean the invalid `invalid regular expression flag` error should be decided by Runtime. Not Lexer.

**Comment by Razican** [comment]
After reviewing the specification, I can see that the only static error that this should throw should be in case we find a unicode scape sequence in the flags:
https://www.ecma-international.org/ecma-262/10.0/#sec-literals-regular-expression-literals-static-semantics-early-errors

But then, on runtime, we get the Syntax Error:
https://www.ecma-international.org/ecma-262/10.0/#sec-regexpinitialize

The thing is that this would prevent some optimizations, and I can see that both V8 and Spidermonkey throw a syntax error statically, before running the code.

I tried this code to test it:
```javascript
function a() {
	return /abc/abc;
}
```

Note that this throws a Syntax Error even if it's not being executed.

In any case, is there a particular situation where this is causing pain? Do you have an example situation where this is behaving diferently to common browsers? Or any particular situation where this could be an issue?

**Comment by Razican** [comment]
There are some early errors that must be taken into account: https://262.ecma-international.org/10.0/#sec-primary-expression-regular-expression-literals-static-semantics-early-errors

**Comment by Razican** [comment]
After checking this thoroughly and following the Test262 suite, it turns out that these flags must be checked at parsing time (early error) and not at runtime, so I'm closing this issue.
