### ISSUE TITLE
`ReferenceError` on cli prints full obj properties instead of short message

### ISSUE THREAD

**Issue by AnirudhKonduru** [boa-dev/boa#507]
On the cli, simply running `ReferenceError`, `console`, `console.log` and many other global objects/functions prints the full object and its properties of what the script returns instead of a short message like `function: ReferenceError` or `global object: console`. 

### to reproduce
Run `console`, `console.log`, `ReferenceError` on the cli

**Expected behavior**
Print a shorter description like `function: ReferenceError` or `global object: console`

The spec define not defineewhat to /how to print what the script returns.

**Build environment (please complete the following information):**
 - OS: [Windows10]
 - Version: [e.g. 64]
 - Target triple: [x86_64-uwp-windows-msvc]
 - Rustc version: [rustc 1.44.0 (49cae5576 2020-06-01)]

**Comment by HalidOdat** [comment]
We should discus how we should print the objects and errors (uncaught errors) we are not bound by the spec so we can print whatever we want!

I would like for objects to be printed all objects (not `Error`s): `ObjectName { MaybeValueOrEmpty }`, for example:
```js
new String("Hello") // => String { "Hello" }
new Boolean(true) // => Boolean { true }
```

For errors like type error, like `TypeError`
```js
new TypeError(msg) // => Uncaught TypeError: msg (maybe in red)
throw "Hello"; // =>  Uncaught "Hello" (this is how node REPL does it)
```

**Comment by HalidOdat** [comment]
Additionally we cold have a flag for displaying all the object properties like we do now for debugging purposes.

**Comment by AnirudhKonduru** [comment]
Sound great to me. Perhaps for uncaught Errors we could print the stack trace also? (maybe just 2-3 levels of it on the cli for brevity).
