### ISSUE TITLE
Assignment with invalid LHS does not throw SyntaxError

### ISSUE THREAD

**Issue by AnirudhKonduru** [boa-dev/boa#508]
Assignments with invalid left-hand side(`1=2`) return the value of the right-hand side(`2`) instead of throwing SyntaxError.

## To Reproduce
This JavaScript code reproduces the issue:
```javascript
1=2 # should throw SyntaxError
```
-->

## Expected behavior

The spec for the expected behaviour can be found in the [ECMAScript specification][spec].

[spec]: https://tc39.es/ecma262/#sec-assignment-operators-static-semantics-early-errors

**Comment by Lan2u** [comment]
Fixed by #559
