### ISSUE TITLE
[Call] calling an undefined method does not throw

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#510]
**To Reproduce**
```js
'bar'.foo()
```
or
```js
let bar = {}
bar.foo()
```

**Expected behavior**
Should throw TypeError 
`TypeError: 'bar'.foo is not a function`
`TypeError: bar.foo is not a function`

Instead `undefined` is returned.

**Comment by HalidOdat** [comment]
Could #501 fix this issue?

**Comment by croraf** [comment]
Negative.
