### ISSUE TITLE
[Call] Usage of "this" in methods is not supported

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#511]
**Describe the bug**
```js
const foo = {
  a: 3,
  bar: function () {return this.a + 5}
};

foo.bar()
```

should return 8. Instead `thread 'main' panicked at 'Reference Error: Unitialised binding for this function', boa/src/environment/function_environment_record.rs:115:17` happens

**Comment by jasonwilliams** [comment]
Looks like the binding status is defauting to uninitialized, changing to initialized will work https://github.com/boa-dev/boa/blob/master/boa/src/builtins/function/mod.rs#L196 but we probably want to pass that value in, as we don't know at that point whether we're in an arrow function or not

**Comment by jasonwilliams** [comment]
There's a fix for this in https://github.com/boa-dev/boa/pull/526
