### ISSUE TITLE
Implement `Object.is()` method

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#513]
**ECMASCript feature**
Implement the `Object.is()` method, the `is` method uses the `SameValue` algorithm (implementation is [here](https://github.com/boa-dev/boa/blob/a7cffe3c7c/boa/src/builtins/value/equality.rs#L144))

The builtin Object functions are [here](https://github.com/boa-dev/boa/blob/a7cffe3c7c/boa/src/builtins/object/mod.rs#L410-L494), after implementing it should be added to `Object` [here](https://github.com/boa-dev/boa/blob/a7cffe3c7c/boa/src/builtins/object/mod.rs#L513) like `defineProperty`

**Example code**

```javascript
Object.is('foo', 'foo');     // true

Object.is('foo', 'bar');     // false
Object.is([], []);           // false

var foo = { a: 1 };
var bar = { a: 1 };
Object.is(foo, foo);         // true
Object.is(foo, bar);         // false

Object.is(null, null);       // true

// Special Cases
Object.is(0, -0);            // false
Object.is(-0, -0);           // true
Object.is(NaN, 0/0);         // true
```

More information:
 - [ECMAScript Specification](https://tc39.es/ecma262/#sec-object.is)
 - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is)

**Comment by tylermorten** [comment]
I could probably tackle this one. Do we need it to work in “strict” mode as well?
