### ISSUE TITLE
Cleanup `Math` methods

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#514]
Many of the Math builtin functions are a bit convoluted for example:
```rust
pub(crate) fn abs(_: &Value, args: &[Value], _: &mut Interpreter) -> ResultValue {
    Ok(Value::from(if args.is_empty() {
       f64::NAN
    } else {
        f64::from(args.get(0).expect("Could not get argument")).abs()
    }))
}
```
This is also inefficient because we check if there is an argument and then another check is done when we call `.expect()`.

A better way of doing this would be to use `.map_or` which would simplify the code a lot:
```rust
pub(crate) fn abs(_: &Value, args: &[Value], _: &mut Interpreter) -> ResultValue {
	Ok(args.get(0).map_or(f64::NAN, |x| f64::from(x).abs()).into())
}
```

**Comment by n14little** [comment]
I’ll take this

**Comment by HalidOdat** [comment]
> I’ll take this

Sure!

**Comment by n14little** [comment]
@HalidOdat  There are still some methods that can be cleaned up in this issue. I just did the ones that were quick and easy.

**Comment by HalidOdat** [comment]
> @HalidOdat There are still some methods that can be cleaned up in this issue. I just did the ones that were quick and easy.

In that case, I'll reopen the issue :)

**Comment by pedropaulosuzuki** [comment]
In that case, we might benefit from mapping which methods still need refactoring:

- [ ] Math.abs()
- [ ] Math.acos()
- [ ] Math.acosh()
- [ ] Math.asin()
- [ ] Math.asinh()
- [ ] Math.atan()
- [ ] Math.atan2()
- [ ] Math.atanh()
- [ ] Math.cbrt()
- [ ] Math.ceil()
- [ ] Math.clz32()
- [ ] Math.cos()
- [ ] Math.cosh()
- [ ] Math.exp()
- [ ] Math.expm1()
- [ ] Math.floor()
- [ ] Math.fround()
- [ ] Math.hypot()
- [ ] Math.imul()
- [ ] Math.log()
- [ ] Math.log10()
- [ ] Math.log1p()
- [ ] Math.log2()
- [ ] Math.max()
- [ ] Math.min()
- [ ] Math.pow()
- [ ] Math.random()
- [ ] Math.round()
- [ ] Math.sign()
- [ ] Math.sin()
- [ ] Math.sinh()
- [ ] Math.sqrt()
- [ ] Math.tan()
- [ ] Math.tanh()
- [ ] Math.trunc()

**Comment by n14little** [comment]
There are a couple of these functions that are not yet implemented. Are there separate issues tracking the implementation of those functions?

**Comment by HalidOdat** [comment]
> There are a couple of these functions that are not yet implemented. Are there separate issues tracking the implementation of those functions?

we don't have an issue for tracking the unimplemented ones. I'll create it :)
