### ISSUE TITLE
Implement the rest of `Math` methods

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#524]
Implement `Math` methods:
 - [x] `Math.clz32()`
 - [x] `Math.expm1()`
 - [x] `Math.fround()`
 - [x] `Math.hypot()`
 - [x] `Math.log1p()`
 - [x] `Math.imul()`

**Comment by mr-rodgers** [comment]
Hey, I'm new, but I would like to take these.

**Comment by HalidOdat** [comment]
> Hey, I'm new, but I would like to take these.

Sure. go for it! If you have any questions or any need assistance just ask :)

**Comment by HalidOdat** [comment]
@mr-rodgers a good example of a `Math` method is `abs`: <https://github.com/boa-dev/boa/blob/master/boa/src/builtins/math/mod.rs#L43-L45>

after we create the methods we need to register them here like `abs`: <https://github.com/boa-dev/boa/blob/master/boa/src/builtins/math/mod.rs#L478>

**Comment by pedropaulosuzuki** [comment]
I think we missed Math.imul(a: f64, b:f64) -> i32;

**Comment by HalidOdat** [comment]
> I think we missed Math.imul(a: f64, b:f64) -> i32;

Good catch! I'll add it to the list :)

**Comment by mr-rodgers** [comment]
Do we have a guide for writing tests?

**Comment by HalidOdat** [comment]
> Do we have a guide for writing tests?

Not really. we really should have one, but for now here is an example of how we test `abs`: https://github.com/boa-dev/boa/blob/master/boa/src/builtins/math/tests.rs#L6-L22

Also the Math tests should go in in this file

Hope this helps.

**Comment by mr-rodgers** [comment]
> > Do we have a guide for writing tests?
> 
> Not really. we really should have one [...]

Maybe this is something I can help with?

**Comment by HalidOdat** [comment]
> Maybe this is something I can help with?

Yes. It would be awesome to have it for newcomers to the project :)
