### ISSUE TITLE
[exec - Call] handling GetField and GetConstantField seems superfluous

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#530]
https://github.com/boa-dev/boa/blob/8b40e9eec2c190f8df7cde6713c7fe44e2564756/boa/src/exec/expression/mod.rs#L16-L34
It can be seen that some expressions are handled differently.

**Code of type `expression ()` should be handled in the same way irrespective of the `expression` involved.**

Additional data (research):
If `GetConstField` branch of the `match` is removed only built in object methods seem to fail. Which could indicate erroneous handling of the built in objects.
if `GetField` branch of the `match` is removed nothing fails, but this is due to lack of tests of the form `built_in_object['built_in_method'])`. If these tests are added they fail.

**Comment by croraf** [comment]
When these match branches are removed the following example fails (with and without parentheses around the `many['findIndex']`):

```js
function comp(item) {
  return item === 2;
}
var many = [1, 2, 3];

(many['findIndex'])(comp);
```

returning -1 instead of 1

**Comment by Razican** [comment]
Hi, I'm not sure on what are we talking about. I would prefer if you could explain the issue with the issue template we provided.

**Comment by croraf** [comment]
It is not actually a bug. It is a suspicious code (code optimization), if you have that label you can change.

**Comment by croraf** [comment]
I updated the original ticket. Hopefully it is more clear now. We also had some in depth discussion on the discord.

**Comment by RageKnify** [comment]
@croraf could you review whether this issue still exists?
I ran the following code in `master` and seems to work fine:
```js
let a = [0, 1, 2]
(a.pop)()    // 2
(a['pop'])() // 1
```

Can you give a JS code example that fails?

**Comment by croraf** [comment]
(I don't think I'll have time in the following days to review it)

**Comment by croraf** [comment]
Please check the previous messages. There was no bug happening. This is an optimization suggestion task.

**Comment by RageKnify** [comment]
You want `GetConstField` and `GetField` to be handled equally by `Call`?
I don't see why we would want to do that, we would need to dumb down `GetConstField`, one of the big reasons for using it is that it provides faster access since the field doesn't need to be computed.

**Comment by Razican** [comment]
I'm closing this issue, since the optimization seems to have its point, and it's unclear to me what we are supposed to fix/improve here.
