### ISSUE TITLE
[builtins] Builtin function doesnt have constructor property

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#531]
**To Reproduce**
`[].findIndex.constructor` 

**Expected behavior**
Should return a `Function` constructor. Instead `undefined` is returned.

Custom functions do have `constructor` property which returns correctly.

**Comment by 54k1** [comment]
I think [make_builtin_fn](https://github.com/54k1/boa/blob/master/boa/src/builtins/function/mod.rs#L516) should take even global as parameter (apart from parent), just like [make_constructor_fn](https://github.com/54k1/boa/blob/master/boa/src/builtins/function/mod.rs#L450). Then, we can set the constructor field as "Function" of the builtin which is fetched from the global object. Then the signature would change to the following:

```Rust
pub fn make_builtin_fn<N>(function: NativeFunctionData, name: N, parent: &Value, length: usize, global: &Value)
where
    N: Into<String> {
    ...
    let mut function = Object::function(Function::builtin(Vec::new(), function), Value::null());
    let constructor = Object::function(function, global.get_field("Function"));
    function.insert_property("constructor", Property::data_descriptor(constructor.into(),
        Attribute::READONLY | Attribute::NON_ENUMERABLE | Attribute::PERMANENT));
    ...
}
```
Any thoughts about this?

**Comment by HalidOdat** [comment]
> I think [make_builtin_fn](https://github.com/54k1/boa/blob/master/boa/src/builtins/function/mod.rs?rgh-link-date=2020-08-06T12%3A34%3A10Z#L516) should take even global as parameter (apart from parent), just like [make_constructor_fn](https://github.com/54k1/boa/blob/master/boa/src/builtins/function/mod.rs?rgh-link-date=2020-08-06T12%3A34%3A10Z#L450). Then, we can set the constructor field as "Function" (fetched from global).

Yes. this is good solution, maybe we should accept an `Interpreter` so we have more control and we can call `Interpreter::global()` which return the global object. Accepting `Interpreter` can make it easier to implement caching in the future for common objects like `Object`, `Array`, `Function` and there prototypes instead of doing it through `.get_field`.

@54k1 should I assign you to this issue?

**Comment by 54k1** [comment]
Yes, that would be a good solution to take Interpreter as the parameter. Thanks for pointing it out.
I was however just checking the specification of [Function instances](https://tc39.es/ecma262/#sec-function-instances). It does not mention anything about the "constructor" field. Is it something left to the implementation?

Sure, I can take this up.

**Comment by HalidOdat** [comment]
> I was however just checking the specification of [Function instances](https://tc39.es/ecma262/#sec-function-instances). It does not mention anything about the "constructor" field. Is it something left to the implementation?

Good catch! should have looked at the spec first. What we are trying to do is not spec compliant. the `"constructor"` field is not a part of the function instance, it is from the `Function` `prototype`. So what we need to do is set the prototype (`__proto__`), not the owned property field `"constructor"`. [here](https://github.com/54k1/boa/blob/master/boa/src/builtins/function/mod.rs#L523-L524) there already is a `FIXME` comment on it.

**Comment by 54k1** [comment]
> [].findIndex.constructor This works because properties are searched in the prototype chain.

Thanks for pointing this out.
