### ISSUE TITLE
Lexing and Parsing errors should throw a `SyntaxError`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#539]
**Describe the bug**

**To Reproduce**
Any invalid syntax like `{`.

**Expected behavior**
The expected behavior would be a `SyntaxError` with the parser error.

**Actual behavior**
we get a panic with the message.

**Additional context**
I think the best way to implement this would be to have the lexer and parser, generate the error as we do now but not panic, and in `forward` we check if lexing or parsing failed and then throw a `SyntaxError`, this would eliminate the need to introduce the `Interpreter` to the lexer/parser which would keep the code cleaner.

This is blocked until #536 lands

**Comment by Razican** [comment]
Hmmm this is interesting, where do we panic? I thought we just returned a parsing/lexing error.

**Comment by HalidOdat** [comment]
> Hmmm this is interesting, where do we panic? I thought we just returned a parsing/lexing error.

Sorry about that, we don't panic but we print the parsing error and exit <https://github.com/boa-dev/boa/blob/master/boa/src/lib.rs#L83-L85>

**Comment by Razican** [comment]
> > Hmmm this is interesting, where do we panic? I thought we just returned a parsing/lexing error.
> 
> Sorry about that, we don't panic but we print the parsing error and exit [/boa/src/lib.rs@`master`#L83-L85](https://github.com/boa-dev/boa/blob/master/boa/src/lib.rs?rgh-link-date=2020-07-02T20%3A02%3A52Z#L83-L85)

True, that should throw a Syntax Error :)
