### ISSUE TITLE
Add benchmarks for "uglified" JS

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#564]
Currently, all of our benchmarks take non-uglified JavaScript as input. This is fine for some scenarios, but we should also have benchmarks for "uglified" or "minified" JavaScript.

This usually creates smaller variable and function names, and removes spaces and new lines, which should speed up parsing and even a bit the execution.

**Comment by neeldug** [comment]
I was wondering roughly for the test cases, whether it should have both a regular and uglified test case for comparison, and also roughly how long the test case should be for a reliable and significant benchmark?

**Comment by Razican** [comment]
> I was wondering roughly for the test cases, whether it should have both a regular and uglified test case for comparison, and also roughly how long the test case should be for a reliable and significant benchmark?

It shouldn't be too long. With a small benchmark we should have enough information, since we do a statistical analysis. As far as I can see in the PR, I think that should be enough.
