### ISSUE TITLE
Expose API to Deno

### ISSUE THREAD

**Issue by littledivy** [boa-dev/boa#575]
[Deno](https://deno.land) is another runtime for JS/TS written in Rust similar to Node.js

There is no such JS parser for Deno that can be used as a library. Also, since Deno uses v8 bindings exposing them will not be ideal. I find Boa quite useful for Deno devs who would want to compile JS (just like how `acorn` does on Node.js)

Bindings to Deno can be either provided using [`deno_core`](https://crates.io/crates/deno_core) crate or by compile to WASM. As an example: https://github.com/divy-work/autopilot-deno

If you guys approve, I'll be free to open a PR here!

**Comment by jasonwilliams** [comment]
Related: https://github.com/boa-dev/boa/issues/445

**Comment by jasonwilliams** [comment]
@divy-work sounds like its approved if you wanted to experiment with this

**Comment by jasonwilliams** [comment]
@littledivy are you still interested in doing this?

**Comment by littledivy** [comment]
@jasonwilliams sorry for the late reply, I'm busy with my classes and other projects these days :(

**Comment by RageKnify** [comment]
https://docs.rs/v8/latest/v8/
This is the crate deno uses to interact with V8, I think it would probably be a nice source of inspiration.

**Comment by jedel1043** [comment]
Closing this. Nowadays, there are a lot of other options for parsing, so we don't need to offer an API just for parsing JS from Deno.
