### ISSUE TITLE
Implement for...of syntax for Iterables

### ISSUE THREAD

**Issue by joshwd36** [boa-dev/boa#576]
As more collections are added, it would be useful to implement the `for...of` syntax for Iterables, and adding iterables to the String, Array, and Map types. [ECMAScript specification][spec].

[spec]: https://www.ecma-international.org/ecma-262/10.0/index.html#sec-for-in-and-for-of-statements

This code should now work and give the expected result:
```javascript
let a = [1, 2, 3];
for (i of a) {
    console.log(i);
}
```
The expected output is:
```javascript
1
2
3
```

I'm happy to have a go at this myself, although as this will be my first time adding syntax features, I'm wondering whether I should wait for #559 to land or just go right ahead with the current lexer?

**Comment by Lan2u** [comment]
You could make a branch-based from #559 if you wanted to get started right away, I expect that most of the work regarding this would be in the parser (syntax/parser/statement/iteration) and exec (exec/iteration/mod.rs)

**Comment by dvtkrlbs** [comment]
I can take a look at this

**Comment by joshwd36** [comment]
> I can take a look at this. Does this include the for-in statement too?

I've made a start on it already, but haven't been able to work on it recently. I should have more time this week though so I'll try and finish it then, if not I'm happy to transfer what I've done over to you.

**Comment by jcdickinson** [comment]
Dropping #671 for whoever wants to take this on. See my comments there, as there is a tricky design question. My current thoughts are:

```rust
pub enum IterableForLoopKind {
    In,
    Of
}
struct InnerIterableForLoop {
    kind: IterableForLoopKind,
    variable: SingleVarLetOrConstDecl, // or something
    object: Node,
    body: Node
}
```

Note that #670 would also be closed, as `for..in` is simply a `for..of` with a built-in iterator.
