### ISSUE TITLE
Assignment to non-assignable expression should throw a `SyntaxError`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#588]
**Describe the bug**
Assignment to non-assignable expression should throw a `SyntaxError`.

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.

This JavaScript code reproduces the issue:
```javascript
3 = 5 
```

**Expected behavior**
Explain what you expected to happen, and what is happening instead.

Running this code, should throw a `SyntaxError`.

SpiderMonkey: `SyntaxError: invalid assignment left-hand side`
V8: `Uncaught SyntaxError: Invalid left-hand side in assignment`

instead we get `5`

**Build environment (please complete the following information):**
 - OS: Manjaro Linux
 - Target triple: x86_64-unknown-linux-gnu
 - Rustc version: rustc 1.45.0 (5c1f21c3b 2020-07-13)

**Comment by Lan2u** [comment]
I will have a look at this as part of #559
