### ISSUE TITLE
Division operator parse error pattern

### ISSUE THREAD

**Issue by elasmojs** [boa-dev/boa#605]
Hi

The following code snippet causes a parse error

```js
function radToDeg(rad) {
  return rad / (Math.PI / 180); //parse error here
};
```

**Comment by HalidOdat** [comment]
Hi @elasmojs 

This is a bug related to the lexer, that has been fixed in the `new_lexer` branch :)

**Comment by elasmojs** [comment]
@HalidOdat Thank you for the quick response :)
