### ISSUE TITLE
Rename `Object::prototype()` and `Object::set_prototype()` to `Object::prototype_instance()` and `Object::set_prototype_instance()`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#607]
The `Object::prototype()` returns the prototype instance `__proto__`, so it makes more sense to call it `Object::prototype_instance()`. they are is located [here](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/object/mod.rs#L432-L439)

**Comment by RageKnify** [comment]
I'm gonna take this on and open a PR soon.
