### ISSUE TITLE
Error in RegExp

### ISSUE THREAD

**Issue by elasmojs** [boa-dev/boa#610]
Hi,

The following code snippet works incorrectly for RegExp

```js
let re = /(\w+)\s(\w+)/
let str = 'John Smith'
let newstr = str.replace(re, '$2, $1')
console.log(newstr)
```

Expected: `Smith, John`
Got: `Smith, $1`

thanks

**Comment by HalidOdat** [comment]
Hmmm. This this is probably a bug in `String.prototype.replace`.

**Comment by RageKnify** [comment]
I think I've found the mistake and found the fix, I'll open a PR soon.
