### ISSUE TITLE
Unexpected result in exponentiation assignment

### ISSUE THREAD

**Issue by elasmojs** [boa-dev/boa#614]
Hi

There is an unexpected result in exponentiation assignment
```js
let a = 3;
console.log(a **= 'hello');
```
expected output: `NaN`
got: `1`

thanks

**Comment by HalidOdat** [comment]
This has already been fixed in `master` branch when #520 landed (fixed all operation +, -, &, |, **), I'm assuming you are using version `0.9`, right?

**Comment by HalidOdat** [comment]
Closing this issue since it is fixed :)
