### ISSUE TITLE
Test Project

### ISSUE THREAD

**Issue by elasmojs** [boa-dev/boa#623]
Hi

Created a test project for Boa based on [Mozilla Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference) over here: [Boatest](https://github.com/elasmojs/boatest)

It is not complete but adequate, i think

thanks

**Comment by Razican** [comment]
Hi!
We are currently trying to integrate the official ECMAScript test suite ([test262](https://github.com/tc39/test262)) in #567. Would this be different?

**Comment by elasmojs** [comment]
@Razican Thanks. I was not aware of that, I want to have check of the spread for my own needs. If we have taken up the official test suite that is wonderful! Where can I see the results of the test, if available?

**Comment by Razican** [comment]
> Where can I see the results of the test, if available?

We are still not able to run the test suite, so there are no results yet.
