### ISSUE TITLE
Test Refactoring HashMaps with HashBrown

### ISSUE THREAD

**Issue by neeldug** [boa-dev/boa#655]
Currently, Boa uses `rustc-hash` for all HashMaps, from looking at the documentation, there are no specific benchmarks on this hashing algorithm, and so I propose we test [`hashbrown`](https://docs.rs/crate/hashbrown/0.8.2), which is Rust's port for Google's SwissTable hash map, I figure that if we find any drastic performance benefits, it may be worth considering switching, as `hashbrown` can be used as a drop-in replacement for Rust's STL HashMap Collection. I believe testing this on a branch and viewing the benchmarks may show whether the HashMap implementation is causing a bottleneck.

EDIT: Seems similar to #356 which actually raised using `rustc-hash` for the very same reason, perhaps useful to see which performs better.

**Comment by neeldug** [comment]
@jasonwilliams did some testing which showed that the STL using `ahash` vs `rustc-hash` made negligible performance differences for the most part except for scaling  with `usize` `usize` hashmaps, this made major differences with `ahash` outperforming `rustc-hash` for inserting and deleting large quantities of usize pairs into the hashmap. I believe that unless this operation is common and at large-scale, it's not worth switching.

**Comment by Razican** [comment]
Just to give some extra information here, we are not using the default hashing algorithm, we are using `FXHash`, which is noticeably faster.

**Comment by neeldug** [comment]
Actually, @Razican just wondering whether [these benchmarks](https://github.com/Amanieu/hashbrown#performance), performed a year ago, apply to Boa’s current state, as the benchmarks that I performed were quite naive in implementation due to lack of knowledge and reliability across machines.

**Comment by Razican** [comment]
Feel free to make a PR. If it's more performant, we can replace our implementation :)
