### ISSUE TITLE
Implement `for..in` for objects

### ISSUE THREAD

**Issue by jcdickinson** [boa-dev/boa#670]
**ECMASCript feature**
I would like to see `for..in` syntax and execution implemented. [ECMAScript specification][spec]. This is important for test262, as it uses `for..in` pretty extensively.

**Example code**
```js
const myObject = {
 a: 'test1',
 b: 'test2'
};
let c = '';
for(const prop in myObject) {
 c += prop + '=' + myObject[prop] + ';';
}
c
```

The expected output is `a=test1;b=test2;`.

[spec]: https://www.ecma-international.org/ecma-262/10.0/index.html#sec-for-in-and-for-of-statements

**Comment by tofpie** [comment]
Hi. Could I work on it?

**Comment by jcdickinson** [comment]
> Hi. Could I work on it?

I have no objection. You might want to take a look at my closed PR to see if it applies to the subsequent changes.

If you have a WIP feel free to @ me, I'm somewhat familiar with the architecture.
