### ISSUE TITLE
Last expressions result gets returned from functions when there is no return

### ISSUE THREAD

**Issue by dvtkrlbs** [boa-dev/boa#672]
When non returning functions mutates a property of another object that modified object gets returned even though we dont use the return statement

In the repl
```javascript
>> function x() {}
undefined
>> function y() { x.y = 3 }
undefined
>> x.y
undefined
>> y()
3
```
y() should not return anything

**Comment by RageKnify** [comment]
This can be generalized, it seems that when the last statement in a function is an expression the expression's result is returned rather than undefined.
```js
>> function z() { 0 }
undefined
>> z()
0
```

**Comment by RageKnify** [comment]
Problem is in: https://github.com/boa-dev/boa/blob/be20b65a9e1a2ac6d802f5c8f3f87edd149274eb/boa/src/exec/statement_list.rs
```rust
if i + 1 == self.statements().len() {
     obj = val;
}
```
Regardless of the type of node, the value obtained from running it is used as the return value.

I think `StatementList`s are used elsewhere besides function, if so it might not be as simple as removing these lines....

**Comment by jasonwilliams** [comment]
Seeing that all returns in JavaScript are explicit anyway, I wonder if StatementList can Ok(undefined), it should be safe as any return will change the interpreter state so it wouldn’t get that far. You could return Ok(val) directly from the return state branch in that link @RageKnify posted

**Comment by RageKnify** [comment]
Should have been explicit on my PS, what happened when I tried removing the 3 lines was that the CLI started only returning `undefined`, because what the parser gives to be `run` with the `Interpreter` is a `StatementList`.

Changing the `break` to an early return wouldn't change the current flow, right?

**Comment by JayHelton** [comment]
Hello! Is this available to work on?

**Comment by jasonwilliams** [comment]
@JayHelton i believe so!
