### ISSUE TITLE
Use test262 data to generate page to show our conformance

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#719]
Boa generates TEST262 data on every PR. 
It then dumps out some JSON files which chart how conformant we are compared to the test262 suite.

Currently we do nothing with this data.
It would be good to it to our `gh-pages` branch and use it to generate a static page.

You can test this locally by running.
`cargo run --release --bin boa_tester -- -o gh-pages/test262`
then inspecting the JSON output.

I'm easy on charting library.

1. We should have a new github action that runs test262 (weekly?) and generates data
2. Use that data to generate a page on github.io

**Comment by Razican** [comment]
This was already implemented.
