### ISSUE TITLE
obj.toString() should be "[object Object]" S8.6.2_A3

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#729]
During Test262 we have https://github.com/tc39/test262/blob/master/test/language/types/object/S8.6.2_A3.js failing.
You can test this by setting your js file to...

```
let obj = {};
obj.toString();
```

The output should be "[object Object]"

The issue here is we're using the internal display rather than what the JS developer should be seeing.
https://github.com/boa-dev/boa/blob/master/boa/src/builtins/object/mod.rs#L120 could be changed to "[object Object]"

We will need to implement a way for us to debug the insides of objects, but this should be left to another method, like `print()` etc

Contributing: https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md
Debugging: https://github.com/boa-dev/boa/blob/master/docs/debugging.md

**Comment by RageKnify** [comment]
The insides of objects can still be seen normally, this only changes the output of this method. I'll open a PR ASAP.
