### ISSUE TITLE
Potential false-negatives from the test runner.

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#731]
We seem to have some tests which show a red dot after running, but work fine when ran manually.
Here are 2 examples I've found:

https://github.com/tc39/test262/blob/master/test/language/types/object/S8.6_A3_T1.js
https://github.com/tc39/test262/blob/master/test/language/types/reference/8.7.2-3-1-s.js

## Steps to reproduce

- I set up test262 following https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md#testing
- To speed things up I deleted all the other folders bar `language/types` in `test262`.
- added `dbg!(&self.content);` here https://github.com/boa-dev/boa/blob/master/tester/src/exec.rs#L86 - This is so i can see which test ran by looking at the source
- ran `cargo run --release --bin boa_tester -- -v`

**Comment by Razican** [comment]
We do have false negatives, most of them because we can't load the pre-requisites for the test for not implementing for..of for..in. also some others because we don't check error types.
