### ISSUE TITLE
Symbols cannot be defined as a property

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#732]
```js
var obj = {};
var s = Symbol('1');
Object.defineProperty(obj, s);
```
Outputs: `Uncaught "TypeError": "can't convert symbol to string"`

The problem starts here:
https://github.com/boa-dev/boa/blob/master/boa/src/builtins/object/mod.rs#L101 we try to coarce the key into a `string` type. We shouldn't need to do this as Property's already support Symbols as keys. We should pass the argument straight through to PropertyKey::from() and let it sort it out.

PropertyKey is defined here:
https://github.com/boa-dev/boa/blob/master/boa/src/property/mod.rs#L290-L294

Contributing: https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md
Debugging: https://github.com/boa-dev/boa/blob/master/docs/debugging.md

**Comment by georgeroman** [comment]
I can take this one.

**Comment by jasonwilliams** [comment]
Thanks @georgeroman assigned
