### ISSUE TITLE
redeclaration with FunctionDeclaration (LexicalDeclaration (const) should early error

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#740]
running:

```js
{ const f = 0; const f = 0 }
```
cause the engine to panic with:
`thread 'main' panicked at 'Identifier f has already been declared'`

but 
```js
{ const f = 0; function f() {} }
```

passes fine.

The expectation is that the latter should do the same as the former.

**Comment by iamsaquib8** [comment]
I'd like to work on this

**Comment by jasonwilliams** [comment]
Thanks @iamsaquib8 assigned

**Comment by Razican** [comment]
This has been patched in the latest releases, but we might want to re-check the spec compliance in the future.
