### ISSUE TITLE
break = 1; gives Uncaught "TypeError" instead of Uncaught "SyntaxError"

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#741]
```js
break = 1;
```

`Uncaught "TypeError": "expected token 'identifier', got '=' in binding identifier at line 1, col 7"`

The above should be:

Uncaught SyntaxError: "expected token 'identifier', got '=' in binding identifier at line 1, col 7"`

Taken from:
https://github.com/tc39/test262/blob/master/test/language/keywords/ident-ref-break.js

Contributing: https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md
Debugging: https://github.com/boa-dev/boa/blob/master/docs/debugging.md

**Comment by iamsaquib8** [comment]
Can I take this?
