### ISSUE TITLE
Implement String.prototype.codePointAt

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#751]
**ECMASCript feature**
Implement `String.prototype.codePointAt`

MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt
Spec: https://tc39.es/ecma262/#sec-string.prototype.codepointat

This code should now work and give the expected result:
```javascript
onst icons = '☃★♲';

console.log(icons.codePointAt(1));
// expected output: "9733"
```

It will be similar to our implementation of [`charCodeAt`](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/string/mod.rs#L136-L174)

Contributing: https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md
Debugging: https://github.com/boa-dev/boa/blob/master/docs/debugging.md

**Comment by andylim0221** [comment]
I would like to take up this issue.

**Comment by Razican** [comment]
> I would like to take up this issue.

Go ahead! :)

**Comment by croraf** [comment]
@andylim0221 Hi Andy. Any progress on this? Do you need some help?

**Comment by devinus** [comment]
Hope I'm not stepping on any toes, but I implemented this in https://github.com/boa-dev/boa/pull/935 as a learning exercise.
