### ISSUE TITLE
Throw TypeError if regex is passed to String.prototype.startsWith 

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#755]
In our implementation of `String.prototype.startsWith` we're not type checking the argument and blindly coercing it into a string.
https://github.com/boa-dev/boa/blob/master/boa/src/builtins/string/mod.rs#L301

We should match on the value (or if let) and if its a regular expression throw a type error:

```rust
ctx.throw_type_error("First argument to String.prototype.startsWith must not be a regular expression")?;
```

There should be a test also

Same here: https://github.com/boa-dev/boa/blob/master/boa/src/builtins/string/mod.rs#L344
and here: https://github.com/boa-dev/boa/blob/master/boa/src/builtins/string/mod.rs#L390

Example JS
```
const str1 = 'Saturday night plans';
console.log(str1.startsWith(/saturday/));
```

Contributing: https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md
Debugging: https://github.com/boa-dev/boa/blob/master/docs/debugging.md

**Comment by pt2121** [comment]
Can I take a stab at this?
