### ISSUE TITLE
Throw Syntax error instead of Panic in environment errors

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#756]
Now that we have `SyntaxError` defined in [`Context`](https://github.com/boa-dev/boa/blob/master/boa/src/context.rs#L229-L235) we should use it instead of Panicing.

Our environments Panic when a binding has already been declared.
https://github.com/boa-dev/boa/blob/master/boa/src/environment/declarative_environment_record.rs#L47

But these can be switched to use the `ctx` instead.
Example here: https://github.com/boa-dev/boa/blob/master/boa/src/object/gcobject.rs#L169

This does mean needing to pass `ctx` into Environments when using them, like here:
https://github.com/boa-dev/boa/blob/master/boa/src/builtins/function/mod.rs#L127

or `Environment` will need to access them some other way, this can be discussed and looked at

Contributing: https://github.com/boa-dev/boa/blob/master/CONTRIBUTING.md
Debugging: https://github.com/boa-dev/boa/blob/master/docs/debugging.md

**Comment by mersinvald** [comment]
I'll be happy to pick this up on the weekend

**Comment by jasonwilliams** [comment]
Thanks @mersinvald

**Comment by mersinvald** [comment]
@jasonwilliams I have tried to pass the `&mut Context ` as an additional parameters to the methods in `EnvironmentRecordTrait`, but that causes a borrowing issue, as environments are stored in Realm, and Realm is stored in Context, hence there's a dependency cycle.

The possible solution I see is to return a `Call` from `construct_*_error` methods, so the caller could choose when it's possible to execute the error, and thus make the `construct` error methods static, and usable from inside the Environments.

What do you think?

**Comment by jasonwilliams** [comment]
I wonder if some sort of [`Pinning`](https://doc.rust-lang.org/std/pin/index.html) would work, as they're all on the same struct and should have the same lifetime. @Razican @HalidOdat for thoughts. 

I would have to take a further look at what you described to see if thats ergonomic

**Comment by mersinvald** [comment]
Here's one example when there is a mutable borrow cycle: https://github.com/boa-dev/boa/blob/master/boa/src/syntax/ast/node/operator/assign/mod.rs#L59

If the `interpreter` is passed as a parameter to `create_mutable_binding` here, then `interpreter` is borrowed mutably twice.
I don't think pinning can help here.

**Comment by Razican** [comment]
This has been patched in the last commits in master. In the future we might want to improve how this works, as we just "allow" some re-definitions, but I'm not sure if this is spec compliant.
