### ISSUE TITLE
[Error builtin] does not output "name" property correctly

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#791]
**Describe the bug**
`Error` builtin and its subclasses don't output "name" property correctly

**To Reproduce**
`new Error().name;`
should show "Error", instead it shows `Uncaught "Error": ""`

also `new SyntaxError().name;`
should show "SyntaxError", instead it shows `Uncaught "SyntaxError": ""`

**Environment**

- OS: [e.g. Fedora Linux]
- Version: [e.g. 32]
- Target triple: [e.g. x86_64-unknown-linux-gnu]
- Rustc version: [e.g. rustc 1.43.0 (4fb7144ed 2020-04-20), running `rustc -V`]

**Additional context**

**Comment by HalidOdat** [comment]
@croraf I think #749 should fix this issue, right? since `new Error()` or `Error()` just throws the error immediately

**Comment by croraf** [comment]
I don't know if it will fix it, but if "new Error()" throws immediately, we should definitely prioritize that PR, and then check this again.

**Comment by RageKnify** [comment]
Yeah, #749 will fix this.
