### ISSUE TITLE
Spread operator on a non-iterable panics

### ISSUE THREAD

**Issue by dapper-gh** [boa-dev/boa#793]
**Describe the bug**
A panic occurs when running the spread operator on a non-iterable.
![image](https://user-images.githubusercontent.com/31050943/95032422-7567fc00-0688-11eb-9f29-59389020342b.png)
The panic occurs at line `42` in file `syntax/ast/node/array/mod.rs`.

**To Reproduce**
```js
[...5]
```

**Expected behavior**
A JavaScript error is raised. Chrome seems to raise a `TypeError`, as seen below.
![image](https://user-images.githubusercontent.com/31050943/95032192-a98eed00-0687-11eb-8d01-e87a0a1c580a.png)
Additionally, the [spec](https://tc39.es/ecma262/#sec-getiterator) states that a `TypeError` should be raised.

**Build environment (please complete the following information):**

- OS: `Windows 10`
- Version: `Version 1909 (OS Build 18363.1082)`
- Target triple: `x86_64-pc-windows-msvc`
- Rustc version: `rustc 1.46.0 (04488afe3 2020-08-24)`

**Additional context**
MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)
Spec: [https://tc39.es/ecma262/#sec-array-initializer](https://tc39.es/ecma262/#sec-array-initializer)

**Comment by croraf** [comment]
I'll try this. I'll maybe need help on discord though.
