### ISSUE TITLE
Calling "new" on a primitive value does not throw an error

### ISSUE THREAD

**Issue by dapper-gh** [boa-dev/boa#801]
**Describe the bug**
Calling `new` on a primitive value (or, in other words, calling a primitive value as a constructor) does not error.

**To Reproduce**
```js
const a = "";
new a();
```

**Expected behavior**
A `TypeError` is supposed to be raised. The spec can be found [here](https://tc39.es/ecma262/#sec-new-operator) (step 7). Chrome implements this properly:
![image](https://user-images.githubusercontent.com/31050943/95126567-b6ade980-0724-11eb-9b26-18a718200d35.png)

**Build environment (please complete the following information):**

- OS: `Windows 10`
- Version: `Version 1909 (OS Build 18363.1082)`
- Target triple: `x86_64-pc-windows-msvc`
- Rustc version: `rustc 1.46.0 (04488afe3 2020-08-24)`

**Additional context**
MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new)
Spec: [https://tc39.es/ecma262/#sec-evaluatenew](https://tc39.es/ecma262/#sec-evaluatenew)

**Comment by HalidOdat** [comment]
The problem is here `boa/src/syntax/ast/node/new/mod.rs:58` we should throw a `TypeError` (with `.throw_type_error()`), but instead we are returning `undefined`

**Comment by dlemel8** [comment]
Hey @HalidOdat , I want to do this.
Thanks.
