### ISSUE TITLE
Strict Mode Interpreter

### ISSUE THREAD

**Issue by Lan2u** [boa-dev/boa#815]
**ECMASCript feature**
Strict mode support for the interpreter as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode.

**Example code**
```
'use strict';
(14).sailing = 'home';
```
This code should throw a type error but currently returns 'home'.

The parser/lexer side of this was previously implemented as #717.

**Comment by raskad** [comment]
With #1550 we have `strict` flags available during the execution. I think we can close this and track individual implementations of `strict` handling in separate issues.
