### ISSUE TITLE
The `Array()` constructor is not spec compliant

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#816]
**Describe the bug**
The `Array()` constructor is not spec compliant. When creating a huge array, for example:
```javascript
let a = new Array(50000);
```

This will try to actually insert 50k properties in the array. The [spec](https://tc39.es/ecma262/#sec-array-constructor-array) says otherwise. It should only set the length, and should not create any other property.

This happens because [our implementation](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/array/mod.rs#L100-L140) is not spec compliant. We should have 3 private constructor methods (`construct_array`, `construct_array_length` and `construct_array_items`), and they should be called from the `constructor` method. In each of them, we should have information about the exact spec, and use the actual spec implementation.

This means we will need to create an `array_create` function, that will follow [this](https://tc39.es/ecma262/#sec-arraycreate) spec.

A similar thing should be done with the rest of the `Array` prototype methods.

**Comment by georgeroman** [comment]
I can take this one.

**Comment by Razican** [comment]
> I can take this one.

Go ahead! :D let us know if you need guidance
