### ISSUE TITLE
Improve our GitHub pages site by not requiring vendored code

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#821]
We currently require Bootstrap and jQuery to be included in the GitHub pages branch. This is not ideal, and we should somehow just create a static page with a `node_modules` or with a webpacked script that includes all the requirements.

This should be available for both the Test262 test suite and for the benchmarks, that should then be linked from the demo and the main website.

**Comment by neeldug** [comment]
Couldn't this be done with a CDN instead of holding the assets locally?

**Comment by Razican** [comment]
> Couldn't this be done with a CDN instead of holding the assets locally? Unless you want updated versioning somehow, in which case it probably should be done with webpack.

Indeed, that would probably be an easy improvement.

**Comment by neeldug** [comment]
> Indeed, that would probably be an easy improvement.

Also, I'm currently unable to see where jQuery's being included on the `gh-pages` branch. Any help on where to find it would be much appreciated!

**Comment by Razican** [comment]
> > Indeed, that would probably be an easy improvement.
> 
> Also, I'm currently unable to see where jQuery's being included on the `gh-pages` branch. Any help on where to find it would be much appreciated!

It's being included in #769.

**Comment by neeldug** [comment]
> It's being included in #769.

Alright, I see, I'll just wait for 769 to land before I make the changes since they aren't too urgent!

**Comment by neeldug** [comment]
Rebase ended up pulling in loads of commits, so just created a fresh branch since changes were simple enough!
