### ISSUE TITLE
We cannot run some Test262 include files

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#823]
Currently, when running the Test262 ECMAScript conformance test suite, some files that need to be included by the tester are not working properly. We need to fix all of them to be able to run the whole test suite. This is the tracking issue:

 - [ ] [`atomicsHelper.js`](https://github.com/tc39/test262/blob/main/harness/atomicsHelper.js)

<details>
<summary>Details</summary>
<pre>Uncaught ReferenceError: $262 is not defined</pre>
</details>

 - [ ] [`nativeFunctionMatcher.js`](https://github.com/tc39/test262/blob/main/harness/nativeFunctionMatcher.js)

<details>
<summary>Details</summary>
<pre>Uncaught SyntaxError: Invalid regular expression literal: Invalid unicode escape at position: 20:26</pre>
</details>

These files are stored in the `harness` folder of the test suite. To run a check, run:

```
cargo run -- test262/harness/assert.js test262/harness/sta.js test262/harness/<file>
```

**Comment by ashoksrinivasan96** [comment]
Hi Razican,

I have forked your code. Can you please assign this task to my name, so that we can save some efforts of others, who would be planning to work on this?

Regards,
Ashok

**Comment by RageKnify** [comment]
Good luck @ashoksrinivasan96 , if you need any help you can talk here, open a draft PR or visit our Discord.

**Comment by Razican** [comment]
For the case of `regExpUtils.js`, the error is a parsing error:
```
Uncaught "SyntaxError": "expected token 'identifier', got '{' in binding identifier at line 9, col 22"
```

This is due to us not fully implementing `FormalParameters` parsing. The [spec](https://tc39.es/ecma262/#prod-FormalParameters) shows how each formal parameter must be a [`BindingElement`](https://tc39.es/ecma262/#prod-BindingElement) (or a rest parameter, which we do check).

We currently only check for a `SingleNameBinding`, and even there, we don't check for the optional `Initializer`. But, we do not check a [`BindingPattern`](https://tc39.es/ecma262/#prod-BindingPattern).

The idea here would be to implement both the optional `Initializer` and the `BindingPattern`. This shouldn't be super difficult at the parser level. When parsing a `FormalParameter`, if we `peek()` our lexer cursor and we see a `[` or a `{`, then, this is a `BindingPattern`, if not, it's a `SingleNameBinding`.

Then, we should create the `BindingPattern` parser and the `SingleNameBinding` parser (which I'm not sure we already do).

This requires changes to the AST nodes, and a whole different thing would be to execute it. But at least it can be done in steps, first the parsing and the AST node generation, and then in a second step, we can do the execution.

**Comment by ashoksrinivasan96** [comment]
Hi,

I installed Rust and the mentioned tech in the readme. However, when I do cargo -- test.js, i get the following error:
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.

This would be my first ever attempt for open source contribution and also I have zero experience with Rust, and have experience only with Javascript. So please forgive me if I mentioned something obvious or stupid.

**Comment by RageKnify** [comment]
Currently we need to specify which binary to run, we have `boa` and `boa_tester`, you'd need to change your command to `cargo run --bin boa -- test.js`.

**Comment by Razican** [comment]
We should update the readme with this new information

**Comment by AnnikaCodes** [comment]
I'm going to work on this as well

**Comment by Razican** [comment]
I think this is not up to date anymore. We should review if this is still happening, and revisit the list above.

**Comment by Razican** [comment]
I have updated the list. Only 2 are still broken:
 - `atomicsHelper.js`
 - `timer.js`

The first one is failing because it's considering the `await` keyword as an identifier, since we still haven't implemented async/await.

The reason for the 2nd one is that we don't yet implement the `Promise` object (or async/await). In any case, we might be able to implement the `Promise` object even before having async/await support.

BTW, you can run the checks with the following command:
```bash
cargo run -- test262/harness/assert.js test262/harness/sta.js test262/harness/<file>
```

**Comment by Razican** [comment]
`timer.js` issues have been solved, and `atomicsHelper.js` now parses correctly. Unfortunately, not everything is done. In `atomicsHelper.js`, we get a `$262 not defined` error if we run it directly with the `boa` CLI, since `$262` is not defined there, but when running it in the test suite, we're missing agents.

Then, `nativeFunctionMatcher.js` parses correctly, but there seems to be an issue with a regular expression. Maybe due to missing features in `regress`.

**Comment by jedel1043** [comment]
Fixed. Aside from a Temporal helper that is failing because our Temporal implementation is WIP, the rest of the helpers work perfectly fine.
