### ISSUE TITLE
Profiler no longer works with measureme 9.0.0

### ISSUE THREAD

**Issue by neeldug** [boa-dev/boa#839]
**Describe the bug**
The profiler no longer functions as there was a breaking change in `measureme` from 0.8.0 to 9.0.0

**To Reproduce**
```
cargo run --features Boa/profiler <some.js>
```

**Expected behavior**
The profiler to produce a profile

**Comment by jasonwilliams** [comment]
Thanks for raising this @neeldug i thought it was just me going mad, are our dependencies not locked? How did we update to their latest?

**Comment by neeldug** [comment]
@jasonwilliams I think it might’ve been merged with dependabot, since profiler isn’t tested in our current test suite, perhaps we should create one?

**Comment by jasonwilliams** [comment]
@wesleywiser how big of a migration is this? is there a migration guide?

**Comment by wesleywiser** [comment]
@jasonwilliams It should be pretty easy. Here's the PR I opened up upgrade rustc: https://github.com/rust-lang/rust/pull/77398

**Comment by neeldug** [comment]
@jasonwilliams here's a screenshot of the original errors: ![img](https://i.ibb.co/ZY7bDzw/Screenshot-2020-10-10-at-23-42-09.png), currently it's working but not associating the `SerializationSink` struct as it's no longer accepted.
