### ISSUE TITLE
terminology - replace "statements" property in StatementList struct with "statement_list_items"

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#842]
This term will be more compliant with the standard.

These items can be both statements and declarations.

**Comment by Lan2u** [comment]
Could u send a spec link?

**Comment by Razican** [comment]
In the case we change this, I would just call it `items`.

**Comment by croraf** [comment]
https://tc39.es/ecma262/#prod-StatementList

**Comment by jasonwilliams** [comment]
I’m ok with just items

**Comment by AnnikaCodes** [comment]
I'm going to work on this - do we want to change the `statements()` method in the impl or just the property?

Personally I think that it should be changed, since it could contain declarations.
