### ISSUE TITLE
[parser - expression] Some nodes of the resultant AST tree are missing

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#843]
**Describe the bug**
When parsing the following code: 
```
let a;
a++;
```

I get the following AST printout:
```
StatementList {
        statements: [
            ...declaration staterment here...,
            UnaryOp(
                UnaryOp {
                    op: IncrementPost,
                    target: target: Identifier(
                        Identifier {
                            ident: "a",
                        },
                    ),
                },
            ),
        ],
    },
```

This second statement_list_item should be :
1. In a `Statement` node, type of statement_list_item (statement or declaration) is not visible
2. Then in an `TypeOfStatement` node (I guess this should be an `ExpressionStatement`)
3. etc...
4. Up to the `UpdateExpression` node

**Comment by croraf** [comment]
I checked a bit more, and indeed there are like 7-8 expressions between `ExpressionStatement` and `UpdateExpression`.

**Comment by Lan2u** [comment]
You get target Const(Int(5)) as output?

**Comment by croraf** [comment]
Edited.

**Comment by Razican** [comment]
I think this implies we should have on AST node per production, but I don't think that should be the case, right?

**Comment by croraf** [comment]
I'm actually not sure what should the logic be about presenting or not the Node.

**Comment by Razican** [comment]
> I'm actually not sure what should the logic be about presenting or not the Node.

Our current approach, since the parser is written manually, is to manually simplify + optimise each node.

**Comment by Razican** [comment]
I'm closing this now. It can be opened again in the future if we find a better way of representing this.
