### ISSUE TITLE
Map.prototype.values() method not implemented

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#845]
**ECMASCript feature**
https://www.ecma-international.org/ecma-262/11.0/index.html#sec-map.prototype.values

**Example code**

```
const map1 = new Map();

map1.set('0', 'foo');
map1.set(1, 'bar');

const iterator1 = map1.values();

console.log(iterator1.next().value);
// expected output: "foo"

console.log(iterator1.next().value);
// expected output: "bar"
```

**Comment by JohnDoneth** [comment]
I have that exact code working in a test on a branch. Implementation needs more work though. I will submit a PR when it's ready for review.
