### ISSUE TITLE
SyntaxError not generated for duplicate identifier names with let declarations

### ISSUE THREAD

**Issue by 54k1** [boa-dev/boa#858]
**To Reproduce**
```JavaScript
>> let x = 12;
undefined
>> var x = 12;
undefined
```

**Expected behavior**
SyntaxError must be thrown by the parser. Environment is not supposed to deal with this according to the spec.

I think [here](https://www.ecma-international.org/ecma-262/11.0/index.html#sec-let-and-const-declarations-static-semantics-early-errors) is where the spec talks about syntax error in `let` declaration.

**Comment by croraf** [comment]
I think this section of the spec talks only when you declare two variables of the same name in the same declaration statement.

Shown example should be a runtime error.

**Comment by croraf** [comment]
I think I'm correct because I compared the following two in Chrome:
```js
let x;
try {
  let x;
} catch (er) {}
```
> undefined

```js
try {
let x, x;
} catch (er) {}
```
> Uncaught SyntaxError: Identifier 'x' has already been declared
