### ISSUE TITLE
Warning on our Linux test suite

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#868]
GitHub has recently deprecated `set-env` and `add-path` commands in GitHub actions due to a security vulnerability. You can read the blog post [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).

The issue is that our `actions-rs/tarpaulin` action is using the `add-path` command, which is giving us this warning:
```
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

This is being tracked in the upstream issue https://github.com/actions-rs/tarpaulin/issues/11, but if it's not solved on time, we might need to stop using that action.

An example of workflow execution with the warning can be found [here](https://github.com/boa-dev/boa/actions/runs/305899899).

**Comment by jasonwilliams** [comment]
Thanks, lets see if they respond to that issue

**Comment by RageKnify** [comment]
Fixed in https://github.com/actions-rs/tarpaulin/pull/14
Warning no longer found in recent runs like https://github.com/boa-dev/boa/actions/runs/406858058
Noted by 0xfada on Discord
