### ISSUE TITLE
Implement `Function.prototype.apply()`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#872]
Implement `Function.prototype.apply()` , the implementation would go in `src/builtins/function/mod.rs` and the tests in `src/builtins/function/tests.rs`

[ECMAScript specification](https://tc39.es/ecma262/#sec-function.prototype.apply)

**Example code**

This code should now work and give the expected result:
```javascript
const numbers = [5, 6, 2, 3, 7];

const max = Math.max.apply(null, numbers);

console.log(max);
// expected output: 7

const min = Math.min.apply(null, numbers);

console.log(min);
// expected output: 2
```

**Comment by georgeroman** [comment]
I can take this one.
