### ISSUE TITLE
Empty statements not fully implemented

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#892]
Currently, a code like this one will work fine:
```javascript
let a = 10;;;
```

But, this one is broken:
```javascript
;;;let a = 10;;
```

This is because if a statement list starts with an empty statement, we only check if it's a closing brace or not, bug it it's not, we just try to parse a `StatementListItem`, which will fail.

All this is implemented in [this](https://github.com/boa-dev/boa/blob/master/boa/src/syntax/parser/statement/mod.rs#L308-L338) loop, and an equivalent one [here](https://github.com/boa-dev/boa/blob/master/boa/src/syntax/parser/statement/mod.rs#L269-L290).

As you can see, before looping again, we do consume any repeated semicolons, so the first example works, but not the second one.

Ideally, we should add an extra branch to the first check in both loops, to see if the next item is a semicolon. If it is, just call `continue;` after consuming the token. With this, we can remove the while loop at the end of the loop.

**Comment by croraf** [comment]
I will check this a bit.

**Comment by AngelOnFira** [comment]
@croraf Just want to check in, I kinda want to look into this as well so just wanted to see how you were doing. Also, no guarantees that I would even be able to, I'm just reading through the codebase now :sweat_smile:

**Comment by croraf** [comment]
@AngelOnFira Join on discord so we can discuss and coordinate. Dont hesitate to pong me there.

**Comment by croraf** [comment]
As we agreed this PR shouldnt close this issue. I think this is the case. A separate PR has to be made with the actual fix.

**Comment by SamuelQZQ** [comment]
@Razican Could I take this task?

**Comment by Razican** [comment]
> @Razican Could I take this task?
> 

Sure, go ahead!

**Comment by SamuelQZQ** [comment]
@Razican After some investigation, I think we cannot fix it with modification in this [method](https://github.com/boa-dev/boa/blob/master/boa/src/syntax/parser/statement/mod.rs#L263-L290).

If we only fix it in `StatementList`, some other empty statement will still fail. For example:
- `if(someFunction()) ;`

To implement the EmptyStatement completely, I think we still should parse it in `Statement`, and add a new `Node` type: `Empty`. Just the same as the [statement section in ecma262 spec](https://tc39.es/ecma262/#prod-Statement).
