### ISSUE TITLE
Implement TypedArray objects

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#893]
**ECMASCript feature**
It would be very nice to get `TypedArray` objects. They are making us fail / ignore many tests in our ECMAScript conformance suite, and they shouldn't be super difficult to implement using our current builtin objects as a template.

You can find the full specification [here](https://tc39.es/ecma262/#sec-typedarray-objects).

**Example code**
This code from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) should give the expected results:
```javascript
const typedArray1 = new Int8Array(8);
typedArray1[0] = 32;

const typedArray2 = new Int8Array(typedArray1);
typedArray2[1] = 42;

console.log(typedArray1);
// expected output: Int8Array [32, 0, 0, 0, 0, 0, 0, 0]

console.log(typedArray2);
// expected output: Int8Array [32, 42, 0, 0, 0, 0, 0, 0]
```

**Implementation tips**
To implement these, we should create a new module [here](https://github.com/boa-dev/boa/tree/master/boa/src/builtins) called `typed_arrays`, and a submodule for each variant. You can see an example of a built-in object implementation [here](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/number/mod.rs#L35).

**Comment by georgeroman** [comment]
I can take this one.

**Comment by georgeroman** [comment]
I'm a bit busy at the moment, so if anyone else wants to take this one feel free to do so.

**Comment by apatniv** [comment]
Can I take this one if no one else is working on it?

**Comment by croraf** [comment]
@apatniv Any progress on this one. Perhaps it can be handled with multiple PRs if at once it is too big. Also join the discord if you need discussion.

**Comment by kvnvelasco** [comment]
Can I take this?

**Comment by Razican** [comment]
> Can I take this? 

Go ahead! I assigned it to you :) let us know if you'd like any guidance.

**Comment by kvnvelasco** [comment]
Okay so I've put up some code and I'm still 90% lost about how a bunch of things work. Is the discord the best place to get guidance? Right now i can `const x = UInt8Array(3); x.length === 3`

**Comment by Razican** [comment]
I think this is a pretty complex task. I've been playing with it for some days and I think I can propose something soon, so I'm assigning it to me.
