### ISSUE TITLE
Implement URI Handling Functions

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#894]
**ECMASCript feature**
We currently lack the implementation of some built-in global functions used for URI encoding/decoding. You can find these functions in the spec [here](https://tc39.es/ecma262/#sec-uri-handling-functions).

The 4 functions to implement would be these:
 - [`encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)
 - [`encodeURIComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)
 - [`decodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI)
 - [`decodeURIComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent)

In those links you can find example code that should work after this implementation.

**Implementation tips**
We should probably create a new module [here](https://github.com/boa-dev/boa/tree/master/boa/src/builtins) for these functions. An example of a built-in global function implementation can be seen [here](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/number/mod.rs#L83).

**Comment by sidntrivedi012** [comment]
Hey @Razican , I would like to work on it. Thanks :)

**Comment by Razican** [comment]
Hi @sidntrivedi012 how is this going?

**Comment by captain-yossarian** [comment]
I will be happy to take a look if @sidntrivedi012 don't mind

**Comment by tofpie** [comment]
Go ahead @captain-yossarian

**Comment by captain-yossarian** [comment]
@tofpie  @Razican 
Just leave here link to [wip pr](https://github.com/boa-dev/boa/pull/1094)

**Comment by captain-yossarian** [comment]
@Razican  Can I use this [percent_encoding crrate](https://docs.rs/percent-encoding/2.0.0/percent_encoding/index.html) ?

**Comment by Razican** [comment]
> @Razican @tofpie Should/Can I use this [percent_encoding crrate](https://docs.rs/percent-encoding/2.0.0/percent_encoding/index.html) ?

Hi, yes, if it makes sense to use it, feel free :)

**Comment by jedel1043** [comment]
Unassigned the issue by @captain-yossarian's request. For anyone interested, feel free to ping us if you want to work on this😁

**Comment by jtara1** [comment]
I'll take a look at this, please assign to me.

**Comment by jedel1043** [comment]
@jtara1 I've asigned it to you. Let us know if you need some pointers to get started :)

**Comment by jtara1** [comment]
I got something working with that crate ^
but I'm trying to just follow their algo directly in the ecma spec now

What's the return values for this function? https://github.com/jtara1/boa/blob/8ba500a26afdad8e200c9990b375664b5c04a97a/boa/src/builtins/string/mod.rs#L36

**Comment by jedel1043** [comment]
`code_point_at` just represents the operation [`CodePointAt`](https://tc39.es/ecma262/#sec-codepointat) from the spec. But maybe we could rewrite it to be more idiomatic with descriptive enum returns instead of `bool`s and `u8`s

**Comment by jtara1** [comment]
the spec answered my question with
>10. Return the Record { [[CodePoint]]: cp, [[CodeUnitCount]]: 2, [[IsUnpairedSurrogate]]: false }.
thanks

**Comment by jtara1** [comment]
So far the hardest part of this is figuring out what the transformation algo (for singles & pairs) for code point -> utf-8 encoded byte(s) is. https://en.wikipedia.org/wiki/UTF-8 which actually seems like the most thorough explanation for this

I'm also checking the node.js implementation of this https://github.com/nodejs/node/blob/e46c680bf2b211bbd52cf959ca17ee98c7f657f5/deps/v8/src/strings/uri.cc#L279

and

```C++
void EncodeSingle(uc16 c, std::vector<uint8_t>* buffer) {
  char s[4] = {};
  int number_of_bytes;
  number_of_bytes =
      unibrow::Utf8::Encode(s, c, unibrow::Utf16::kNoPreviousCharacter, false);
  for (int k = 0; k < number_of_bytes; k++) {
    AddEncodedOctetToBuffer(s[k], buffer);
  }
}

void EncodePair(uc16 cc1, uc16 cc2, std::vector<uint8_t>* buffer) {
  char s[4] = {};
  int number_of_bytes =
      unibrow::Utf8::Encode(s, unibrow::Utf16::CombineSurrogatePair(cc1, cc2),
                            unibrow::Utf16::kNoPreviousCharacter, false);
  for (int k = 0; k < number_of_bytes; k++) {
    AddEncodedOctetToBuffer(s[k], buffer);
  }
}
```

**Comment by joshwd36** [comment]
Would it be worth looking into #736 again? It seems that the implementation will be pretty closely tied to the encoding

**Comment by jedel1043** [comment]
> Would it be worth looking into #736 again? It seems that the implementation will be pretty closely tied to the encoding

Yeah, maybe. We could reevaluate if there's a way to adapt our regex to consume UTF-16, then change the definition of `JsString`.
