### ISSUE TITLE
Implementing the eval function

### ISSUE THREAD

**Issue by NathanRoyer** [boa-dev/boa#948]
**ECMASCript feature**
The `eval` JS function is currently not implemented in boa, although it is quite common to encounter in the wild.
The spec describes this function [here](https://tc39.es/ecma262/#sec-eval-x).

**Example code**
```js
eval('6'); // returns 6
eval(' } '); // throws a syntax error

let someCode = 'f1("param");\nf2()';
eval(someCode);
/* is equivalent to */
f1("param");
f2()
```

**Pitfalls**
The spec for this function is pretty long, and two algorithms should be implemented in total:
 * [PerformEval](https://tc39.es/ecma262/#sec-evaldeclarationinstantiation)
 * [EvalDeclarationInstantiation](https://tc39.es/ecma262/#sec-performeval)

This excludes [HostEnsureCanCompileStrings](https://tc39.es/ecma262/#sec-hostensurecancompilestrings) because it gets complex in JS compilers only.

**Implementation tips**
`eval` is global built-in object, so its module should reside in `boa/src/builtins/eval`.

**Comment by AnnikaCodes** [comment]
I'd like to take a stab at this.

**Comment by Razican** [comment]
> I'd like to take a stab at this.

Go ahead! :)

**Comment by jedel1043** [comment]
Apparently to implement this function we need to support an execution context stack with at least 2 contexts ([context stack spec](https://tc39.es/ecma262/#execution-context-stack)), meaning this issue is blocked by #186.

**Comment by jasonwilliams** [comment]
@jedel1043 i made a start on that here https://github.com/boa-dev/boa/pull/1342 feel free to review

**Comment by Razican** [comment]
> @jedel1043 i made a start on that here https://github.com/boa-dev/boa/pull/1342 feel free to review (there's very little there right now)

I still think we need to implement the stack of contexts outside the VM branch too, to allow implementing the `eval()` function while the VM branch gets to feature parity.

I think the PR you mention implements the execution stack in the VM, though, right? I think this is a different thing.

**Comment by jedel1043** [comment]
> > @jedel1043 i made a start on that here #1342 feel free to review (there's very little there right now)
> 
> I still think we need to implement the stack of contexts outside the VM branch too, to allow implementing the `eval()` function while the VM branch gets to feature parity.

I agree. Ideally we would have an `Agent` struct as the [spec](https://tc39.es/ecma262/#sec-agents) requires, but while that's not implemented we could maybe refactor `Context` to have an `execution_context_stack: Vec<ExecutionContext>` and a `running_execution_context` function, that way we could pass the context to `eval` and obtain an execution context to run the code from.

**Comment by jasonwilliams** [comment]
> > > @jedel1043 i made a start on that here #1342 feel free to review (there's very little there right now)
> > 
> > 
> > I still think we need to implement the stack of contexts outside the VM branch too, to allow implementing the `eval()` function while the VM branch gets to feature parity.
> 
> I agree. Ideally we would have an `Agent` struct as the [spec](https://tc39.es/ecma262/#sec-agents) requires, but while that's not implemented we could maybe refactor `Context` to have an `execution_context_stack: Vec<ExecutionContext>`, that way we could pass the context to `eval` and obtain an execution context to run the code from.

I wouldn’t want to invest time doing that on the tree-walking side when we’re going to move away from that direction in future.

**Comment by jedel1043** [comment]
> > > > @jedel1043 i made a start on that here #1342 feel free to review (there's very little there right now)
> > > 
> > > 
> > > I still think we need to implement the stack of contexts outside the VM branch too, to allow implementing the `eval()` function while the VM branch gets to feature parity.
> > 
> > 
> > I agree. Ideally we would have an `Agent` struct as the [spec](https://tc39.es/ecma262/#sec-agents) requires, but while that's not implemented we could maybe refactor `Context` to have an `execution_context_stack: Vec<ExecutionContext>`, that way we could pass the context to `eval` and obtain an execution context to run the code from.
> 
> I wouldn’t want to invest time doing that on the tree-walking side when we’re going to move away from that direction in future.

Yeah, maybe the best approach would be to implement `Agent` right now (possibly on a separate branch) and merge the moment it's ready.

**Comment by Razican** [comment]
This is making many, many of the Test262 tests fail, since Test262 uses `eval()` a lot. Maybe we should prioritise this, so that we can get a more accurate representation of our conformance.
