### ISSUE TITLE
Implement property accessors

### ISSUE THREAD

**Issue by tofpie** [boa-dev/boa#986]
**ECMASCript feature**
I would like to see the property accessors parsing and execution implemented. [ECMAScript specification][spec].

[spec]: https://tc39.es/ecma262/#sec-property-accessors

**Example code**
This code should now work and give the expected result:
```javascript
let a = { get b() { return "c"}}
a.b
```
The expected output is `"c"`.

**Comment by RageKnify** [comment]
This is tied to #577, @HalidOdat was leading development on that, sadly you implemented it on `Value` in #987 , which would require us to change it all once we want to move the behaviour to `GcObject`...
@HalidOdat what are your thoughts?
